/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ChangePasswordRequest,
  ChangeUsernameRequest,
  CommonResponseVoid,
  SwaggerErrorResponse,
  WithdrawRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 사용자의 아이디를 변경합니다.
 * @summary [공통] 아이디 변경
 */
export type changeUsername1Response200 = {
  data: CommonResponseVoid
  status: 200
}

export type changeUsername1Response400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type changeUsername1Response409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type changeUsername1ResponseSuccess = (changeUsername1Response200) & {
  headers: Headers;
};
export type changeUsername1ResponseError = (changeUsername1Response400 | changeUsername1Response409) & {
  headers: Headers;
};

export type changeUsername1Response = (changeUsername1ResponseSuccess | changeUsername1ResponseError)

export const getChangeUsername1Url = () => {


  

  return `/api/account/change-username`
}

export const changeUsername1 = async (changeUsernameRequest: ChangeUsernameRequest, options?: RequestInit): Promise<changeUsername1Response> => {
  
  return customFetch<changeUsername1Response>(getChangeUsername1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changeUsernameRequest,)
  }
);}




export const getChangeUsername1MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUsername1>>, TError,{data: ChangeUsernameRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changeUsername1>>, TError,{data: ChangeUsernameRequest}, TContext> => {

const mutationKey = ['changeUsername1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeUsername1>>, {data: ChangeUsernameRequest}> = (props) => {
          const {data} = props ?? {};

          return  changeUsername1(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeUsername1MutationResult = NonNullable<Awaited<ReturnType<typeof changeUsername1>>>
    export type ChangeUsername1MutationBody = ChangeUsernameRequest
    export type ChangeUsername1MutationError = SwaggerErrorResponse

    /**
 * @summary [공통] 아이디 변경
 */
export const useChangeUsername1 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUsername1>>, TError,{data: ChangeUsernameRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeUsername1>>,
        TError,
        {data: ChangeUsernameRequest},
        TContext
      > => {
      return useMutation(getChangeUsername1MutationOptions(options), queryClient);
    }
    /**
 * 사용자의 비밀번호를 변경합니다.
 * @summary [공통] 비밀번호 변경
 */
export type changePassword1Response200 = {
  data: CommonResponseVoid
  status: 200
}

export type changePassword1Response400 = {
  data: SwaggerErrorResponse
  status: 400
}
    
export type changePassword1ResponseSuccess = (changePassword1Response200) & {
  headers: Headers;
};
export type changePassword1ResponseError = (changePassword1Response400) & {
  headers: Headers;
};

export type changePassword1Response = (changePassword1ResponseSuccess | changePassword1ResponseError)

export const getChangePassword1Url = () => {


  

  return `/api/account/change-password`
}

export const changePassword1 = async (changePasswordRequest: ChangePasswordRequest, options?: RequestInit): Promise<changePassword1Response> => {
  
  return customFetch<changePassword1Response>(getChangePassword1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePasswordRequest,)
  }
);}




export const getChangePassword1MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword1>>, TError,{data: ChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword1>>, TError,{data: ChangePasswordRequest}, TContext> => {

const mutationKey = ['changePassword1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword1>>, {data: ChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  changePassword1(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePassword1MutationResult = NonNullable<Awaited<ReturnType<typeof changePassword1>>>
    export type ChangePassword1MutationBody = ChangePasswordRequest
    export type ChangePassword1MutationError = SwaggerErrorResponse

    /**
 * @summary [공통] 비밀번호 변경
 */
export const useChangePassword1 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword1>>, TError,{data: ChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePassword1>>,
        TError,
        {data: ChangePasswordRequest},
        TContext
      > => {
      return useMutation(getChangePassword1MutationOptions(options), queryClient);
    }
    /**
 * 회원을 탈퇴 처리합니다. (Soft Delete)
 * @summary [공통] 회원 탈퇴
 */
export type withdrawResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type withdrawResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type withdrawResponse401 = {
  data: SwaggerErrorResponse
  status: 401
}
    
export type withdrawResponseSuccess = (withdrawResponse204) & {
  headers: Headers;
};
export type withdrawResponseError = (withdrawResponse400 | withdrawResponse401) & {
  headers: Headers;
};

export type withdrawResponse = (withdrawResponseSuccess | withdrawResponseError)

export const getWithdrawUrl = () => {


  

  return `/api/account/withdraw`
}

export const withdraw = async (withdrawRequest: WithdrawRequest, options?: RequestInit): Promise<withdrawResponse> => {
  
  return customFetch<withdrawResponse>(getWithdrawUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      withdrawRequest,)
  }
);}




export const getWithdrawMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,{data: WithdrawRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,{data: WithdrawRequest}, TContext> => {

const mutationKey = ['withdraw'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof withdraw>>, {data: WithdrawRequest}> = (props) => {
          const {data} = props ?? {};

          return  withdraw(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type WithdrawMutationResult = NonNullable<Awaited<ReturnType<typeof withdraw>>>
    export type WithdrawMutationBody = WithdrawRequest
    export type WithdrawMutationError = SwaggerErrorResponse

    /**
 * @summary [공통] 회원 탈퇴
 */
export const useWithdraw = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,{data: WithdrawRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof withdraw>>,
        TError,
        {data: WithdrawRequest},
        TContext
      > => {
      return useMutation(getWithdrawMutationOptions(options), queryClient);
    }
    