/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseAdminStoreResponse,
  CommonResponseCoordinate,
  CommonResponseLong,
  CommonResponsePageResponseAdminStoreResponse,
  CommonResponseString,
  CommonResponseVoid,
  GetGeocodeParams,
  GetStores1Params,
  StoreCreateRequest,
  StoreUpdateRequest,
  SwaggerErrorResponse,
  UploadStoreDataBody
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 조건에 따라 상점 목록을 조회합니다.
 * @summary [관리자] 상점 목록 페이징 조회
 */
export type getStores1Response200 = {
  data: CommonResponsePageResponseAdminStoreResponse
  status: 200
}
    
export type getStores1ResponseSuccess = (getStores1Response200) & {
  headers: Headers;
};
;

export type getStores1Response = (getStores1ResponseSuccess)

export const getGetStores1Url = (params?: GetStores1Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/stores?${stringifiedParams}` : `/api/admin/stores`
}

export const getStores1 = async (params?: GetStores1Params, options?: RequestInit): Promise<getStores1Response> => {
  
  return customFetch<getStores1Response>(getGetStores1Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStores1QueryKey = (params?: GetStores1Params,) => {
    return [
    `/api/admin/stores`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetStores1QueryOptions = <TData = Awaited<ReturnType<typeof getStores1>>, TError = unknown>(params?: GetStores1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStores1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStores1>>> = ({ signal }) => getStores1(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStores1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStores1QueryResult = NonNullable<Awaited<ReturnType<typeof getStores1>>>
export type GetStores1QueryError = unknown


export function useGetStores1<TData = Awaited<ReturnType<typeof getStores1>>, TError = unknown>(
 params: undefined |  GetStores1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStores1>>,
          TError,
          Awaited<ReturnType<typeof getStores1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStores1<TData = Awaited<ReturnType<typeof getStores1>>, TError = unknown>(
 params?: GetStores1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStores1>>,
          TError,
          Awaited<ReturnType<typeof getStores1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStores1<TData = Awaited<ReturnType<typeof getStores1>>, TError = unknown>(
 params?: GetStores1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 상점 목록 페이징 조회
 */

export function useGetStores1<TData = Awaited<ReturnType<typeof getStores1>>, TError = unknown>(
 params?: GetStores1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStores1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 관리자가 새로운 상점을 등록합니다.
 * @summary [관리자] 상점 등록
 */
export type createStore2Response201 = {
  data: CommonResponseLong
  status: 201
}

export type createStore2Response400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type createStore2Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type createStore2Response409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type createStore2ResponseSuccess = (createStore2Response201) & {
  headers: Headers;
};
export type createStore2ResponseError = (createStore2Response400 | createStore2Response403 | createStore2Response409) & {
  headers: Headers;
};

export type createStore2Response = (createStore2ResponseSuccess | createStore2ResponseError)

export const getCreateStore2Url = () => {


  

  return `/api/admin/stores`
}

export const createStore2 = async (storeCreateRequest: StoreCreateRequest, options?: RequestInit): Promise<createStore2Response> => {
  
  return customFetch<createStore2Response>(getCreateStore2Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeCreateRequest,)
  }
);}




export const getCreateStore2MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStore2>>, TError,{data: StoreCreateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createStore2>>, TError,{data: StoreCreateRequest}, TContext> => {

const mutationKey = ['createStore2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStore2>>, {data: StoreCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createStore2(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStore2MutationResult = NonNullable<Awaited<ReturnType<typeof createStore2>>>
    export type CreateStore2MutationBody = StoreCreateRequest
    export type CreateStore2MutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 상점 등록
 */
export const useCreateStore2 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStore2>>, TError,{data: StoreCreateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStore2>>,
        TError,
        {data: StoreCreateRequest},
        TContext
      > => {
      return useMutation(getCreateStore2MutationOptions(options), queryClient);
    }
    /**
 * 상권 데이터를 엑셀로 업로드하여 DB에 저장 및 보정합니다.
 * @summary [관리자] 상점 데이터 엑셀 업로드
 */
export type uploadStoreDataResponse200 = {
  data: CommonResponseString
  status: 200
}

export type uploadStoreDataResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type uploadStoreDataResponse500 = {
  data: SwaggerErrorResponse
  status: 500
}
    
export type uploadStoreDataResponseSuccess = (uploadStoreDataResponse200) & {
  headers: Headers;
};
export type uploadStoreDataResponseError = (uploadStoreDataResponse400 | uploadStoreDataResponse500) & {
  headers: Headers;
};

export type uploadStoreDataResponse = (uploadStoreDataResponseSuccess | uploadStoreDataResponseError)

export const getUploadStoreDataUrl = () => {


  

  return `/api/admin/stores/upload`
}

export const uploadStoreData = async (uploadStoreDataBody: UploadStoreDataBody, options?: RequestInit): Promise<uploadStoreDataResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadStoreDataBody.file);

  return customFetch<uploadStoreDataResponse>(getUploadStoreDataUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadStoreDataMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadStoreData>>, TError,{data: UploadStoreDataBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadStoreData>>, TError,{data: UploadStoreDataBody}, TContext> => {

const mutationKey = ['uploadStoreData'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadStoreData>>, {data: UploadStoreDataBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadStoreData(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadStoreDataMutationResult = NonNullable<Awaited<ReturnType<typeof uploadStoreData>>>
    export type UploadStoreDataMutationBody = UploadStoreDataBody
    export type UploadStoreDataMutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 상점 데이터 엑셀 업로드
 */
export const useUploadStoreData = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadStoreData>>, TError,{data: UploadStoreDataBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadStoreData>>,
        TError,
        {data: UploadStoreDataBody},
        TContext
      > => {
      return useMutation(getUploadStoreDataMutationOptions(options), queryClient);
    }
    /**
 * 상점의 상세 정보를 조회합니다.
 * @summary [관리자] 상점 단건 조회
 */
export type getStore1Response200 = {
  data: CommonResponseAdminStoreResponse
  status: 200
}

export type getStore1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getStore1ResponseSuccess = (getStore1Response200) & {
  headers: Headers;
};
export type getStore1ResponseError = (getStore1Response404) & {
  headers: Headers;
};

export type getStore1Response = (getStore1ResponseSuccess | getStore1ResponseError)

export const getGetStore1Url = (storeId: number,) => {


  

  return `/api/admin/stores/${storeId}`
}

export const getStore1 = async (storeId: number, options?: RequestInit): Promise<getStore1Response> => {
  
  return customFetch<getStore1Response>(getGetStore1Url(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStore1QueryKey = (storeId?: number,) => {
    return [
    `/api/admin/stores/${storeId}`
    ] as const;
    }

    
export const getGetStore1QueryOptions = <TData = Awaited<ReturnType<typeof getStore1>>, TError = SwaggerErrorResponse>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStore1QueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStore1>>> = ({ signal }) => getStore1(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStore1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStore1QueryResult = NonNullable<Awaited<ReturnType<typeof getStore1>>>
export type GetStore1QueryError = SwaggerErrorResponse


export function useGetStore1<TData = Awaited<ReturnType<typeof getStore1>>, TError = SwaggerErrorResponse>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStore1>>,
          TError,
          Awaited<ReturnType<typeof getStore1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStore1<TData = Awaited<ReturnType<typeof getStore1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStore1>>,
          TError,
          Awaited<ReturnType<typeof getStore1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStore1<TData = Awaited<ReturnType<typeof getStore1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 상점 단건 조회
 */

export function useGetStore1<TData = Awaited<ReturnType<typeof getStore1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStore1QueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * UNCLAIMED 상태의 상점을 삭제합니다.
 * @summary [관리자] 상점 삭제
 */
export type deleteStore2Response204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteStore2Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteStore2Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteStore2ResponseSuccess = (deleteStore2Response204) & {
  headers: Headers;
};
export type deleteStore2ResponseError = (deleteStore2Response403 | deleteStore2Response404) & {
  headers: Headers;
};

export type deleteStore2Response = (deleteStore2ResponseSuccess | deleteStore2ResponseError)

export const getDeleteStore2Url = (storeId: number,) => {


  

  return `/api/admin/stores/${storeId}`
}

export const deleteStore2 = async (storeId: number, options?: RequestInit): Promise<deleteStore2Response> => {
  
  return customFetch<deleteStore2Response>(getDeleteStore2Url(storeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteStore2MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStore2>>, TError,{storeId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStore2>>, TError,{storeId: number}, TContext> => {

const mutationKey = ['deleteStore2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStore2>>, {storeId: number}> = (props) => {
          const {storeId} = props ?? {};

          return  deleteStore2(storeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStore2MutationResult = NonNullable<Awaited<ReturnType<typeof deleteStore2>>>
    
    export type DeleteStore2MutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 상점 삭제
 */
export const useDeleteStore2 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStore2>>, TError,{storeId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStore2>>,
        TError,
        {storeId: number},
        TContext
      > => {
      return useMutation(getDeleteStore2MutationOptions(options), queryClient);
    }
    /**
 * 관리자가 상점 정보를 수정합니다. 점유 여부와 관계없이 수정할 수 있습니다.
 * @summary [관리자] 상점 정보 수정
 */
export type updateStore2Response200 = {
  data: CommonResponseVoid
  status: 200
}

export type updateStore2Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updateStore2Response404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type updateStore2Response409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type updateStore2ResponseSuccess = (updateStore2Response200) & {
  headers: Headers;
};
export type updateStore2ResponseError = (updateStore2Response403 | updateStore2Response404 | updateStore2Response409) & {
  headers: Headers;
};

export type updateStore2Response = (updateStore2ResponseSuccess | updateStore2ResponseError)

export const getUpdateStore2Url = (storeId: number,) => {


  

  return `/api/admin/stores/${storeId}`
}

export const updateStore2 = async (storeId: number,
    storeUpdateRequest: StoreUpdateRequest, options?: RequestInit): Promise<updateStore2Response> => {
  
  return customFetch<updateStore2Response>(getUpdateStore2Url(storeId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeUpdateRequest,)
  }
);}




export const getUpdateStore2MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStore2>>, TError,{storeId: number;data: StoreUpdateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStore2>>, TError,{storeId: number;data: StoreUpdateRequest}, TContext> => {

const mutationKey = ['updateStore2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStore2>>, {storeId: number;data: StoreUpdateRequest}> = (props) => {
          const {storeId,data} = props ?? {};

          return  updateStore2(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStore2MutationResult = NonNullable<Awaited<ReturnType<typeof updateStore2>>>
    export type UpdateStore2MutationBody = StoreUpdateRequest
    export type UpdateStore2MutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 상점 정보 수정
 */
export const useUpdateStore2 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStore2>>, TError,{storeId: number;data: StoreUpdateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStore2>>,
        TError,
        {storeId: number;data: StoreUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateStore2MutationOptions(options), queryClient);
    }
    /**
 * 주소를 입력받아 위도, 경도 좌표를 반환합니다.
 * @summary [관리자] 주소로 위경도 변환
 */
export type getGeocodeResponse200 = {
  data: CommonResponseCoordinate
  status: 200
}

export type getGeocodeResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type getGeocodeResponse500 = {
  data: SwaggerErrorResponse
  status: 500
}
    
export type getGeocodeResponseSuccess = (getGeocodeResponse200) & {
  headers: Headers;
};
export type getGeocodeResponseError = (getGeocodeResponse400 | getGeocodeResponse500) & {
  headers: Headers;
};

export type getGeocodeResponse = (getGeocodeResponseSuccess | getGeocodeResponseError)

export const getGetGeocodeUrl = (params: GetGeocodeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/stores/geocode?${stringifiedParams}` : `/api/admin/stores/geocode`
}

export const getGeocode = async (params: GetGeocodeParams, options?: RequestInit): Promise<getGeocodeResponse> => {
  
  return customFetch<getGeocodeResponse>(getGetGeocodeUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGeocodeQueryKey = (params?: GetGeocodeParams,) => {
    return [
    `/api/admin/stores/geocode`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetGeocodeQueryOptions = <TData = Awaited<ReturnType<typeof getGeocode>>, TError = SwaggerErrorResponse>(params: GetGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGeocodeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGeocode>>> = ({ signal }) => getGeocode(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGeocode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGeocodeQueryResult = NonNullable<Awaited<ReturnType<typeof getGeocode>>>
export type GetGeocodeQueryError = SwaggerErrorResponse


export function useGetGeocode<TData = Awaited<ReturnType<typeof getGeocode>>, TError = SwaggerErrorResponse>(
 params: GetGeocodeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeocode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGeocode>>,
          TError,
          Awaited<ReturnType<typeof getGeocode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGeocode<TData = Awaited<ReturnType<typeof getGeocode>>, TError = SwaggerErrorResponse>(
 params: GetGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeocode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGeocode>>,
          TError,
          Awaited<ReturnType<typeof getGeocode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGeocode<TData = Awaited<ReturnType<typeof getGeocode>>, TError = SwaggerErrorResponse>(
 params: GetGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 주소로 위경도 변환
 */

export function useGetGeocode<TData = Awaited<ReturnType<typeof getGeocode>>, TError = SwaggerErrorResponse>(
 params: GetGeocodeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGeocode>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGeocodeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




