/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CommonResponseLong,
  CommonResponseVoid,
  CreateUniversityRequest,
  SwaggerErrorResponse,
  UpdateUniversityRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 새로운 대학을 등록합니다.
 * @summary [관리자] 대학 등록
 */
export type createUniversityResponse201 = {
  data: CommonResponseLong
  status: 201
}

export type createUniversityResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}
    
export type createUniversityResponseSuccess = (createUniversityResponse201) & {
  headers: Headers;
};
export type createUniversityResponseError = (createUniversityResponse403) & {
  headers: Headers;
};

export type createUniversityResponse = (createUniversityResponseSuccess | createUniversityResponseError)

export const getCreateUniversityUrl = () => {


  

  return `/api/admin/universities`
}

export const createUniversity = async (createUniversityRequest: CreateUniversityRequest, options?: RequestInit): Promise<createUniversityResponse> => {
  
  return customFetch<createUniversityResponse>(getCreateUniversityUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUniversityRequest,)
  }
);}




export const getCreateUniversityMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUniversity>>, TError,{data: CreateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createUniversity>>, TError,{data: CreateUniversityRequest}, TContext> => {

const mutationKey = ['createUniversity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUniversity>>, {data: CreateUniversityRequest}> = (props) => {
          const {data} = props ?? {};

          return  createUniversity(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUniversityMutationResult = NonNullable<Awaited<ReturnType<typeof createUniversity>>>
    export type CreateUniversityMutationBody = CreateUniversityRequest
    export type CreateUniversityMutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 대학 등록
 */
export const useCreateUniversity = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUniversity>>, TError,{data: CreateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUniversity>>,
        TError,
        {data: CreateUniversityRequest},
        TContext
      > => {
      return useMutation(getCreateUniversityMutationOptions(options), queryClient);
    }
    /**
 * 대학을 삭제합니다.
 * @summary [관리자] 대학 삭제
 */
export type deleteUniversityResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteUniversityResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type deleteUniversityResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteUniversityResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteUniversityResponseSuccess = (deleteUniversityResponse204) & {
  headers: Headers;
};
export type deleteUniversityResponseError = (deleteUniversityResponse400 | deleteUniversityResponse403 | deleteUniversityResponse404) & {
  headers: Headers;
};

export type deleteUniversityResponse = (deleteUniversityResponseSuccess | deleteUniversityResponseError)

export const getDeleteUniversityUrl = (universityId: number,) => {


  

  return `/api/admin/universities/${universityId}`
}

export const deleteUniversity = async (universityId: number, options?: RequestInit): Promise<deleteUniversityResponse> => {
  
  return customFetch<deleteUniversityResponse>(getDeleteUniversityUrl(universityId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteUniversityMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUniversity>>, TError,{universityId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUniversity>>, TError,{universityId: number}, TContext> => {

const mutationKey = ['deleteUniversity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUniversity>>, {universityId: number}> = (props) => {
          const {universityId} = props ?? {};

          return  deleteUniversity(universityId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUniversityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUniversity>>>
    
    export type DeleteUniversityMutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 대학 삭제
 */
export const useDeleteUniversity = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUniversity>>, TError,{universityId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUniversity>>,
        TError,
        {universityId: number},
        TContext
      > => {
      return useMutation(getDeleteUniversityMutationOptions(options), queryClient);
    }
    /**
 * 대학 정보를 수정합니다.
 * @summary [관리자] 대학 수정
 */
export type updateUniversity2Response200 = {
  data: CommonResponseVoid
  status: 200
}

export type updateUniversity2Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updateUniversity2Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type updateUniversity2ResponseSuccess = (updateUniversity2Response200) & {
  headers: Headers;
};
export type updateUniversity2ResponseError = (updateUniversity2Response403 | updateUniversity2Response404) & {
  headers: Headers;
};

export type updateUniversity2Response = (updateUniversity2ResponseSuccess | updateUniversity2ResponseError)

export const getUpdateUniversity2Url = (universityId: number,) => {


  

  return `/api/admin/universities/${universityId}`
}

export const updateUniversity2 = async (universityId: number,
    updateUniversityRequest: UpdateUniversityRequest, options?: RequestInit): Promise<updateUniversity2Response> => {
  
  return customFetch<updateUniversity2Response>(getUpdateUniversity2Url(universityId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUniversityRequest,)
  }
);}




export const getUpdateUniversity2MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUniversity2>>, TError,{universityId: number;data: UpdateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUniversity2>>, TError,{universityId: number;data: UpdateUniversityRequest}, TContext> => {

const mutationKey = ['updateUniversity2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUniversity2>>, {universityId: number;data: UpdateUniversityRequest}> = (props) => {
          const {universityId,data} = props ?? {};

          return  updateUniversity2(universityId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUniversity2MutationResult = NonNullable<Awaited<ReturnType<typeof updateUniversity2>>>
    export type UpdateUniversity2MutationBody = UpdateUniversityRequest
    export type UpdateUniversity2MutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 대학 수정
 */
export const useUpdateUniversity2 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUniversity2>>, TError,{universityId: number;data: UpdateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUniversity2>>,
        TError,
        {universityId: number;data: UpdateUniversityRequest},
        TContext
      > => {
      return useMutation(getUpdateUniversity2MutationOptions(options), queryClient);
    }
    