/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 현재 노출 중인 팝업 광고 목록을 노출 순서대로 조회합니다.
 * @summary [공통] 팝업 광고 목록 조회
 */
export type getPopupAdvertisementsResponse200 = {
  data: Blob
  status: 200
}
    
export type getPopupAdvertisementsResponseSuccess = (getPopupAdvertisementsResponse200) & {
  headers: Headers;
};
;

export type getPopupAdvertisementsResponse = (getPopupAdvertisementsResponseSuccess)

export const getGetPopupAdvertisementsUrl = () => {


  

  return `/api/advertisements/popup`
}

export const getPopupAdvertisements = async ( options?: RequestInit): Promise<getPopupAdvertisementsResponse> => {
  
  return customFetch<getPopupAdvertisementsResponse>(getGetPopupAdvertisementsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPopupAdvertisementsQueryKey = () => {
    return [
    `/api/advertisements/popup`
    ] as const;
    }

    
export const getGetPopupAdvertisementsQueryOptions = <TData = Awaited<ReturnType<typeof getPopupAdvertisements>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopupAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPopupAdvertisementsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPopupAdvertisements>>> = ({ signal }) => getPopupAdvertisements({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPopupAdvertisements>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPopupAdvertisementsQueryResult = NonNullable<Awaited<ReturnType<typeof getPopupAdvertisements>>>
export type GetPopupAdvertisementsQueryError = unknown


export function useGetPopupAdvertisements<TData = Awaited<ReturnType<typeof getPopupAdvertisements>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopupAdvertisements>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPopupAdvertisements>>,
          TError,
          Awaited<ReturnType<typeof getPopupAdvertisements>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPopupAdvertisements<TData = Awaited<ReturnType<typeof getPopupAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopupAdvertisements>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPopupAdvertisements>>,
          TError,
          Awaited<ReturnType<typeof getPopupAdvertisements>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPopupAdvertisements<TData = Awaited<ReturnType<typeof getPopupAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopupAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 팝업 광고 목록 조회
 */

export function useGetPopupAdvertisements<TData = Awaited<ReturnType<typeof getPopupAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopupAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPopupAdvertisementsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 현재 노출 중인 플로팅 배너 목록을 노출 순서대로 조회합니다.
 * @summary [공통] 플로팅 배너 목록 조회
 */
export type getFloatingAdvertisementsResponse200 = {
  data: Blob
  status: 200
}
    
export type getFloatingAdvertisementsResponseSuccess = (getFloatingAdvertisementsResponse200) & {
  headers: Headers;
};
;

export type getFloatingAdvertisementsResponse = (getFloatingAdvertisementsResponseSuccess)

export const getGetFloatingAdvertisementsUrl = () => {


  

  return `/api/advertisements/floating`
}

export const getFloatingAdvertisements = async ( options?: RequestInit): Promise<getFloatingAdvertisementsResponse> => {
  
  return customFetch<getFloatingAdvertisementsResponse>(getGetFloatingAdvertisementsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetFloatingAdvertisementsQueryKey = () => {
    return [
    `/api/advertisements/floating`
    ] as const;
    }

    
export const getGetFloatingAdvertisementsQueryOptions = <TData = Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFloatingAdvertisementsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFloatingAdvertisements>>> = ({ signal }) => getFloatingAdvertisements({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFloatingAdvertisementsQueryResult = NonNullable<Awaited<ReturnType<typeof getFloatingAdvertisements>>>
export type GetFloatingAdvertisementsQueryError = unknown


export function useGetFloatingAdvertisements<TData = Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFloatingAdvertisements>>,
          TError,
          Awaited<ReturnType<typeof getFloatingAdvertisements>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFloatingAdvertisements<TData = Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFloatingAdvertisements>>,
          TError,
          Awaited<ReturnType<typeof getFloatingAdvertisements>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFloatingAdvertisements<TData = Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 플로팅 배너 목록 조회
 */

export function useGetFloatingAdvertisements<TData = Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFloatingAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFloatingAdvertisementsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 현재 노출 중인 배너 광고 목록을 노출 순서대로 조회합니다.
 * @summary [공통] 배너 광고 목록 조회
 */
export type getBannerAdvertisementsResponse200 = {
  data: Blob
  status: 200
}
    
export type getBannerAdvertisementsResponseSuccess = (getBannerAdvertisementsResponse200) & {
  headers: Headers;
};
;

export type getBannerAdvertisementsResponse = (getBannerAdvertisementsResponseSuccess)

export const getGetBannerAdvertisementsUrl = () => {


  

  return `/api/advertisements/banner`
}

export const getBannerAdvertisements = async ( options?: RequestInit): Promise<getBannerAdvertisementsResponse> => {
  
  return customFetch<getBannerAdvertisementsResponse>(getGetBannerAdvertisementsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetBannerAdvertisementsQueryKey = () => {
    return [
    `/api/advertisements/banner`
    ] as const;
    }

    
export const getGetBannerAdvertisementsQueryOptions = <TData = Awaited<ReturnType<typeof getBannerAdvertisements>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBannerAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBannerAdvertisementsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBannerAdvertisements>>> = ({ signal }) => getBannerAdvertisements({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBannerAdvertisements>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBannerAdvertisementsQueryResult = NonNullable<Awaited<ReturnType<typeof getBannerAdvertisements>>>
export type GetBannerAdvertisementsQueryError = unknown


export function useGetBannerAdvertisements<TData = Awaited<ReturnType<typeof getBannerAdvertisements>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBannerAdvertisements>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBannerAdvertisements>>,
          TError,
          Awaited<ReturnType<typeof getBannerAdvertisements>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBannerAdvertisements<TData = Awaited<ReturnType<typeof getBannerAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBannerAdvertisements>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBannerAdvertisements>>,
          TError,
          Awaited<ReturnType<typeof getBannerAdvertisements>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBannerAdvertisements<TData = Awaited<ReturnType<typeof getBannerAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBannerAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 배너 광고 목록 조회
 */

export function useGetBannerAdvertisements<TData = Awaited<ReturnType<typeof getBannerAdvertisements>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBannerAdvertisements>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBannerAdvertisementsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




