/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppleLoginRequest,
  CheckUsernameAvailabilityParams,
  CompleteSocialSignupParams,
  CompleteSocialSignupRequest,
  CouncilSignupRequest,
  FindPasswordSendCodeRequest,
  GoogleLoginRequest,
  KakaoLoginRequest,
  LoginRequest,
  OwnerSignupRequest,
  ResetPasswordRequest,
  SendEmailCodeRequest,
  StudentSignupRequest,
  VerifyEmailCodeRequest,
  WithdrawRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 학생 회원을 등록합니다.
 * @summary [학생] 학생 회원가입
 */
export type signupStudentResponse200 = {
  data: Blob
  status: 200
}
    
export type signupStudentResponseSuccess = (signupStudentResponse200) & {
  headers: Headers;
};
;

export type signupStudentResponse = (signupStudentResponseSuccess)

export const getSignupStudentUrl = () => {


  

  return `/api/auth/signup/student`
}

export const signupStudent = async (studentSignupRequest: StudentSignupRequest, options?: RequestInit): Promise<signupStudentResponse> => {
  
  return customFetch<signupStudentResponse>(getSignupStudentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      studentSignupRequest,)
  }
);}




export const getSignupStudentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupStudent>>, TError,{data: StudentSignupRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof signupStudent>>, TError,{data: StudentSignupRequest}, TContext> => {

const mutationKey = ['signupStudent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupStudent>>, {data: StudentSignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupStudent(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SignupStudentMutationResult = NonNullable<Awaited<ReturnType<typeof signupStudent>>>
    export type SignupStudentMutationBody = StudentSignupRequest
    export type SignupStudentMutationError = unknown

    /**
 * @summary [학생] 학생 회원가입
 */
export const useSignupStudent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupStudent>>, TError,{data: StudentSignupRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signupStudent>>,
        TError,
        {data: StudentSignupRequest},
        TContext
      > => {
      return useMutation(getSignupStudentMutationOptions(options), queryClient);
    }
    /**
 * 점주 회원을 등록합니다.
 * @summary [점주] 점주 회원가입
 */
export type signupOwnerResponse200 = {
  data: Blob
  status: 200
}
    
export type signupOwnerResponseSuccess = (signupOwnerResponse200) & {
  headers: Headers;
};
;

export type signupOwnerResponse = (signupOwnerResponseSuccess)

export const getSignupOwnerUrl = () => {


  

  return `/api/auth/signup/owner`
}

export const signupOwner = async (ownerSignupRequest: OwnerSignupRequest, options?: RequestInit): Promise<signupOwnerResponse> => {
  
  return customFetch<signupOwnerResponse>(getSignupOwnerUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      ownerSignupRequest,)
  }
);}




export const getSignupOwnerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupOwner>>, TError,{data: OwnerSignupRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof signupOwner>>, TError,{data: OwnerSignupRequest}, TContext> => {

const mutationKey = ['signupOwner'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupOwner>>, {data: OwnerSignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupOwner(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SignupOwnerMutationResult = NonNullable<Awaited<ReturnType<typeof signupOwner>>>
    export type SignupOwnerMutationBody = OwnerSignupRequest
    export type SignupOwnerMutationError = unknown

    /**
 * @summary [점주] 점주 회원가입
 */
export const useSignupOwner = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupOwner>>, TError,{data: OwnerSignupRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signupOwner>>,
        TError,
        {data: OwnerSignupRequest},
        TContext
      > => {
      return useMutation(getSignupOwnerMutationOptions(options), queryClient);
    }
    /**
 * 학생회 회원을 등록합니다.
 * @summary [학생회] 학생회 회원가입
 */
export type signupcouncilResponse200 = {
  data: Blob
  status: 200
}
    
export type signupcouncilResponseSuccess = (signupcouncilResponse200) & {
  headers: Headers;
};
;

export type signupcouncilResponse = (signupcouncilResponseSuccess)

export const getSignupcouncilUrl = () => {


  

  return `/api/auth/signup/council`
}

export const signupcouncil = async (councilSignupRequest: CouncilSignupRequest, options?: RequestInit): Promise<signupcouncilResponse> => {
  
  return customFetch<signupcouncilResponse>(getSignupcouncilUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      councilSignupRequest,)
  }
);}




export const getSignupcouncilMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupcouncil>>, TError,{data: CouncilSignupRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof signupcouncil>>, TError,{data: CouncilSignupRequest}, TContext> => {

const mutationKey = ['signupcouncil'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupcouncil>>, {data: CouncilSignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupcouncil(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SignupcouncilMutationResult = NonNullable<Awaited<ReturnType<typeof signupcouncil>>>
    export type SignupcouncilMutationBody = CouncilSignupRequest
    export type SignupcouncilMutationError = unknown

    /**
 * @summary [학생회] 학생회 회원가입
 */
export const useSignupcouncil = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupcouncil>>, TError,{data: CouncilSignupRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signupcouncil>>,
        TError,
        {data: CouncilSignupRequest},
        TContext
      > => {
      return useMutation(getSignupcouncilMutationOptions(options), queryClient);
    }
    /**
 * RefreshToken으로 AccessToken을 갱신합니다.
 * @summary [공통] 토큰 갱신
 */
export type refreshResponse200 = {
  data: Blob
  status: 200
}

export type refreshResponse401 = {
  data: Blob
  status: 401
}

export type refreshResponse404 = {
  data: Blob
  status: 404
}
    
export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
export type refreshResponseError = (refreshResponse401 | refreshResponse404) & {
  headers: Headers;
};

export type refreshResponse = (refreshResponseSuccess | refreshResponseError)

export const getRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const refresh = async ( options?: RequestInit): Promise<refreshResponse> => {
  
  return customFetch<refreshResponse>(getRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRefreshMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext> => {

const mutationKey = ['refresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refresh>>, void> = () => {
          

          return  refresh(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshMutationResult = NonNullable<Awaited<ReturnType<typeof refresh>>>
    
    export type RefreshMutationError = Blob

    /**
 * @summary [공통] 토큰 갱신
 */
export const useRefresh = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRefreshMutationOptions(options), queryClient);
    }
    /**
 * 사용자를 로그아웃 처리합니다.
 * @summary [공통] 로그아웃
 */
export type logoutResponse200 = {
  data: Blob
  status: 200
}
    
export type logoutResponseSuccess = (logoutResponse200) & {
  headers: Headers;
};
;

export type logoutResponse = (logoutResponseSuccess)

export const getLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<logoutResponse> => {
  
  return customFetch<logoutResponse>(getLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = unknown

    /**
 * @summary [공통] 로그아웃
 */
export const useLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options), queryClient);
    }
    /**
 * 아이디와 비밀번호로 로그인합니다.
 * @summary [공통] 로그인
 */
export type loginResponse200 = {
  data: Blob
  status: 200
}

export type loginResponse400 = {
  data: Blob
  status: 400
}

export type loginResponse401 = {
  data: Blob
  status: 401
}
    
export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse400 | loginResponse401) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {


  

  return `/api/auth/login`
}

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginResponse> => {
  
  return customFetch<loginResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}




export const getLoginMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = Blob

    /**
 * @summary [공통] 로그인
 */
export const useLogin = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
    /**
 * 카카오 인증 후 발급받은 access_token을 통해 로그인/회원가입을 진행합니다.
 * @summary [공통] 카카오 로그인 (네이티브)
 */
export type kakaoLoginResponse200 = {
  data: Blob
  status: 200
}

export type kakaoLoginResponse400 = {
  data: Blob
  status: 400
}

export type kakaoLoginResponse401 = {
  data: Blob
  status: 401
}
    
export type kakaoLoginResponseSuccess = (kakaoLoginResponse200) & {
  headers: Headers;
};
export type kakaoLoginResponseError = (kakaoLoginResponse400 | kakaoLoginResponse401) & {
  headers: Headers;
};

export type kakaoLoginResponse = (kakaoLoginResponseSuccess | kakaoLoginResponseError)

export const getKakaoLoginUrl = () => {


  

  return `/api/auth/kakao/login`
}

export const kakaoLogin = async (kakaoLoginRequest: KakaoLoginRequest, options?: RequestInit): Promise<kakaoLoginResponse> => {
  
  return customFetch<kakaoLoginResponse>(getKakaoLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kakaoLoginRequest,)
  }
);}




export const getKakaoLoginMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof kakaoLogin>>, TError,{data: KakaoLoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof kakaoLogin>>, TError,{data: KakaoLoginRequest}, TContext> => {

const mutationKey = ['kakaoLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof kakaoLogin>>, {data: KakaoLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  kakaoLogin(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type KakaoLoginMutationResult = NonNullable<Awaited<ReturnType<typeof kakaoLogin>>>
    export type KakaoLoginMutationBody = KakaoLoginRequest
    export type KakaoLoginMutationError = Blob

    /**
 * @summary [공통] 카카오 로그인 (네이티브)
 */
export const useKakaoLogin = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof kakaoLogin>>, TError,{data: KakaoLoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof kakaoLogin>>,
        TError,
        {data: KakaoLoginRequest},
        TContext
      > => {
      return useMutation(getKakaoLoginMutationOptions(options), queryClient);
    }
    /**
 * 구글 인증 후 발급받은 id_token을 통해 로그인/회원가입을 진행합니다.
 * @summary [공통] 구글 로그인 (네이티브)
 */
export type googleLoginResponse200 = {
  data: Blob
  status: 200
}

export type googleLoginResponse400 = {
  data: Blob
  status: 400
}

export type googleLoginResponse401 = {
  data: Blob
  status: 401
}
    
export type googleLoginResponseSuccess = (googleLoginResponse200) & {
  headers: Headers;
};
export type googleLoginResponseError = (googleLoginResponse400 | googleLoginResponse401) & {
  headers: Headers;
};

export type googleLoginResponse = (googleLoginResponseSuccess | googleLoginResponseError)

export const getGoogleLoginUrl = () => {


  

  return `/api/auth/google/login`
}

export const googleLogin = async (googleLoginRequest: GoogleLoginRequest, options?: RequestInit): Promise<googleLoginResponse> => {
  
  return customFetch<googleLoginResponse>(getGoogleLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      googleLoginRequest,)
  }
);}




export const getGoogleLoginMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof googleLogin>>, TError,{data: GoogleLoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof googleLogin>>, TError,{data: GoogleLoginRequest}, TContext> => {

const mutationKey = ['googleLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof googleLogin>>, {data: GoogleLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  googleLogin(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GoogleLoginMutationResult = NonNullable<Awaited<ReturnType<typeof googleLogin>>>
    export type GoogleLoginMutationBody = GoogleLoginRequest
    export type GoogleLoginMutationError = Blob

    /**
 * @summary [공통] 구글 로그인 (네이티브)
 */
export const useGoogleLogin = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof googleLogin>>, TError,{data: GoogleLoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof googleLogin>>,
        TError,
        {data: GoogleLoginRequest},
        TContext
      > => {
      return useMutation(getGoogleLoginMutationOptions(options), queryClient);
    }
    /**
 * 인증번호 검증 후 비밀번호 재설정을 위한 임시 토큰을 반환합니다.
 * @summary [공통] 비밀번호 재설정 - 인증 확인 및 임시 토큰 반환
 */
export type verifyCodeForFindPasswordResponse200 = {
  data: Blob
  status: 200
}
    
export type verifyCodeForFindPasswordResponseSuccess = (verifyCodeForFindPasswordResponse200) & {
  headers: Headers;
};
;

export type verifyCodeForFindPasswordResponse = (verifyCodeForFindPasswordResponseSuccess)

export const getVerifyCodeForFindPasswordUrl = () => {


  

  return `/api/auth/find-password/verify`
}

export const verifyCodeForFindPassword = async (verifyEmailCodeRequest: VerifyEmailCodeRequest, options?: RequestInit): Promise<verifyCodeForFindPasswordResponse> => {
  
  return customFetch<verifyCodeForFindPasswordResponse>(getVerifyCodeForFindPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailCodeRequest,)
  }
);}




export const getVerifyCodeForFindPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCodeForFindPassword>>, TError,{data: VerifyEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyCodeForFindPassword>>, TError,{data: VerifyEmailCodeRequest}, TContext> => {

const mutationKey = ['verifyCodeForFindPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyCodeForFindPassword>>, {data: VerifyEmailCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  verifyCodeForFindPassword(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyCodeForFindPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof verifyCodeForFindPassword>>>
    export type VerifyCodeForFindPasswordMutationBody = VerifyEmailCodeRequest
    export type VerifyCodeForFindPasswordMutationError = unknown

    /**
 * @summary [공통] 비밀번호 재설정 - 인증 확인 및 임시 토큰 반환
 */
export const useVerifyCodeForFindPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCodeForFindPassword>>, TError,{data: VerifyEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyCodeForFindPassword>>,
        TError,
        {data: VerifyEmailCodeRequest},
        TContext
      > => {
      return useMutation(getVerifyCodeForFindPasswordMutationOptions(options), queryClient);
    }
    /**
 * 아이디와 이메일이 일치하는지 확인 후 인증번호를 발송합니다.
 * @summary [공통] 비밀번호 찾기 - 인증번호 발송
 */
export type sendCodeForFindPasswordResponse200 = {
  data: Blob
  status: 200
}
    
export type sendCodeForFindPasswordResponseSuccess = (sendCodeForFindPasswordResponse200) & {
  headers: Headers;
};
;

export type sendCodeForFindPasswordResponse = (sendCodeForFindPasswordResponseSuccess)

export const getSendCodeForFindPasswordUrl = () => {


  

  return `/api/auth/find-password/send-code`
}

export const sendCodeForFindPassword = async (findPasswordSendCodeRequest: FindPasswordSendCodeRequest, options?: RequestInit): Promise<sendCodeForFindPasswordResponse> => {
  
  return customFetch<sendCodeForFindPasswordResponse>(getSendCodeForFindPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      findPasswordSendCodeRequest,)
  }
);}




export const getSendCodeForFindPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendCodeForFindPassword>>, TError,{data: FindPasswordSendCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof sendCodeForFindPassword>>, TError,{data: FindPasswordSendCodeRequest}, TContext> => {

const mutationKey = ['sendCodeForFindPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendCodeForFindPassword>>, {data: FindPasswordSendCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  sendCodeForFindPassword(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SendCodeForFindPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof sendCodeForFindPassword>>>
    export type SendCodeForFindPasswordMutationBody = FindPasswordSendCodeRequest
    export type SendCodeForFindPasswordMutationError = unknown

    /**
 * @summary [공통] 비밀번호 찾기 - 인증번호 발송
 */
export const useSendCodeForFindPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendCodeForFindPassword>>, TError,{data: FindPasswordSendCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendCodeForFindPassword>>,
        TError,
        {data: FindPasswordSendCodeRequest},
        TContext
      > => {
      return useMutation(getSendCodeForFindPasswordMutationOptions(options), queryClient);
    }
    /**
 * 비밀번호 재설정 토큰을 사용하여 새 비밀번호로 변경합니다.
 * @summary [공통] 비밀번호 재설정
 */
export type resetPasswordResponse200 = {
  data: Blob
  status: 200
}
    
export type resetPasswordResponseSuccess = (resetPasswordResponse200) & {
  headers: Headers;
};
;

export type resetPasswordResponse = (resetPasswordResponseSuccess)

export const getResetPasswordUrl = () => {


  

  return `/api/auth/find-password/reset`
}

export const resetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: RequestInit): Promise<resetPasswordResponse> => {
  
  return customFetch<resetPasswordResponse>(getResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordRequest,)
  }
);}




export const getResetPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordRequest}, TContext> => {

const mutationKey = ['resetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPassword>>, {data: ResetPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  resetPassword(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
    export type ResetPasswordMutationBody = ResetPasswordRequest
    export type ResetPasswordMutationError = unknown

    /**
 * @summary [공통] 비밀번호 재설정
 */
export const useResetPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetPassword>>,
        TError,
        {data: ResetPasswordRequest},
        TContext
      > => {
      return useMutation(getResetPasswordMutationOptions(options), queryClient);
    }
    /**
 * 인증번호 검증 후 가입된 아이디를 반환합니다.
 * @summary [공통] 아이디 찾기 - 인증 확인 및 아이디 반환
 */
export type verifyCodeForFindIdResponse200 = {
  data: Blob
  status: 200
}
    
export type verifyCodeForFindIdResponseSuccess = (verifyCodeForFindIdResponse200) & {
  headers: Headers;
};
;

export type verifyCodeForFindIdResponse = (verifyCodeForFindIdResponseSuccess)

export const getVerifyCodeForFindIdUrl = () => {


  

  return `/api/auth/find-id/verify`
}

export const verifyCodeForFindId = async (verifyEmailCodeRequest: VerifyEmailCodeRequest, options?: RequestInit): Promise<verifyCodeForFindIdResponse> => {
  
  return customFetch<verifyCodeForFindIdResponse>(getVerifyCodeForFindIdUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailCodeRequest,)
  }
);}




export const getVerifyCodeForFindIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCodeForFindId>>, TError,{data: VerifyEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyCodeForFindId>>, TError,{data: VerifyEmailCodeRequest}, TContext> => {

const mutationKey = ['verifyCodeForFindId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyCodeForFindId>>, {data: VerifyEmailCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  verifyCodeForFindId(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyCodeForFindIdMutationResult = NonNullable<Awaited<ReturnType<typeof verifyCodeForFindId>>>
    export type VerifyCodeForFindIdMutationBody = VerifyEmailCodeRequest
    export type VerifyCodeForFindIdMutationError = unknown

    /**
 * @summary [공통] 아이디 찾기 - 인증 확인 및 아이디 반환
 */
export const useVerifyCodeForFindId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCodeForFindId>>, TError,{data: VerifyEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyCodeForFindId>>,
        TError,
        {data: VerifyEmailCodeRequest},
        TContext
      > => {
      return useMutation(getVerifyCodeForFindIdMutationOptions(options), queryClient);
    }
    /**
 * 가입된 이메일로 인증번호를 발송합니다.
 * @summary [공통] 아이디 찾기 - 인증번호 발송
 */
export type sendCodeForFindIdResponse200 = {
  data: Blob
  status: 200
}
    
export type sendCodeForFindIdResponseSuccess = (sendCodeForFindIdResponse200) & {
  headers: Headers;
};
;

export type sendCodeForFindIdResponse = (sendCodeForFindIdResponseSuccess)

export const getSendCodeForFindIdUrl = () => {


  

  return `/api/auth/find-id/send-code`
}

export const sendCodeForFindId = async (sendEmailCodeRequest: SendEmailCodeRequest, options?: RequestInit): Promise<sendCodeForFindIdResponse> => {
  
  return customFetch<sendCodeForFindIdResponse>(getSendCodeForFindIdUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendEmailCodeRequest,)
  }
);}




export const getSendCodeForFindIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendCodeForFindId>>, TError,{data: SendEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof sendCodeForFindId>>, TError,{data: SendEmailCodeRequest}, TContext> => {

const mutationKey = ['sendCodeForFindId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendCodeForFindId>>, {data: SendEmailCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  sendCodeForFindId(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SendCodeForFindIdMutationResult = NonNullable<Awaited<ReturnType<typeof sendCodeForFindId>>>
    export type SendCodeForFindIdMutationBody = SendEmailCodeRequest
    export type SendCodeForFindIdMutationError = unknown

    /**
 * @summary [공통] 아이디 찾기 - 인증번호 발송
 */
export const useSendCodeForFindId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendCodeForFindId>>, TError,{data: SendEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendCodeForFindId>>,
        TError,
        {data: SendEmailCodeRequest},
        TContext
      > => {
      return useMutation(getSendCodeForFindIdMutationOptions(options), queryClient);
    }
    /**
 * 회원 가입용 이메일 인증 코드를 검증합니다. (true: 검증 (일치) 완료, false: 검증 실패 (코드 불일치 및 이미 등록된 이메일)
 * @summary [공통] 회원 가입용 이메일 인증 확인
 */
export type verifyResponse200 = {
  data: Blob
  status: 200
}
    
export type verifyResponseSuccess = (verifyResponse200) & {
  headers: Headers;
};
;

export type verifyResponse = (verifyResponseSuccess)

export const getVerifyUrl = () => {


  

  return `/api/auth/email/verify`
}

export const verify = async (verifyEmailCodeRequest: VerifyEmailCodeRequest, options?: RequestInit): Promise<verifyResponse> => {
  
  return customFetch<verifyResponse>(getVerifyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailCodeRequest,)
  }
);}




export const getVerifyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verify>>, TError,{data: VerifyEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof verify>>, TError,{data: VerifyEmailCodeRequest}, TContext> => {

const mutationKey = ['verify'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verify>>, {data: VerifyEmailCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  verify(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyMutationResult = NonNullable<Awaited<ReturnType<typeof verify>>>
    export type VerifyMutationBody = VerifyEmailCodeRequest
    export type VerifyMutationError = unknown

    /**
 * @summary [공통] 회원 가입용 이메일 인증 확인
 */
export const useVerify = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verify>>, TError,{data: VerifyEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verify>>,
        TError,
        {data: VerifyEmailCodeRequest},
        TContext
      > => {
      return useMutation(getVerifyMutationOptions(options), queryClient);
    }
    /**
 * 회원 가입용 이메일 인증 코드를 전송합니다. (universityId 존재 시 도메인 검사 진행)
 * @summary [공통] 회원 가입용 이메일 인증 발송
 */
export type sendResponse200 = {
  data: Blob
  status: 200
}
    
export type sendResponseSuccess = (sendResponse200) & {
  headers: Headers;
};
;

export type sendResponse = (sendResponseSuccess)

export const getSendUrl = () => {


  

  return `/api/auth/email/send-code`
}

export const send = async (sendEmailCodeRequest: SendEmailCodeRequest, options?: RequestInit): Promise<sendResponse> => {
  
  return customFetch<sendResponse>(getSendUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendEmailCodeRequest,)
  }
);}




export const getSendMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof send>>, TError,{data: SendEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof send>>, TError,{data: SendEmailCodeRequest}, TContext> => {

const mutationKey = ['send'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof send>>, {data: SendEmailCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  send(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SendMutationResult = NonNullable<Awaited<ReturnType<typeof send>>>
    export type SendMutationBody = SendEmailCodeRequest
    export type SendMutationError = unknown

    /**
 * @summary [공통] 회원 가입용 이메일 인증 발송
 */
export const useSend = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof send>>, TError,{data: SendEmailCodeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof send>>,
        TError,
        {data: SendEmailCodeRequest},
        TContext
      > => {
      return useMutation(getSendMutationOptions(options), queryClient);
    }
    /**
 * 소셜 로그인 후 추가 정보를 입력하여 회원가입을 완료합니다.
 * @summary [공통] 소셜 회원가입 완료
 */
export type completeSocialSignupResponse200 = {
  data: Blob
  status: 200
}

export type completeSocialSignupResponse400 = {
  data: Blob
  status: 400
}

export type completeSocialSignupResponse404 = {
  data: Blob
  status: 404
}

export type completeSocialSignupResponse409 = {
  data: Blob
  status: 409
}
    
export type completeSocialSignupResponseSuccess = (completeSocialSignupResponse200) & {
  headers: Headers;
};
export type completeSocialSignupResponseError = (completeSocialSignupResponse400 | completeSocialSignupResponse404 | completeSocialSignupResponse409) & {
  headers: Headers;
};

export type completeSocialSignupResponse = (completeSocialSignupResponseSuccess | completeSocialSignupResponseError)

export const getCompleteSocialSignupUrl = (params: CompleteSocialSignupParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/complete-social-signup?${stringifiedParams}` : `/api/auth/complete-social-signup`
}

export const completeSocialSignup = async (completeSocialSignupRequest: CompleteSocialSignupRequest,
    params: CompleteSocialSignupParams, options?: RequestInit): Promise<completeSocialSignupResponse> => {
  
  return customFetch<completeSocialSignupResponse>(getCompleteSocialSignupUrl(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      completeSocialSignupRequest,)
  }
);}




export const getCompleteSocialSignupMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSocialSignup>>, TError,{data: CompleteSocialSignupRequest;params: CompleteSocialSignupParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completeSocialSignup>>, TError,{data: CompleteSocialSignupRequest;params: CompleteSocialSignupParams}, TContext> => {

const mutationKey = ['completeSocialSignup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeSocialSignup>>, {data: CompleteSocialSignupRequest;params: CompleteSocialSignupParams}> = (props) => {
          const {data,params} = props ?? {};

          return  completeSocialSignup(data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteSocialSignupMutationResult = NonNullable<Awaited<ReturnType<typeof completeSocialSignup>>>
    export type CompleteSocialSignupMutationBody = CompleteSocialSignupRequest
    export type CompleteSocialSignupMutationError = Blob

    /**
 * @summary [공통] 소셜 회원가입 완료
 */
export const useCompleteSocialSignup = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeSocialSignup>>, TError,{data: CompleteSocialSignupRequest;params: CompleteSocialSignupParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeSocialSignup>>,
        TError,
        {data: CompleteSocialSignupRequest;params: CompleteSocialSignupParams},
        TContext
      > => {
      return useMutation(getCompleteSocialSignupMutationOptions(options), queryClient);
    }
    /**
 * 애플 인증 후 발급받은 id_token을 통해 로그인/회원가입을 진행합니다.
 * @summary [공통] 애플 로그인 (네이티브)
 */
export type appleLoginResponse200 = {
  data: Blob
  status: 200
}

export type appleLoginResponse400 = {
  data: Blob
  status: 400
}

export type appleLoginResponse401 = {
  data: Blob
  status: 401
}
    
export type appleLoginResponseSuccess = (appleLoginResponse200) & {
  headers: Headers;
};
export type appleLoginResponseError = (appleLoginResponse400 | appleLoginResponse401) & {
  headers: Headers;
};

export type appleLoginResponse = (appleLoginResponseSuccess | appleLoginResponseError)

export const getAppleLoginUrl = () => {


  

  return `/api/auth/apple/login`
}

export const appleLogin = async (appleLoginRequest: AppleLoginRequest, options?: RequestInit): Promise<appleLoginResponse> => {
  
  return customFetch<appleLoginResponse>(getAppleLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      appleLoginRequest,)
  }
);}




export const getAppleLoginMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appleLogin>>, TError,{data: AppleLoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof appleLogin>>, TError,{data: AppleLoginRequest}, TContext> => {

const mutationKey = ['appleLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof appleLogin>>, {data: AppleLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  appleLogin(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AppleLoginMutationResult = NonNullable<Awaited<ReturnType<typeof appleLogin>>>
    export type AppleLoginMutationBody = AppleLoginRequest
    export type AppleLoginMutationError = Blob

    /**
 * @summary [공통] 애플 로그인 (네이티브)
 */
export const useAppleLogin = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appleLogin>>, TError,{data: AppleLoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof appleLogin>>,
        TError,
        {data: AppleLoginRequest},
        TContext
      > => {
      return useMutation(getAppleLoginMutationOptions(options), queryClient);
    }
    /**
 * 아이디 사용 가능 여부를 확인합니다. (true: 사용 가능, false: 중복)
 * @summary [공통] 아이디 중복 확인
 */
export type checkUsernameAvailabilityResponse200 = {
  data: Blob
  status: 200
}
    
export type checkUsernameAvailabilityResponseSuccess = (checkUsernameAvailabilityResponse200) & {
  headers: Headers;
};
;

export type checkUsernameAvailabilityResponse = (checkUsernameAvailabilityResponseSuccess)

export const getCheckUsernameAvailabilityUrl = (params: CheckUsernameAvailabilityParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/check-username?${stringifiedParams}` : `/api/auth/check-username`
}

export const checkUsernameAvailability = async (params: CheckUsernameAvailabilityParams, options?: RequestInit): Promise<checkUsernameAvailabilityResponse> => {
  
  return customFetch<checkUsernameAvailabilityResponse>(getCheckUsernameAvailabilityUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCheckUsernameAvailabilityQueryKey = (params?: CheckUsernameAvailabilityParams,) => {
    return [
    `/api/auth/check-username`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getCheckUsernameAvailabilityQueryOptions = <TData = Awaited<ReturnType<typeof checkUsernameAvailability>>, TError = unknown>(params: CheckUsernameAvailabilityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkUsernameAvailability>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckUsernameAvailabilityQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkUsernameAvailability>>> = ({ signal }) => checkUsernameAvailability(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkUsernameAvailability>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckUsernameAvailabilityQueryResult = NonNullable<Awaited<ReturnType<typeof checkUsernameAvailability>>>
export type CheckUsernameAvailabilityQueryError = unknown


export function useCheckUsernameAvailability<TData = Awaited<ReturnType<typeof checkUsernameAvailability>>, TError = unknown>(
 params: CheckUsernameAvailabilityParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkUsernameAvailability>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkUsernameAvailability>>,
          TError,
          Awaited<ReturnType<typeof checkUsernameAvailability>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckUsernameAvailability<TData = Awaited<ReturnType<typeof checkUsernameAvailability>>, TError = unknown>(
 params: CheckUsernameAvailabilityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkUsernameAvailability>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkUsernameAvailability>>,
          TError,
          Awaited<ReturnType<typeof checkUsernameAvailability>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckUsernameAvailability<TData = Awaited<ReturnType<typeof checkUsernameAvailability>>, TError = unknown>(
 params: CheckUsernameAvailabilityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkUsernameAvailability>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 아이디 중복 확인
 */

export function useCheckUsernameAvailability<TData = Awaited<ReturnType<typeof checkUsernameAvailability>>, TError = unknown>(
 params: CheckUsernameAvailabilityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkUsernameAvailability>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckUsernameAvailabilityQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 회원을 탈퇴 처리합니다. (Soft Delete)
 * @summary [공통] 회원 탈퇴
 */
export type withdrawResponse204 = {
  data: Blob
  status: 204
}

export type withdrawResponse400 = {
  data: Blob
  status: 400
}

export type withdrawResponse401 = {
  data: Blob
  status: 401
}
    
export type withdrawResponseSuccess = (withdrawResponse204) & {
  headers: Headers;
};
export type withdrawResponseError = (withdrawResponse400 | withdrawResponse401) & {
  headers: Headers;
};

export type withdrawResponse = (withdrawResponseSuccess | withdrawResponseError)

export const getWithdrawUrl = () => {


  

  return `/api/auth/withdraw`
}

export const withdraw = async (withdrawRequest: WithdrawRequest, options?: RequestInit): Promise<withdrawResponse> => {
  
  return customFetch<withdrawResponse>(getWithdrawUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      withdrawRequest,)
  }
);}




export const getWithdrawMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,{data: WithdrawRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,{data: WithdrawRequest}, TContext> => {

const mutationKey = ['withdraw'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof withdraw>>, {data: WithdrawRequest}> = (props) => {
          const {data} = props ?? {};

          return  withdraw(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type WithdrawMutationResult = NonNullable<Awaited<ReturnType<typeof withdraw>>>
    export type WithdrawMutationBody = WithdrawRequest
    export type WithdrawMutationError = Blob

    /**
 * @summary [공통] 회원 탈퇴
 */
export const useWithdraw = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdraw>>, TError,{data: WithdrawRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof withdraw>>,
        TError,
        {data: WithdrawRequest},
        TContext
      > => {
      return useMutation(getWithdrawMutationOptions(options), queryClient);
    }
    