/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseInquiryResponse,
  CommonResponseLong,
  CommonResponsePageInquiryResponse,
  CreateInquiryRequest,
  GetInquiriesParams,
  SwaggerErrorResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 내가 작성한 문의 목록을 조회합니다.
 * @summary 내 문의 목록 조회
 */
export type getInquiriesResponse200 = {
  data: CommonResponsePageInquiryResponse
  status: 200
}
    
export type getInquiriesResponseSuccess = (getInquiriesResponse200) & {
  headers: Headers;
};
;

export type getInquiriesResponse = (getInquiriesResponseSuccess)

export const getGetInquiriesUrl = (params: GetInquiriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/inquiries?${stringifiedParams}` : `/api/inquiries`
}

export const getInquiries = async (params: GetInquiriesParams, options?: RequestInit): Promise<getInquiriesResponse> => {
  
  return customFetch<getInquiriesResponse>(getGetInquiriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetInquiriesQueryKey = (params?: GetInquiriesParams,) => {
    return [
    `/api/inquiries`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetInquiriesQueryOptions = <TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(params: GetInquiriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInquiriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInquiries>>> = ({ signal }) => getInquiries(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInquiriesQueryResult = NonNullable<Awaited<ReturnType<typeof getInquiries>>>
export type GetInquiriesQueryError = unknown


export function useGetInquiries<TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(
 params: GetInquiriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInquiries>>,
          TError,
          Awaited<ReturnType<typeof getInquiries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInquiries<TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(
 params: GetInquiriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInquiries>>,
          TError,
          Awaited<ReturnType<typeof getInquiries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInquiries<TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(
 params: GetInquiriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 문의 목록 조회
 */

export function useGetInquiries<TData = Awaited<ReturnType<typeof getInquiries>>, TError = unknown>(
 params: GetInquiriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInquiriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 고객센터에 문의를 등록합니다.
 * @summary 문의하기
 */
export type createInquiryResponse200 = {
  data: CommonResponseLong
  status: 200
}

export type createInquiryResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}
    
export type createInquiryResponseSuccess = (createInquiryResponse200) & {
  headers: Headers;
};
export type createInquiryResponseError = (createInquiryResponse400) & {
  headers: Headers;
};

export type createInquiryResponse = (createInquiryResponseSuccess | createInquiryResponseError)

export const getCreateInquiryUrl = () => {


  

  return `/api/inquiries`
}

export const createInquiry = async (createInquiryRequest: CreateInquiryRequest, options?: RequestInit): Promise<createInquiryResponse> => {
  
  return customFetch<createInquiryResponse>(getCreateInquiryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInquiryRequest,)
  }
);}




export const getCreateInquiryMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInquiry>>, TError,{data: CreateInquiryRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createInquiry>>, TError,{data: CreateInquiryRequest}, TContext> => {

const mutationKey = ['createInquiry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInquiry>>, {data: CreateInquiryRequest}> = (props) => {
          const {data} = props ?? {};

          return  createInquiry(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateInquiryMutationResult = NonNullable<Awaited<ReturnType<typeof createInquiry>>>
    export type CreateInquiryMutationBody = CreateInquiryRequest
    export type CreateInquiryMutationError = SwaggerErrorResponse

    /**
 * @summary 문의하기
 */
export const useCreateInquiry = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInquiry>>, TError,{data: CreateInquiryRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createInquiry>>,
        TError,
        {data: CreateInquiryRequest},
        TContext
      > => {
      return useMutation(getCreateInquiryMutationOptions(options), queryClient);
    }
    /**
 * 문의 상세 내용을 조회합니다.
 * @summary 문의 상세 조회
 */
export type getInquiryResponse200 = {
  data: CommonResponseInquiryResponse
  status: 200
}

export type getInquiryResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type getInquiryResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getInquiryResponseSuccess = (getInquiryResponse200) & {
  headers: Headers;
};
export type getInquiryResponseError = (getInquiryResponse403 | getInquiryResponse404) & {
  headers: Headers;
};

export type getInquiryResponse = (getInquiryResponseSuccess | getInquiryResponseError)

export const getGetInquiryUrl = (inquiryId: number,) => {


  

  return `/api/inquiries/${inquiryId}`
}

export const getInquiry = async (inquiryId: number, options?: RequestInit): Promise<getInquiryResponse> => {
  
  return customFetch<getInquiryResponse>(getGetInquiryUrl(inquiryId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetInquiryQueryKey = (inquiryId?: number,) => {
    return [
    `/api/inquiries/${inquiryId}`
    ] as const;
    }

    
export const getGetInquiryQueryOptions = <TData = Awaited<ReturnType<typeof getInquiry>>, TError = SwaggerErrorResponse>(inquiryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInquiryQueryKey(inquiryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInquiry>>> = ({ signal }) => getInquiry(inquiryId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(inquiryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInquiryQueryResult = NonNullable<Awaited<ReturnType<typeof getInquiry>>>
export type GetInquiryQueryError = SwaggerErrorResponse


export function useGetInquiry<TData = Awaited<ReturnType<typeof getInquiry>>, TError = SwaggerErrorResponse>(
 inquiryId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInquiry>>,
          TError,
          Awaited<ReturnType<typeof getInquiry>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInquiry<TData = Awaited<ReturnType<typeof getInquiry>>, TError = SwaggerErrorResponse>(
 inquiryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInquiry>>,
          TError,
          Awaited<ReturnType<typeof getInquiry>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInquiry<TData = Awaited<ReturnType<typeof getInquiry>>, TError = SwaggerErrorResponse>(
 inquiryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 문의 상세 조회
 */

export function useGetInquiry<TData = Awaited<ReturnType<typeof getInquiry>>, TError = SwaggerErrorResponse>(
 inquiryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInquiry>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInquiryQueryOptions(inquiryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




