/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponsePageResponseStudentEventResponse,
  CommonResponseStudentEventResponse,
  GetEvents2Params,
  SwaggerErrorResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 이벤트 목록을 페이징 조회합니다.
 * @deprecated
 * @summary [공통] 이벤트 목록 조회
 */
export type getEvents2Response200 = {
  data: CommonResponsePageResponseStudentEventResponse
  status: 200
}
    
export type getEvents2ResponseSuccess = (getEvents2Response200) & {
  headers: Headers;
};
;

export type getEvents2Response = (getEvents2ResponseSuccess)

export const getGetEvents2Url = (params: GetEvents2Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/events?${stringifiedParams}` : `/api/events`
}

export const getEvents2 = async (params: GetEvents2Params, options?: RequestInit): Promise<getEvents2Response> => {
  
  return customFetch<getEvents2Response>(getGetEvents2Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEvents2QueryKey = (params?: GetEvents2Params,) => {
    return [
    `/api/events`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetEvents2QueryOptions = <TData = Awaited<ReturnType<typeof getEvents2>>, TError = unknown>(params: GetEvents2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEvents2QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEvents2>>> = ({ signal }) => getEvents2(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEvents2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEvents2QueryResult = NonNullable<Awaited<ReturnType<typeof getEvents2>>>
export type GetEvents2QueryError = unknown


export function useGetEvents2<TData = Awaited<ReturnType<typeof getEvents2>>, TError = unknown>(
 params: GetEvents2Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvents2>>,
          TError,
          Awaited<ReturnType<typeof getEvents2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvents2<TData = Awaited<ReturnType<typeof getEvents2>>, TError = unknown>(
 params: GetEvents2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvents2>>,
          TError,
          Awaited<ReturnType<typeof getEvents2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvents2<TData = Awaited<ReturnType<typeof getEvents2>>, TError = unknown>(
 params: GetEvents2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary [공통] 이벤트 목록 조회
 */

export function useGetEvents2<TData = Awaited<ReturnType<typeof getEvents2>>, TError = unknown>(
 params: GetEvents2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEvents2QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 이벤트 ID로 상세 정보를 조회합니다.
 * @deprecated
 * @summary [공통] 이벤트 단건 조회
 */
export type getEvent2Response200 = {
  data: CommonResponseStudentEventResponse
  status: 200
}

export type getEvent2Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getEvent2ResponseSuccess = (getEvent2Response200) & {
  headers: Headers;
};
export type getEvent2ResponseError = (getEvent2Response404) & {
  headers: Headers;
};

export type getEvent2Response = (getEvent2ResponseSuccess | getEvent2ResponseError)

export const getGetEvent2Url = (eventId: number,) => {


  

  return `/api/events/${eventId}`
}

export const getEvent2 = async (eventId: number, options?: RequestInit): Promise<getEvent2Response> => {
  
  return customFetch<getEvent2Response>(getGetEvent2Url(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEvent2QueryKey = (eventId?: number,) => {
    return [
    `/api/events/${eventId}`
    ] as const;
    }

    
export const getGetEvent2QueryOptions = <TData = Awaited<ReturnType<typeof getEvent2>>, TError = SwaggerErrorResponse>(eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEvent2QueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEvent2>>> = ({ signal }) => getEvent2(eventId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEvent2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEvent2QueryResult = NonNullable<Awaited<ReturnType<typeof getEvent2>>>
export type GetEvent2QueryError = SwaggerErrorResponse


export function useGetEvent2<TData = Awaited<ReturnType<typeof getEvent2>>, TError = SwaggerErrorResponse>(
 eventId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvent2>>,
          TError,
          Awaited<ReturnType<typeof getEvent2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvent2<TData = Awaited<ReturnType<typeof getEvent2>>, TError = SwaggerErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvent2>>,
          TError,
          Awaited<ReturnType<typeof getEvent2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvent2<TData = Awaited<ReturnType<typeof getEvent2>>, TError = SwaggerErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary [공통] 이벤트 단건 조회
 */

export function useGetEvent2<TData = Awaited<ReturnType<typeof getEvent2>>, TError = SwaggerErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvent2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEvent2QueryOptions(eventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




