/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseLong,
  CommonResponsePageResponseStudentFavoriteStoreResponse,
  CommonResponseVoid,
  GetMyFavorites1Params,
  SwaggerErrorResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 특정 상점을 단골 상점으로 등록합니다.
 * @deprecated
 * @summary [학생] 상점 즐겨찾기 추가
 */
export type addFavorite1Response201 = {
  data: CommonResponseVoid
  status: 201
}

export type addFavorite1Response400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type addFavorite1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type addFavorite1Response409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type addFavorite1ResponseSuccess = (addFavorite1Response201) & {
  headers: Headers;
};
export type addFavorite1ResponseError = (addFavorite1Response400 | addFavorite1Response404 | addFavorite1Response409) & {
  headers: Headers;
};

export type addFavorite1Response = (addFavorite1ResponseSuccess | addFavorite1ResponseError)

export const getAddFavorite1Url = (storeId: number,) => {


  

  return `/api/stores/${storeId}/favorites`
}

export const addFavorite1 = async (storeId: number, options?: RequestInit): Promise<addFavorite1Response> => {
  
  return customFetch<addFavorite1Response>(getAddFavorite1Url(storeId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getAddFavorite1MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addFavorite1>>, TError,{storeId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addFavorite1>>, TError,{storeId: number}, TContext> => {

const mutationKey = ['addFavorite1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addFavorite1>>, {storeId: number}> = (props) => {
          const {storeId} = props ?? {};

          return  addFavorite1(storeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddFavorite1MutationResult = NonNullable<Awaited<ReturnType<typeof addFavorite1>>>
    
    export type AddFavorite1MutationError = SwaggerErrorResponse

    /**
 * @deprecated
 * @summary [학생] 상점 즐겨찾기 추가
 */
export const useAddFavorite1 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addFavorite1>>, TError,{storeId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addFavorite1>>,
        TError,
        {storeId: number},
        TContext
      > => {
      return useMutation(getAddFavorite1MutationOptions(options), queryClient);
    }
    /**
 * 단골 상점 등록을 취소합니다.
 * @deprecated
 * @summary [학생] 상점 즐겨찾기 취소
 */
export type removeFavorite1Response204 = {
  data: CommonResponseVoid
  status: 204
}

export type removeFavorite1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type removeFavorite1ResponseSuccess = (removeFavorite1Response204) & {
  headers: Headers;
};
export type removeFavorite1ResponseError = (removeFavorite1Response404) & {
  headers: Headers;
};

export type removeFavorite1Response = (removeFavorite1ResponseSuccess | removeFavorite1ResponseError)

export const getRemoveFavorite1Url = (storeId: number,) => {


  

  return `/api/stores/${storeId}/favorites`
}

export const removeFavorite1 = async (storeId: number, options?: RequestInit): Promise<removeFavorite1Response> => {
  
  return customFetch<removeFavorite1Response>(getRemoveFavorite1Url(storeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getRemoveFavorite1MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFavorite1>>, TError,{storeId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeFavorite1>>, TError,{storeId: number}, TContext> => {

const mutationKey = ['removeFavorite1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeFavorite1>>, {storeId: number}> = (props) => {
          const {storeId} = props ?? {};

          return  removeFavorite1(storeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveFavorite1MutationResult = NonNullable<Awaited<ReturnType<typeof removeFavorite1>>>
    
    export type RemoveFavorite1MutationError = SwaggerErrorResponse

    /**
 * @deprecated
 * @summary [학생] 상점 즐겨찾기 취소
 */
export const useRemoveFavorite1 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFavorite1>>, TError,{storeId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeFavorite1>>,
        TError,
        {storeId: number},
        TContext
      > => {
      return useMutation(getRemoveFavorite1MutationOptions(options), queryClient);
    }
    /**
 * 특정 상점의 총 단골 수를 조회합니다.
 * @deprecated
 * @summary [공통] 상점 즐겨찾기 수 조회
 */
export type countFavorites1Response200 = {
  data: CommonResponseLong
  status: 200
}

export type countFavorites1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type countFavorites1ResponseSuccess = (countFavorites1Response200) & {
  headers: Headers;
};
export type countFavorites1ResponseError = (countFavorites1Response404) & {
  headers: Headers;
};

export type countFavorites1Response = (countFavorites1ResponseSuccess | countFavorites1ResponseError)

export const getCountFavorites1Url = (storeId: number,) => {


  

  return `/api/stores/${storeId}/favorites/count`
}

export const countFavorites1 = async (storeId: number, options?: RequestInit): Promise<countFavorites1Response> => {
  
  return customFetch<countFavorites1Response>(getCountFavorites1Url(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCountFavorites1QueryKey = (storeId?: number,) => {
    return [
    `/api/stores/${storeId}/favorites/count`
    ] as const;
    }

    
export const getCountFavorites1QueryOptions = <TData = Awaited<ReturnType<typeof countFavorites1>>, TError = SwaggerErrorResponse>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFavorites1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCountFavorites1QueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof countFavorites1>>> = ({ signal }) => countFavorites1(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof countFavorites1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CountFavorites1QueryResult = NonNullable<Awaited<ReturnType<typeof countFavorites1>>>
export type CountFavorites1QueryError = SwaggerErrorResponse


export function useCountFavorites1<TData = Awaited<ReturnType<typeof countFavorites1>>, TError = SwaggerErrorResponse>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFavorites1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof countFavorites1>>,
          TError,
          Awaited<ReturnType<typeof countFavorites1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCountFavorites1<TData = Awaited<ReturnType<typeof countFavorites1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFavorites1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof countFavorites1>>,
          TError,
          Awaited<ReturnType<typeof countFavorites1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCountFavorites1<TData = Awaited<ReturnType<typeof countFavorites1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFavorites1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary [공통] 상점 즐겨찾기 수 조회
 */

export function useCountFavorites1<TData = Awaited<ReturnType<typeof countFavorites1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof countFavorites1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCountFavorites1QueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 내가 등록한 단골 상점 목록을 페이징하여 조회합니다.<br>정렬 기능: 찜한최신순(sort=createdAt,desc), 별점높은순(sort=store.averageRating,desc)
 * @deprecated
 * @summary [학생] 내 단골 상점 목록 조회
 */
export type getMyFavorites1Response200 = {
  data: CommonResponsePageResponseStudentFavoriteStoreResponse
  status: 200
}
    
export type getMyFavorites1ResponseSuccess = (getMyFavorites1Response200) & {
  headers: Headers;
};
;

export type getMyFavorites1Response = (getMyFavorites1ResponseSuccess)

export const getGetMyFavorites1Url = (params: GetMyFavorites1Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/favorites?${stringifiedParams}` : `/api/favorites`
}

export const getMyFavorites1 = async (params: GetMyFavorites1Params, options?: RequestInit): Promise<getMyFavorites1Response> => {
  
  return customFetch<getMyFavorites1Response>(getGetMyFavorites1Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyFavorites1QueryKey = (params?: GetMyFavorites1Params,) => {
    return [
    `/api/favorites`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMyFavorites1QueryOptions = <TData = Awaited<ReturnType<typeof getMyFavorites1>>, TError = unknown>(params: GetMyFavorites1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFavorites1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyFavorites1QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyFavorites1>>> = ({ signal }) => getMyFavorites1(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyFavorites1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyFavorites1QueryResult = NonNullable<Awaited<ReturnType<typeof getMyFavorites1>>>
export type GetMyFavorites1QueryError = unknown


export function useGetMyFavorites1<TData = Awaited<ReturnType<typeof getMyFavorites1>>, TError = unknown>(
 params: GetMyFavorites1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFavorites1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyFavorites1>>,
          TError,
          Awaited<ReturnType<typeof getMyFavorites1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyFavorites1<TData = Awaited<ReturnType<typeof getMyFavorites1>>, TError = unknown>(
 params: GetMyFavorites1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFavorites1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyFavorites1>>,
          TError,
          Awaited<ReturnType<typeof getMyFavorites1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyFavorites1<TData = Awaited<ReturnType<typeof getMyFavorites1>>, TError = unknown>(
 params: GetMyFavorites1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFavorites1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary [학생] 내 단골 상점 목록 조회
 */

export function useGetMyFavorites1<TData = Awaited<ReturnType<typeof getMyFavorites1>>, TError = unknown>(
 params: GetMyFavorites1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyFavorites1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyFavorites1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




