/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
export interface UpdateStudentProfileRequest {
  nickname?: string;
  collegeId?: number;
  departmentId?: number;
  isClubMember?: boolean;
}

export interface ErrorDetail {
  field?: string;
  value?: string;
  reason?: string;
}

export interface ErrorResponse {
  timestamp?: string;
  path?: string;
  code?: string;
  message?: string;
  details?: ErrorDetail[];
}

/**
 * 공통 에러 응답
 */
export interface SwaggerErrorResponse {
  /** 성공 여부 */
  isSuccess?: boolean;
  data?: ErrorResponse;
}

export type CommonResponseVoidData = { [key: string]: unknown };

export interface CommonResponseVoid {
  isSuccess?: boolean;
  data?: CommonResponseVoidData;
}

export interface CreateReviewRequest {
  content: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating?: number;
  parentReviewId?: number;
  imageUrls?: string[];
}

export interface CommonResponseLong {
  isSuccess?: boolean;
  data?: number;
}

export type StoreReportRequestReasonsItem = typeof StoreReportRequestReasonsItem[keyof typeof StoreReportRequestReasonsItem];


export const StoreReportRequestReasonsItem = {
  BENEFIT_REFUSAL: 'BENEFIT_REFUSAL',
  BENEFIT_MISMATCH: 'BENEFIT_MISMATCH',
  EVENT_NOT_HELD: 'EVENT_NOT_HELD',
  CLOSED_OR_MOVED: 'CLOSED_OR_MOVED',
  INFO_ERROR: 'INFO_ERROR',
  LOCATION_MISMATCH: 'LOCATION_MISMATCH',
  ETC: 'ETC',
} as const;

export interface StoreReportRequest {
  reasons: StoreReportRequestReasonsItem[];
  detail?: string;
}

/**
 * 소식 댓글 생성 요청
 */
export interface CreateStoreNewsCommentRequest {
  /**
   * 댓글 내용
   * @minLength 1
   * @maxLength 500
   */
  content: string;
}

export type ReportRequestReason = typeof ReportRequestReason[keyof typeof ReportRequestReason];


export const ReportRequestReason = {
  MALICIOUS_SLANDER: 'MALICIOUS_SLANDER',
  INAPPROPRIATE_CONTENT: 'INAPPROPRIATE_CONTENT',
  RIGHTS_VIOLATION: 'RIGHTS_VIOLATION',
  PRIVACY_INFRINGEMENT: 'PRIVACY_INFRINGEMENT',
  COMMERCIAL_PROMOTION: 'COMMERCIAL_PROMOTION',
  FRAUDULENT_REVIEW: 'FRAUDULENT_REVIEW',
  IRRELEVANT: 'IRRELEVANT',
  OTHER: 'OTHER',
} as const;

export interface ReportRequest {
  reason: ReportRequestReason;
  /**
   * @minLength 0
   * @maxLength 300
   */
  detail?: string;
}

export interface UpdateUniversityRequest {
  universityId: number;
}

export interface ActivateCouponResponse {
  verificationCode?: string;
  activationExpiresAt?: string;
}

export interface CommonResponseActivateCouponResponse {
  isSuccess?: boolean;
  data?: ActivateCouponResponse;
}

export type DownloadCouponResponseStatus = typeof DownloadCouponResponseStatus[keyof typeof DownloadCouponResponseStatus];


export const DownloadCouponResponseStatus = {
  UNUSED: 'UNUSED',
  ACTIVATED: 'ACTIVATED',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
} as const;

export type DownloadCouponResponseBenefitType = typeof DownloadCouponResponseBenefitType[keyof typeof DownloadCouponResponseBenefitType];


export const DownloadCouponResponseBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export interface DownloadCouponResponse {
  studentCouponId?: number;
  couponCode?: string;
  status?: DownloadCouponResponseStatus;
  downloadedAt?: string;
  expiresAt?: string;
  title?: string;
  benefitType?: DownloadCouponResponseBenefitType;
  benefitValue?: string;
  minOrderAmount?: number;
  storeName?: string;
  activationExpiresAt?: string;
}

export interface CommonResponseDownloadCouponResponse {
  isSuccess?: boolean;
  data?: DownloadCouponResponse;
}

/**
 * 가게 카테고리 목록
 */
export type StoreCreateRequestStoreCategoriesItem = typeof StoreCreateRequestStoreCategoriesItem[keyof typeof StoreCreateRequestStoreCategoriesItem];


export const StoreCreateRequestStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

/**
 * 가게 분위기 목록
 */
export type StoreCreateRequestStoreMoodsItem = typeof StoreCreateRequestStoreMoodsItem[keyof typeof StoreCreateRequestStoreMoodsItem];


export const StoreCreateRequestStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

/**
 * 가게 정보 생성 요청
 */
export interface StoreCreateRequest {
  /** 상호명 */
  name: string;
  /** 지점명 */
  branch?: string;
  /** 사업자등록번호 */
  bizRegNo?: string;
  /** 도로명 주소 */
  roadAddress: string;
  /** 지번 주소 */
  jibunAddress?: string;
  /** 위도 */
  latitude?: number;
  /** 경도 */
  longitude?: number;
  /** 가게 전화번호 */
  storePhone?: string;
  /** 대표자명 */
  representativeName?: string;
  /** 가게 소개 */
  introduction?: string;
  /** 영업 시간 (JSON 형식 권장) */
  operatingHours?: string;
  /** 가게 카테고리 목록 */
  storeCategories?: StoreCreateRequestStoreCategoriesItem[];
  /** 가게 분위기 목록 */
  storeMoods?: StoreCreateRequestStoreMoodsItem[];
  /** 연결할 대학 ID 목록 */
  universityIds?: number[];
  /** 프로필 이미지 URL */
  profileImageUrl?: string;
  /** 갤러리 이미지 URL 목록 (최대 3장) */
  imageUrls?: string[];
  /** 메뉴판 이미지 URL 목록 (최대 10장) */
  menuBoardImageUrls?: string[];
}

/**
 * 가게 소식 생성 요청
 */
export interface CreateStoreNewsRequest {
  /** 소식 제목 */
  title: string;
  /** 소식 내용 */
  content: string;
  /** 이미지 URL 목록 (최대 5장) */
  imageUrls?: string[];
}

export type CreateItemRequestBadge = typeof CreateItemRequestBadge[keyof typeof CreateItemRequestBadge];


export const CreateItemRequestBadge = {
  BEST: 'BEST',
  NEW: 'NEW',
  HOT: 'HOT',
  VEGAN: 'VEGAN',
} as const;

export interface CreateItemRequest {
  name: string;
  /** @minimum 0 */
  price?: number;
  description?: string;
  itemOrder?: number;
  badge?: CreateItemRequestBadge;
  itemCategoryId?: number;
  imageUrl?: string;
  hidden?: boolean;
  representative?: boolean;
  soldOut?: boolean;
}

export type CreateCouponRequestBenefitType = typeof CreateCouponRequestBenefitType[keyof typeof CreateCouponRequestBenefitType];


export const CreateCouponRequestBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export type CreateCouponRequestStatus = typeof CreateCouponRequestStatus[keyof typeof CreateCouponRequestStatus];


export const CreateCouponRequestStatus = {
  ACTIVE: 'ACTIVE',
  SOLD_OUT: 'SOLD_OUT',
  EXPIRED: 'EXPIRED',
  WITHDRAWN_BY_OWNER: 'WITHDRAWN_BY_OWNER',
} as const;

export interface CreateCouponRequest {
  title: string;
  issueStartsAt?: string;
  issueEndsAt?: string;
  validDays: number;
  totalQuantity?: number;
  limitPerUser: number;
  benefitType: CreateCouponRequestBenefitType;
  benefitValue?: string;
  minOrderAmount?: number;
  status?: CreateCouponRequestStatus;
}

export interface VerifyCouponRequest {
  /**
   * @minLength 4
   * @maxLength 4
   */
  code: string;
}

export type VerifyCouponResponseBenefitType = typeof VerifyCouponResponseBenefitType[keyof typeof VerifyCouponResponseBenefitType];


export const VerifyCouponResponseBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export interface VerifyCouponResponse {
  studentCouponId?: number;
  studentNickname?: string;
  couponTitle?: string;
  benefitType?: VerifyCouponResponseBenefitType;
  benefitValue?: string;
  downloadedAt?: string;
  expiresAt?: string;
  isExpired?: boolean;
}

export interface CommonResponseVerifyCouponResponse {
  isSuccess?: boolean;
  data?: VerifyCouponResponse;
}

export interface StoreClaimRequest {
  storeId: number;
  bizRegNo: string;
  representativeName: string;
  storeName: string;
  storePhone?: string;
  licenseImageUrl?: string;
}

export interface PresignedUrlRequest {
  fileName: string;
  contentType: string;
}

export interface PresignedUrlResponse {
  presignedUrl?: string;
  fileUrl?: string;
}

export interface CommonResponsePresignedUrlResponse {
  isSuccess?: boolean;
  data?: PresignedUrlResponse;
}

export interface BizInfo {
  bno?: string;
  pnm?: string;
  b_no?: string;
  start_dt?: string;
  p_nm?: string;
}

export interface BizVerificationRequest {
  bizs?: BizInfo[];
}

export interface Status {
  b_no?: string;
  b_stt?: string;
  b_stt_cd?: string;
}

export interface BizStatus {
  b_no?: string;
  valid?: string;
  valid_msg?: string;
  status?: Status;
}

export interface BizVerificationResponse {
  data?: BizStatus[];
  status_code?: string;
  match_cnt?: number;
  request_cnt?: number;
}

export interface CommonResponseBizVerificationResponse {
  isSuccess?: boolean;
  data?: BizVerificationResponse;
}

export interface ChangeUsernameRequest {
  newUsername: string;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export type CreateOrganizationRequestCategory = typeof CreateOrganizationRequestCategory[keyof typeof CreateOrganizationRequestCategory];


export const CreateOrganizationRequestCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  UNIVERSITY_COUNCIL: 'UNIVERSITY_COUNCIL',
  CLUB_ASSOCIATION: 'CLUB_ASSOCIATION',
} as const;

export interface CreateOrganizationRequest {
  category: CreateOrganizationRequestCategory;
  name: string;
  parentId?: number;
  expiresAt?: string;
}

export type StudentSignupRequestGender = typeof StudentSignupRequestGender[keyof typeof StudentSignupRequestGender];


export const StudentSignupRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface StudentSignupRequest {
  /** @pattern ^[a-zA-Z0-9]{6,16}$ */
  username?: string;
  /** @pattern ^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9]).{8,20}$ */
  password?: string;
  email?: string;
  nickname?: string;
  gender?: StudentSignupRequestGender;
  birthDate?: string;
  universityId?: number;
  collegeId?: number;
  departmentId?: number;
  isClubMember?: boolean;
}

export interface LoginResponse {
  accessToken?: string;
  expiresIn?: number;
}

export interface CommonResponseLoginResponse {
  isSuccess?: boolean;
  data?: LoginResponse;
}

export type OwnerSignupRequestGender = typeof OwnerSignupRequestGender[keyof typeof OwnerSignupRequestGender];


export const OwnerSignupRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface OwnerSignupRequest {
  /** @pattern ^[a-zA-Z0-9]{6,16}$ */
  username?: string;
  /** @pattern ^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9]).{8,20}$ */
  password?: string;
  email?: string;
  gender?: OwnerSignupRequestGender;
  birthDate?: string;
  name?: string;
}

export interface CouncilSignupRequest {
  username?: string;
  password?: string;
  name?: string;
  universityId?: number;
}

export interface LoginRequest {
  username?: string;
  password?: string;
}

/**
 * 카카오 소셜 로그인 요청 (앱 네이티브)
 */
export interface KakaoLoginRequest {
  /** Kakao SDK를 통해 발급받은 Access Token */
  accessToken: string;
  /** Kakao SDK를 통해 발급받은 ID Token (선택) */
  idToken?: string;
}

/**
 * 구글 소셜 로그인 요청 (앱 네이티브)
 */
export interface GoogleLoginRequest {
  /** Google 인증 후 발급받은 JWT 형식의 id_token */
  idToken: string;
}

export interface VerifyEmailCodeRequest {
  email: string;
  code: string;
}

export interface CommonResponseString {
  isSuccess?: boolean;
  data?: string;
}

export interface FindPasswordSendCodeRequest {
  username: string;
  email: string;
}

export interface ResetPasswordRequest {
  resetToken: string;
  newPassword: string;
}

export interface SendEmailCodeRequest {
  email: string;
  universityId?: number;
}

export type CompleteSocialSignupRequestRole = typeof CompleteSocialSignupRequestRole[keyof typeof CompleteSocialSignupRequestRole];


export const CompleteSocialSignupRequestRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_COUNCIL: 'ROLE_COUNCIL',
  ROLE_STUDENT: 'ROLE_STUDENT',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export type CompleteSocialSignupRequestGender = typeof CompleteSocialSignupRequestGender[keyof typeof CompleteSocialSignupRequestGender];


export const CompleteSocialSignupRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface CompleteSocialSignupRequest {
  role?: CompleteSocialSignupRequestRole;
  gender?: CompleteSocialSignupRequestGender;
  birthDate?: string;
  nickname?: string;
  universityId?: number;
  collegeId?: number;
  departmentId?: number;
  isClubMember?: boolean;
  name?: string;
  email?: string;
}

/**
 * 애플 소셜 로그인 요청 (앱 네이티브)
 */
export interface AppleLoginRequest {
  /** Apple 인증 후 발급받은 JWT 형식의 id_token */
  idToken: string;
  /** 유저의 이름 (Apple 로그인 최초 1회에만 제공됨. 없을 경우 null) */
  name?: string;
}

export interface CreateUniversityRequest {
  name: string;
  emailDomains: string[];
  allowGeneralEmail?: boolean;
  latitude?: number;
  longitude?: number;
}

export interface CreatePartnershipRequest {
  storeId: number;
  organizationId: number;
  benefit: string;
  startsAt: string;
  endsAt: string;
}

export interface StoreClaimRejectionRequest {
  reason?: string;
}

/**
 * 이벤트 타입 목록
 */
export type CreateEventRequestEventTypesItem = typeof CreateEventRequestEventTypesItem[keyof typeof CreateEventRequestEventTypesItem];


export const CreateEventRequestEventTypesItem = {
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  STUDENT_EVENT: 'STUDENT_EVENT',
  FOOD_EVENT: 'FOOD_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  BRAND_POPUP: 'BRAND_POPUP',
} as const;

/**
 * 이벤트 생성 요청
 */
export interface CreateEventRequest {
  /** 이벤트 제목 */
  title: string;
  /** 이벤트 설명 */
  description?: string;
  /** 이벤트 부제목 */
  subtitle?: string;
  /** 이벤트 타입 목록 */
  eventTypes: CreateEventRequestEventTypesItem[];
  /** 위도 */
  latitude?: number;
  /** 경도 */
  longitude?: number;
  /** 이벤트 시작일시 */
  startDateTime: string;
  /** 이벤트 종료일시 */
  endDateTime?: string;
  /** 장소 */
  place: string;
  /**
   * 대상 대학 ID 목록 (null이면 모든 대학 대상)
   * @nullable
   */
  targetUniversityIds?: (number | null)[] | null;
  /**
   * 대상 조직 ID 목록 (COLLEGE / DEPARTMENT, 하위 조직은 상위 조직과 함께 지정해야 함)
   * @nullable
   */
  targetOrganizationIds?: (number | null)[] | null;
  /** 배너 이미지 URL */
  bannerImageUrl?: string;
  /** 일반 이미지 URL 목록 */
  imageUrls?: string[];
}

/**
 * 광고 타입 (POPUP / BANNER / FLOATING)
 */
export type CreateAdvertisementRequestAdvertisementType = typeof CreateAdvertisementRequestAdvertisementType[keyof typeof CreateAdvertisementRequestAdvertisementType];


export const CreateAdvertisementRequestAdvertisementType = {
  POPUP: 'POPUP',
  BANNER: 'BANNER',
  FLOATING: 'FLOATING',
} as const;

/**
 * 타겟 성별 (없으면 전체 성별 대상, MALE / FEMALE / UNKNOWN)
 * @nullable
 */
export type CreateAdvertisementRequestTargetGender = typeof CreateAdvertisementRequestTargetGender[keyof typeof CreateAdvertisementRequestTargetGender] | null;


export const CreateAdvertisementRequestTargetGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

/**
 * 광고 등록 요청
 */
export interface CreateAdvertisementRequest {
  /** 광고 제목 */
  title: string;
  /** 광고 타입 (POPUP / BANNER / FLOATING) */
  advertisementType: CreateAdvertisementRequestAdvertisementType;
  /** 광고 이미지 URL */
  imageUrl: string;
  /**
   * 랜딩 URL (없으면 클릭 불가)
   * @nullable
   */
  landingUrl?: string | null;
  /**
   * 노출 순서 (낮을수록 우선 노출, ACTIVE 시작 시만 적용 / 미입력 시 마지막 순서)
   * @minimum 0
   * @nullable
   */
  displayOrder?: number | null;
  /** 노출 시작일시 */
  startAt: string;
  /** 노출 종료일시 */
  endAt: string;
  /**
   * 타겟 대학 ID 목록 (없으면 전체 대학 대상)
   * @nullable
   */
  targetUniversityIds?: (number | null)[] | null;
  /**
   * 타겟 단과대/학과 ID 목록 (COLLEGE 또는 DEPARTMENT, 없으면 전체 대상, 반드시 대학 ID도 함께 지정해야 함)
   * @nullable
   */
  targetOrganizationIds?: (number | null)[] | null;
  /**
   * 타겟 성별 (없으면 전체 성별 대상, MALE / FEMALE / UNKNOWN)
   * @nullable
   */
  targetGender?: CreateAdvertisementRequestTargetGender;
}

/**
 * 별점 (1~5)
 */
export interface JsonNullableInteger {
  present?: boolean;
}

/**
 * 이미지 URL 목록 (미전송 시 유지, null/빈배열 전송 시 전체 삭제, 배열 전송 시 해당 목록으로 교체)
 */
export interface JsonNullableListString {
  present?: boolean;
}

/**
 * 리뷰 내용
 */
export interface JsonNullableString {
  present?: boolean;
}

/**
 * 리뷰 수정 요청
 */
export interface UpdateReviewRequest {
  content?: JsonNullableString;
  rating?: JsonNullableInteger;
  imageUrls?: JsonNullableListString;
}

/**
 * 영업 중지 여부
 */
export interface JsonNullableBoolean {
  present?: boolean;
}

/**
 * 경도
 */
export interface JsonNullableDouble {
  present?: boolean;
}

/**
 * 휴무일 목록
 */
export interface JsonNullableListLocalDate {
  present?: boolean;
}

/**
 * 가게 카테고리 목록
 */
export interface JsonNullableListStoreCategory {
  present?: boolean;
}

/**
 * 가게 분위기 목록
 */
export interface JsonNullableListStoreMood {
  present?: boolean;
}

/**
 * 가게 정보 수정 요청
 */
export interface StoreUpdateRequest {
  name?: JsonNullableString;
  branch?: JsonNullableString;
  roadAddress?: JsonNullableString;
  jibunAddress?: JsonNullableString;
  latitude?: JsonNullableDouble;
  longitude?: JsonNullableDouble;
  phone?: JsonNullableString;
  representativeName?: JsonNullableString;
  introduction?: JsonNullableString;
  operatingHours?: JsonNullableString;
  storeCategories?: JsonNullableListStoreCategory;
  storeMoods?: JsonNullableListStoreMood;
  holidayDates?: JsonNullableListLocalDate;
  isSuspended?: JsonNullableBoolean;
  profileImageUrl?: JsonNullableString;
  imageUrls?: JsonNullableListString;
  menuBoardImageUrls?: JsonNullableListString;
}

/**
 * 가게 소식 수정 요청
 */
export interface UpdateStoreNewsRequest {
  title?: JsonNullableString;
  content?: JsonNullableString;
  imageUrls?: JsonNullableListString;
}

/**
 * 뱃지 (NEW, BEST, HOT 등)
 */
export interface JsonNullableItemBadge {
  present?: boolean;
}

/**
 * 카테고리 ID (null 전달 시 카테고리 해제)
 */
export interface JsonNullableLong {
  present?: boolean;
}

/**
 * 메뉴(상품) 수정 요청
 */
export interface UpdateItemRequest {
  name?: JsonNullableString;
  price?: JsonNullableInteger;
  description?: JsonNullableString;
  isSoldOut?: JsonNullableBoolean;
  itemOrder?: JsonNullableInteger;
  isRepresentative?: JsonNullableBoolean;
  isHidden?: JsonNullableBoolean;
  badge?: JsonNullableItemBadge;
  itemCategoryId?: JsonNullableLong;
  imageUrl?: JsonNullableString;
}

/**
 * 혜택 타입 (DISCOUNT_AMOUNT, DISCOUNT_RATE 등)
 */
export interface JsonNullableCouponBenefitType {
  present?: boolean;
}

/**
 * 쿠폰 상태 (ACTIVE, INACTIVE 등)
 */
export interface JsonNullableCouponStatus {
  present?: boolean;
}

/**
 * 발급 종료 일시
 */
export interface JsonNullableLocalDateTime {
  present?: boolean;
}

/**
 * 쿠폰 수정 요청
 */
export interface UpdateCouponRequest {
  title?: JsonNullableString;
  issueStartsAt?: JsonNullableLocalDateTime;
  issueEndsAt?: JsonNullableLocalDateTime;
  validDays?: JsonNullableInteger;
  totalQuantity?: JsonNullableInteger;
  limitPerUser?: JsonNullableInteger;
  benefitType?: JsonNullableCouponBenefitType;
  benefitValue?: JsonNullableString;
  minOrderAmount?: JsonNullableInteger;
  status?: JsonNullableCouponStatus;
}

/**
 * 조직 카테고리 (COLLEGE, DEPARTMENT 등)
 */
export interface JsonNullableOrganizationCategory {
  present?: boolean;
}

/**
 * 조직(단과대/학과 등) 수정 요청
 */
export interface UpdateOrganizationRequest {
  category?: JsonNullableOrganizationCategory;
  name?: JsonNullableString;
  parentId?: JsonNullableLong;
  expiresAt?: JsonNullableLocalDateTime;
}

export type UserRoleUpdateRequestRole = typeof UserRoleUpdateRequestRole[keyof typeof UserRoleUpdateRequestRole];


export const UserRoleUpdateRequestRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_COUNCIL: 'ROLE_COUNCIL',
  ROLE_STUDENT: 'ROLE_STUDENT',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export interface UserRoleUpdateRequest {
  role: UserRoleUpdateRequestRole;
}

/**
 * 제휴 종료일
 */
export interface JsonNullableLocalDate {
  present?: boolean;
}

/**
 * 제휴 정보 수정 요청
 */
export interface UpdatePartnershipRequest {
  benefit?: JsonNullableString;
  startsAt?: JsonNullableLocalDate;
  endsAt?: JsonNullableLocalDate;
}

/**
 * 이벤트 상태
 */
export interface JsonNullableEventStatus {
  present?: boolean;
}

/**
 * 이벤트 타입 목록
 */
export interface JsonNullableListEventType {
  present?: boolean;
}

/**
 * 대상 조직 ID 목록 (null 전송 시 대상 전체 제거, 빈 배열도 전체 제거)
 * @nullable
 */
export type JsonNullableListLong = {
  present?: boolean;
} | null | null;

/**
 * 이벤트 수정 요청
 */
export interface UpdateEventRequest {
  title?: JsonNullableString;
  description?: JsonNullableString;
  subtitle?: JsonNullableString;
  eventTypes?: JsonNullableListEventType;
  place?: JsonNullableString;
  latitude?: JsonNullableDouble;
  longitude?: JsonNullableDouble;
  startDateTime?: JsonNullableLocalDateTime;
  endDateTime?: JsonNullableLocalDateTime;
  status?: JsonNullableEventStatus;
  targetUniversityIds?: JsonNullableListLong | null;
  targetOrganizationIds?: JsonNullableListLong | null;
  bannerImageUrl?: JsonNullableString;
  imageUrls?: JsonNullableListString;
}

/**
 * 광고 상태 (ACTIVE / INACTIVE만 직접 변경 가능)
 */
export interface JsonNullableAdvertisementStatus {
  present?: boolean;
}

/**
 * 타겟 성별 (null 전송 시 타겟 제거)
 * @nullable
 */
export type JsonNullableGender = {
  present?: boolean;
} | null | null;

/**
 * 광고 수정 요청
 */
export interface UpdateAdvertisementRequest {
  title?: JsonNullableString;
  imageUrl?: JsonNullableString;
  landingUrl?: JsonNullableString;
  displayOrder?: JsonNullableInteger;
  startAt?: JsonNullableLocalDateTime;
  endAt?: JsonNullableLocalDateTime;
  status?: JsonNullableAdvertisementStatus;
  targetUniversityIds?: JsonNullableListLong | null;
  targetOrganizationIds?: JsonNullableListLong | null;
  targetGender?: JsonNullableGender | null;
}

export interface UniversityResponse {
  id?: number;
  name?: string;
  emailDomains?: string[];
  allowGeneralEmail?: boolean;
  latitude?: number;
  longitude?: number;
}

export interface CommonResponseListUniversityResponse {
  isSuccess?: boolean;
  data?: UniversityResponse[];
}

export type OrganizationResponseCategory = typeof OrganizationResponseCategory[keyof typeof OrganizationResponseCategory];


export const OrganizationResponseCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  UNIVERSITY_COUNCIL: 'UNIVERSITY_COUNCIL',
  CLUB_ASSOCIATION: 'CLUB_ASSOCIATION',
} as const;

export interface OrganizationResponse {
  id?: number;
  userId?: number;
  universityId?: number;
  universityName?: string;
  category?: OrganizationResponseCategory;
  name?: string;
  parentId?: number;
  parentName?: string;
  expiresAt?: string;
}

export interface CommonResponseListOrganizationResponse {
  isSuccess?: boolean;
  data?: OrganizationResponse[];
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export type StudentStoreResponseStoreCategoriesItem = typeof StudentStoreResponseStoreCategoriesItem[keyof typeof StudentStoreResponseStoreCategoriesItem];


export const StudentStoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type StudentStoreResponseStoreMoodsItem = typeof StudentStoreResponseStoreMoodsItem[keyof typeof StudentStoreResponseStoreMoodsItem];


export const StudentStoreResponseStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export type StudentStoreResponseStoreStatus = typeof StudentStoreResponseStoreStatus[keyof typeof StudentStoreResponseStoreStatus];


export const StudentStoreResponseStoreStatus = {
  UNCLAIMED: 'UNCLAIMED',
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
} as const;

export type PartnershipInfoCategory = typeof PartnershipInfoCategory[keyof typeof PartnershipInfoCategory];


export const PartnershipInfoCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  UNIVERSITY_COUNCIL: 'UNIVERSITY_COUNCIL',
  CLUB_ASSOCIATION: 'CLUB_ASSOCIATION',
} as const;

export interface PartnershipInfo {
  organizationId?: number;
  category?: PartnershipInfoCategory;
  name?: string;
}

export type StudentStoreResponseCloverGrade = typeof StudentStoreResponseCloverGrade[keyof typeof StudentStoreResponseCloverGrade];


export const StudentStoreResponseCloverGrade = {
  SEED: 'SEED',
  SPROUT: 'SPROUT',
  THREE_LEAF: 'THREE_LEAF',
} as const;

export interface StudentStoreResponse {
  id?: number;
  userId?: number;
  name?: string;
  branch?: string;
  roadAddress?: string;
  jibunAddress?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  representativeName?: string;
  introduction?: string;
  operatingHours?: string;
  needToCheck?: boolean;
  storeCategories?: StudentStoreResponseStoreCategoriesItem[];
  storeMoods?: StudentStoreResponseStoreMoodsItem[];
  imageUrls?: string[];
  menuBoardImageUrls?: string[];
  averageRating?: number;
  reviewCount?: number;
  holidayDates?: string[];
  isSuspended?: boolean;
  storeStatus?: StudentStoreResponseStoreStatus;
  myPartnerships?: PartnershipInfo[];
  cloverGrade?: StudentStoreResponseCloverGrade;
  profileImageUrl?: string;
}

export interface PageResponseStudentStoreResponse {
  content?: StudentStoreResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStudentStoreResponse {
  isSuccess?: boolean;
  data?: PageResponseStudentStoreResponse;
}

export interface CommonResponseStudentStoreResponse {
  isSuccess?: boolean;
  data?: StudentStoreResponse;
}

export interface StudentReviewResponse {
  reviewId?: number;
  storeId?: number;
  storeName?: string;
  parentReviewId?: number;
  username?: string;
  nickname?: string;
  content?: string;
  rating?: number;
  createdAt?: string;
  likeCount?: number;
  imageUrls?: string[];
  liked?: boolean;
  ownerReply?: boolean;
}

export interface PageResponseStudentReviewResponse {
  content?: StudentReviewResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStudentReviewResponse {
  isSuccess?: boolean;
  data?: PageResponseStudentReviewResponse;
}

export interface ReviewStatsResponse {
  averageRating?: number;
  totalReviews?: number;
  rating1Count?: number;
  rating2Count?: number;
  rating3Count?: number;
  rating4Count?: number;
  rating5Count?: number;
}

export interface CommonResponseReviewStatsResponse {
  isSuccess?: boolean;
  data?: ReviewStatsResponse;
}

export type StudentPartnershipResponseOrganizationCategory = typeof StudentPartnershipResponseOrganizationCategory[keyof typeof StudentPartnershipResponseOrganizationCategory];


export const StudentPartnershipResponseOrganizationCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  UNIVERSITY_COUNCIL: 'UNIVERSITY_COUNCIL',
  CLUB_ASSOCIATION: 'CLUB_ASSOCIATION',
} as const;

export interface StudentPartnershipResponse {
  organizationCategory?: StudentPartnershipResponseOrganizationCategory;
  organizationName?: string;
  benefit?: string;
  isMyBenefit?: boolean;
}

export interface CommonResponseListStudentPartnershipResponse {
  isSuccess?: boolean;
  data?: StudentPartnershipResponse[];
}

export interface StoreNewsResponse {
  id?: number;
  storeId?: number;
  title?: string;
  content?: string;
  createdAt?: string;
  imageUrls?: string[];
  likeCount?: number;
  commentCount?: number;
  liked?: boolean;
}

export interface PageResponseStoreNewsResponse {
  content?: StoreNewsResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStoreNewsResponse {
  isSuccess?: boolean;
  data?: PageResponseStoreNewsResponse;
}

export type ItemResponseBadge = typeof ItemResponseBadge[keyof typeof ItemResponseBadge];


export const ItemResponseBadge = {
  BEST: 'BEST',
  NEW: 'NEW',
  HOT: 'HOT',
  VEGAN: 'VEGAN',
} as const;

export interface ItemResponse {
  id?: number;
  storeId?: number;
  name?: string;
  price?: number;
  description?: string;
  imageUrl?: string;
  itemOrder?: number;
  badge?: ItemResponseBadge;
  categoryId?: number;
  categoryName?: string;
  hidden?: boolean;
  representative?: boolean;
  soldOut?: boolean;
}

export interface CommonResponseListItemResponse {
  isSuccess?: boolean;
  data?: ItemResponse[];
}

export interface ItemCategoryResponse {
  id?: number;
  storeId?: number;
  name?: string;
}

export interface CommonResponseListItemCategoryResponse {
  isSuccess?: boolean;
  data?: ItemCategoryResponse[];
}

export type StudentCouponResponseStatus = typeof StudentCouponResponseStatus[keyof typeof StudentCouponResponseStatus];


export const StudentCouponResponseStatus = {
  ACTIVE: 'ACTIVE',
  SOLD_OUT: 'SOLD_OUT',
  EXPIRED: 'EXPIRED',
  WITHDRAWN_BY_OWNER: 'WITHDRAWN_BY_OWNER',
} as const;

export type StudentCouponResponseBenefitType = typeof StudentCouponResponseBenefitType[keyof typeof StudentCouponResponseBenefitType];


export const StudentCouponResponseBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export interface StudentCouponResponse {
  id?: number;
  storeId?: number;
  storeName?: string;
  title?: string;
  issueStartsAt?: string;
  issueEndsAt?: string;
  validDays?: number;
  totalQuantity?: number;
  limitPerUser?: number;
  status?: StudentCouponResponseStatus;
  benefitType?: StudentCouponResponseBenefitType;
  benefitValue?: string;
  minOrderAmount?: number;
  downloadCount?: number;
  isDownloaded?: boolean;
}

export interface CommonResponseListStudentCouponResponse {
  isSuccess?: boolean;
  data?: StudentCouponResponse[];
}

export interface CommonResponseListStudentStoreResponse {
  isSuccess?: boolean;
  data?: StudentStoreResponse[];
}

export type StudentStoreMapResponseStoreCategoriesItem = typeof StudentStoreMapResponseStoreCategoriesItem[keyof typeof StudentStoreMapResponseStoreCategoriesItem];


export const StudentStoreMapResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export interface StudentStoreMapResponse {
  id?: number;
  name?: string;
  latitude?: number;
  longitude?: number;
  imageUrl?: string;
  averageRating?: number;
  reviewCount?: number;
  storeCategories?: StudentStoreMapResponseStoreCategoriesItem[];
  operatingHours?: string;
  myPartnerships?: PartnershipInfo[];
  hasCoupon?: boolean;
  favoriteCount?: number;
}

export interface CommonResponseListStudentStoreMapResponse {
  isSuccess?: boolean;
  data?: StudentStoreMapResponse[];
}

export interface HotStoreResponse {
  storeId?: number;
  name?: string;
  categories?: string[];
  benefitContent?: string;
  favoriteGain?: number;
  profileImageUrl?: string;
}

export interface CommonResponseListHotStoreResponse {
  isSuccess?: boolean;
  data?: HotStoreResponse[];
}

export interface CommonResponseStoreNewsResponse {
  isSuccess?: boolean;
  data?: StoreNewsResponse;
}

export interface StoreNewsCommentResponse {
  id?: number;
  userId?: number;
  nickname?: string;
  content?: string;
  createdAt?: string;
  mine?: boolean;
}

export interface PageResponseStoreNewsCommentResponse {
  content?: StoreNewsCommentResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStoreNewsCommentResponse {
  isSuccess?: boolean;
  data?: PageResponseStoreNewsCommentResponse;
}

export interface StudentInfoResponse {
  username?: string;
  nickname?: string;
  universityId?: number;
  collegeId?: number;
  departmentId?: number;
  universityName?: string;
  collegeName?: string;
  departmentName?: string;
  isClubMember?: boolean;
}

export interface CommonResponseStudentInfoResponse {
  isSuccess?: boolean;
  data?: StudentInfoResponse;
}

export interface CommonResponseListDownloadCouponResponse {
  isSuccess?: boolean;
  data?: DownloadCouponResponse[];
}

export interface CommonResponseItemResponse {
  isSuccess?: boolean;
  data?: ItemResponse;
}

export type StudentFavoriteStoreResponseStoreCategoriesItem = typeof StudentFavoriteStoreResponseStoreCategoriesItem[keyof typeof StudentFavoriteStoreResponseStoreCategoriesItem];


export const StudentFavoriteStoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export interface StudentFavoriteStoreResponse {
  storeId?: number;
  name?: string;
  roadAddress?: string;
  jibunAddress?: string;
  storeCategories?: StudentFavoriteStoreResponseStoreCategoriesItem[];
  profileImageUrl?: string;
  averageRating?: number;
  reviewCount?: number;
  createdAt?: string;
}

export interface PageResponseStudentFavoriteStoreResponse {
  content?: StudentFavoriteStoreResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStudentFavoriteStoreResponse {
  isSuccess?: boolean;
  data?: PageResponseStudentFavoriteStoreResponse;
}

export type StudentEventResponseEventTypesItem = typeof StudentEventResponseEventTypesItem[keyof typeof StudentEventResponseEventTypesItem];


export const StudentEventResponseEventTypesItem = {
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  STUDENT_EVENT: 'STUDENT_EVENT',
  FOOD_EVENT: 'FOOD_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  BRAND_POPUP: 'BRAND_POPUP',
} as const;

export type StudentEventResponseStatus = typeof StudentEventResponseStatus[keyof typeof StudentEventResponseStatus];


export const StudentEventResponseStatus = {
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
} as const;

export interface StudentEventResponse {
  id?: number;
  targetUniversityIds?: number[];
  targetOrganizationIds?: number[];
  title?: string;
  description?: string;
  subtitle?: string;
  eventTypes?: StudentEventResponseEventTypesItem[];
  latitude?: number;
  longitude?: number;
  startDateTime?: string;
  endDateTime?: string;
  place?: string;
  status?: StudentEventResponseStatus;
  bannerImageUrl?: string;
  imageUrls?: string[];
  createdAt?: string;
}

export interface PageResponseStudentEventResponse {
  content?: StudentEventResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStudentEventResponse {
  isSuccess?: boolean;
  data?: PageResponseStudentEventResponse;
}

export interface CommonResponseStudentEventResponse {
  isSuccess?: boolean;
  data?: StudentEventResponse;
}

export interface AdvertisementResponse {
  id?: number;
  imageUrl?: string;
  landingUrl?: string;
  displayOrder?: number;
}

export interface CommonResponseListAdvertisementResponse {
  isSuccess?: boolean;
  data?: AdvertisementResponse[];
}

export interface StoreStatsResponse {
  totalRegulars?: number;
  totalIssuedCoupons?: number;
  totalUsedCoupons?: number;
  totalReviews?: number;
  favoriteIncreaseCount?: number;
}

export interface CommonResponseStoreStatsResponse {
  isSuccess?: boolean;
  data?: StoreStatsResponse;
}

export interface StoreRegistrationStatusResponse {
  hasMenu?: boolean;
  hasStoreInfo?: boolean;
}

export interface CommonResponseStoreRegistrationStatusResponse {
  isSuccess?: boolean;
  data?: StoreRegistrationStatusResponse;
}

export type CouponResponseStatus = typeof CouponResponseStatus[keyof typeof CouponResponseStatus];


export const CouponResponseStatus = {
  ACTIVE: 'ACTIVE',
  SOLD_OUT: 'SOLD_OUT',
  EXPIRED: 'EXPIRED',
  WITHDRAWN_BY_OWNER: 'WITHDRAWN_BY_OWNER',
} as const;

export type CouponResponseBenefitType = typeof CouponResponseBenefitType[keyof typeof CouponResponseBenefitType];


export const CouponResponseBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export interface CouponResponse {
  id?: number;
  storeId?: number;
  storeName?: string;
  title?: string;
  issueStartsAt?: string;
  issueEndsAt?: string;
  validDays?: number;
  totalQuantity?: number;
  limitPerUser?: number;
  status?: CouponResponseStatus;
  benefitType?: CouponResponseBenefitType;
  benefitValue?: string;
  minOrderAmount?: number;
  downloadCount?: number;
  usedCount?: number;
  isDownloaded?: boolean;
}

export interface CommonResponseListCouponResponse {
  isSuccess?: boolean;
  data?: CouponResponse[];
}

export type OwnerStoreResponseStoreCategoriesItem = typeof OwnerStoreResponseStoreCategoriesItem[keyof typeof OwnerStoreResponseStoreCategoriesItem];


export const OwnerStoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type OwnerStoreResponseStoreMoodsItem = typeof OwnerStoreResponseStoreMoodsItem[keyof typeof OwnerStoreResponseStoreMoodsItem];


export const OwnerStoreResponseStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export type OwnerStoreResponseStoreStatus = typeof OwnerStoreResponseStoreStatus[keyof typeof OwnerStoreResponseStoreStatus];


export const OwnerStoreResponseStoreStatus = {
  UNCLAIMED: 'UNCLAIMED',
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
} as const;

export type OwnerStoreResponseCloverGrade = typeof OwnerStoreResponseCloverGrade[keyof typeof OwnerStoreResponseCloverGrade];


export const OwnerStoreResponseCloverGrade = {
  SEED: 'SEED',
  SPROUT: 'SPROUT',
  THREE_LEAF: 'THREE_LEAF',
} as const;

export interface OwnerStoreResponse {
  id?: number;
  userId?: number;
  name?: string;
  branch?: string;
  roadAddress?: string;
  jibunAddress?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  representativeName?: string;
  introduction?: string;
  operatingHours?: string;
  needToCheck?: boolean;
  storeCategories?: OwnerStoreResponseStoreCategoriesItem[];
  storeMoods?: OwnerStoreResponseStoreMoodsItem[];
  imageUrls?: string[];
  menuBoardImageUrls?: string[];
  averageRating?: number;
  reviewCount?: number;
  holidayDates?: string[];
  isSuspended?: boolean;
  storeStatus?: OwnerStoreResponseStoreStatus;
  cloverGrade?: OwnerStoreResponseCloverGrade;
  profileImageUrl?: string;
}

export interface CommonResponseListOwnerStoreResponse {
  isSuccess?: boolean;
  data?: OwnerStoreResponse[];
}

export type StoreResponseStoreCategoriesItem = typeof StoreResponseStoreCategoriesItem[keyof typeof StoreResponseStoreCategoriesItem];


export const StoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type StoreResponseStoreMoodsItem = typeof StoreResponseStoreMoodsItem[keyof typeof StoreResponseStoreMoodsItem];


export const StoreResponseStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export type StoreResponseStoreStatus = typeof StoreResponseStoreStatus[keyof typeof StoreResponseStoreStatus];


export const StoreResponseStoreStatus = {
  UNCLAIMED: 'UNCLAIMED',
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
} as const;

export type StoreResponseCloverGrade = typeof StoreResponseCloverGrade[keyof typeof StoreResponseCloverGrade];


export const StoreResponseCloverGrade = {
  SEED: 'SEED',
  SPROUT: 'SPROUT',
  THREE_LEAF: 'THREE_LEAF',
} as const;

export interface StoreResponse {
  id?: number;
  userId?: number;
  name?: string;
  branch?: string;
  roadAddress?: string;
  jibunAddress?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  representativeName?: string;
  introduction?: string;
  operatingHours?: string;
  needToCheck?: boolean;
  storeCategories?: StoreResponseStoreCategoriesItem[];
  storeMoods?: StoreResponseStoreMoodsItem[];
  imageUrls?: string[];
  menuBoardImageUrls?: string[];
  averageRating?: number;
  reviewCount?: number;
  holidayDates?: string[];
  isSuspended?: boolean;
  storeStatus?: StoreResponseStoreStatus;
  myPartnerships?: PartnershipInfo[];
  cloverGrade?: StoreResponseCloverGrade;
  profileImageUrl?: string;
}

export interface CommonResponseListStoreResponse {
  isSuccess?: boolean;
  data?: StoreResponse[];
}

export type MyStoreClaimResponseStatus = typeof MyStoreClaimResponseStatus[keyof typeof MyStoreClaimResponseStatus];


export const MyStoreClaimResponseStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
} as const;

export interface MyStoreClaimResponse {
  id?: number;
  storeId?: number;
  storeName?: string;
  representativeName?: string;
  status?: MyStoreClaimResponseStatus;
  rejectReason?: string;
  createdAt?: string;
}

export interface CommonResponseListMyStoreClaimResponse {
  isSuccess?: boolean;
  data?: MyStoreClaimResponse[];
}

export interface OwnerReviewResponse {
  reviewId?: number;
  storeId?: number;
  storeName?: string;
  parentReviewId?: number;
  username?: string;
  nickname?: string;
  content?: string;
  rating?: number;
  createdAt?: string;
  likeCount?: number;
  imageUrls?: string[];
  verified?: boolean;
  ownerReply?: boolean;
}

export interface PageResponseOwnerReviewResponse {
  content?: OwnerReviewResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseOwnerReviewResponse {
  isSuccess?: boolean;
  data?: PageResponseOwnerReviewResponse;
}

export type OwnerCouponResponseStatus = typeof OwnerCouponResponseStatus[keyof typeof OwnerCouponResponseStatus];


export const OwnerCouponResponseStatus = {
  ACTIVE: 'ACTIVE',
  SOLD_OUT: 'SOLD_OUT',
  EXPIRED: 'EXPIRED',
  WITHDRAWN_BY_OWNER: 'WITHDRAWN_BY_OWNER',
} as const;

export type OwnerCouponResponseBenefitType = typeof OwnerCouponResponseBenefitType[keyof typeof OwnerCouponResponseBenefitType];


export const OwnerCouponResponseBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export interface OwnerCouponResponse {
  id?: number;
  storeId?: number;
  storeName?: string;
  title?: string;
  issueStartsAt?: string;
  issueEndsAt?: string;
  validDays?: number;
  totalQuantity?: number;
  limitPerUser?: number;
  status?: OwnerCouponResponseStatus;
  benefitType?: OwnerCouponResponseBenefitType;
  benefitValue?: string;
  minOrderAmount?: number;
  downloadCount?: number;
  usedCount?: number;
}

export interface CommonResponseListOwnerCouponResponse {
  isSuccess?: boolean;
  data?: OwnerCouponResponse[];
}

/**
 * 성별
 */
export type OwnerInfoResponseGender = typeof OwnerInfoResponseGender[keyof typeof OwnerInfoResponseGender];


export const OwnerInfoResponseGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

/**
 * 점주 정보 응답
 */
export interface OwnerInfoResponse {
  /** 이름 */
  name?: string;
  /** 이메일 */
  email?: string;
  /** 아이디 */
  username?: string;
  /** 성별 */
  gender?: OwnerInfoResponseGender;
  /** 생년월일 */
  birthDate?: string;
}

export interface CommonResponseOwnerInfoResponse {
  isSuccess?: boolean;
  data?: OwnerInfoResponse;
}

export interface CommonResponseBoolean {
  isSuccess?: boolean;
  data?: boolean;
}

export type AdminUserResponseRole = typeof AdminUserResponseRole[keyof typeof AdminUserResponseRole];


export const AdminUserResponseRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_COUNCIL: 'ROLE_COUNCIL',
  ROLE_STUDENT: 'ROLE_STUDENT',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export type AdminUserResponseSocialType = typeof AdminUserResponseSocialType[keyof typeof AdminUserResponseSocialType];


export const AdminUserResponseSocialType = {
  LOCAL: 'LOCAL',
  GOOGLE: 'GOOGLE',
  KAKAO: 'KAKAO',
  APPLE: 'APPLE',
} as const;

export interface AdminUserResponse {
  id?: number;
  username?: string;
  role?: AdminUserResponseRole;
  socialType?: AdminUserResponseSocialType;
}

export interface PageResponseAdminUserResponse {
  content?: AdminUserResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseAdminUserResponse {
  isSuccess?: boolean;
  data?: PageResponseAdminUserResponse;
}

export type AdminPartnershipResponseCategory = typeof AdminPartnershipResponseCategory[keyof typeof AdminPartnershipResponseCategory];


export const AdminPartnershipResponseCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  UNIVERSITY_COUNCIL: 'UNIVERSITY_COUNCIL',
  CLUB_ASSOCIATION: 'CLUB_ASSOCIATION',
} as const;

export interface AdminPartnershipResponse {
  id?: number;
  organizationId?: number;
  organizationName?: string;
  universityName?: string;
  category?: AdminPartnershipResponseCategory;
  benefit?: string;
  startsAt?: string;
  endsAt?: string;
  storeId?: number;
  storeName?: string;
}

export interface CommonResponseListAdminPartnershipResponse {
  isSuccess?: boolean;
  data?: AdminPartnershipResponse[];
}

export type AdminStoreResponseStoreCategoriesItem = typeof AdminStoreResponseStoreCategoriesItem[keyof typeof AdminStoreResponseStoreCategoriesItem];


export const AdminStoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type AdminStoreResponseStoreMoodsItem = typeof AdminStoreResponseStoreMoodsItem[keyof typeof AdminStoreResponseStoreMoodsItem];


export const AdminStoreResponseStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export type AdminStoreResponseStoreStatus = typeof AdminStoreResponseStoreStatus[keyof typeof AdminStoreResponseStoreStatus];


export const AdminStoreResponseStoreStatus = {
  UNCLAIMED: 'UNCLAIMED',
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
} as const;

export type AdminStoreResponseCloverGrade = typeof AdminStoreResponseCloverGrade[keyof typeof AdminStoreResponseCloverGrade];


export const AdminStoreResponseCloverGrade = {
  SEED: 'SEED',
  SPROUT: 'SPROUT',
  THREE_LEAF: 'THREE_LEAF',
} as const;

export interface AdminStoreResponse {
  id?: number;
  userId?: number;
  name?: string;
  branch?: string;
  roadAddress?: string;
  jibunAddress?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  representativeName?: string;
  introduction?: string;
  operatingHours?: string;
  needToCheck?: boolean;
  storeCategories?: AdminStoreResponseStoreCategoriesItem[];
  storeMoods?: AdminStoreResponseStoreMoodsItem[];
  imageUrls?: string[];
  menuBoardImageUrls?: string[];
  averageRating?: number;
  reviewCount?: number;
  holidayDates?: string[];
  isSuspended?: boolean;
  storeStatus?: AdminStoreResponseStoreStatus;
  cloverGrade?: AdminStoreResponseCloverGrade;
  profileImageUrl?: string;
}

export interface PageResponseAdminStoreResponse {
  content?: AdminStoreResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseAdminStoreResponse {
  isSuccess?: boolean;
  data?: PageResponseAdminStoreResponse;
}

export interface CommonResponseAdminStoreResponse {
  isSuccess?: boolean;
  data?: AdminStoreResponse;
}

export interface Coordinate {
  latitude?: number;
  longitude?: number;
}

export interface CommonResponseCoordinate {
  isSuccess?: boolean;
  data?: Coordinate;
}

export type AdminStoreClaimResponseStatus = typeof AdminStoreClaimResponseStatus[keyof typeof AdminStoreClaimResponseStatus];


export const AdminStoreClaimResponseStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
} as const;

export interface AdminStoreClaimResponse {
  id?: number;
  storeId?: number;
  userId?: number;
  name?: string;
  storeName?: string;
  bizRegNo?: string;
  representativeName?: string;
  storePhone?: string;
  licenseImageUrl?: string;
  status?: AdminStoreClaimResponseStatus;
  createdAt?: string;
  adminMemo?: string;
}

export interface SortObject {
  sorted?: boolean;
  empty?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  offset?: number;
  sort?: SortObject;
  unpaged?: boolean;
}

export interface PageAdminStoreClaimResponse {
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  pageable?: PageableObject;
  size?: number;
  content?: AdminStoreClaimResponse[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  last?: boolean;
  empty?: boolean;
}

export interface CommonResponsePageAdminStoreClaimResponse {
  isSuccess?: boolean;
  data?: PageAdminStoreClaimResponse;
}

export type AdminEventResponseEventTypesItem = typeof AdminEventResponseEventTypesItem[keyof typeof AdminEventResponseEventTypesItem];


export const AdminEventResponseEventTypesItem = {
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  STUDENT_EVENT: 'STUDENT_EVENT',
  FOOD_EVENT: 'FOOD_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  BRAND_POPUP: 'BRAND_POPUP',
} as const;

export type AdminEventResponseStatus = typeof AdminEventResponseStatus[keyof typeof AdminEventResponseStatus];


export const AdminEventResponseStatus = {
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
} as const;

export interface TargetUniversityInfo {
  id?: number;
  name?: string;
}

export type TargetOrganizationInfoCategory = typeof TargetOrganizationInfoCategory[keyof typeof TargetOrganizationInfoCategory];


export const TargetOrganizationInfoCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  UNIVERSITY_COUNCIL: 'UNIVERSITY_COUNCIL',
  CLUB_ASSOCIATION: 'CLUB_ASSOCIATION',
} as const;

export interface TargetOrganizationInfo {
  id?: number;
  name?: string;
  category?: TargetOrganizationInfoCategory;
}

export interface AdminEventResponse {
  id?: number;
  title?: string;
  description?: string;
  subtitle?: string;
  eventTypes?: AdminEventResponseEventTypesItem[];
  latitude?: number;
  longitude?: number;
  startDateTime?: string;
  endDateTime?: string;
  place?: string;
  status?: AdminEventResponseStatus;
  bannerImageUrl?: string;
  imageUrls?: string[];
  createdAt?: string;
  targetUniversities?: TargetUniversityInfo[];
  targetOrganizations?: TargetOrganizationInfo[];
}

export interface PageResponseAdminEventResponse {
  content?: AdminEventResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseAdminEventResponse {
  isSuccess?: boolean;
  data?: PageResponseAdminEventResponse;
}

export interface CommonResponseAdminEventResponse {
  isSuccess?: boolean;
  data?: AdminEventResponse;
}

export type AdminAdvertisementResponseAdvertisementType = typeof AdminAdvertisementResponseAdvertisementType[keyof typeof AdminAdvertisementResponseAdvertisementType];


export const AdminAdvertisementResponseAdvertisementType = {
  POPUP: 'POPUP',
  BANNER: 'BANNER',
  FLOATING: 'FLOATING',
} as const;

export type AdminAdvertisementResponseStatus = typeof AdminAdvertisementResponseStatus[keyof typeof AdminAdvertisementResponseStatus];


export const AdminAdvertisementResponseStatus = {
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ENDED: 'ENDED',
} as const;

export type AdminAdvertisementResponseTargetGender = typeof AdminAdvertisementResponseTargetGender[keyof typeof AdminAdvertisementResponseTargetGender];


export const AdminAdvertisementResponseTargetGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface AdminAdvertisementResponse {
  id?: number;
  title?: string;
  advertisementType?: AdminAdvertisementResponseAdvertisementType;
  imageUrl?: string;
  landingUrl?: string;
  status?: AdminAdvertisementResponseStatus;
  displayOrder?: number;
  startAt?: string;
  endAt?: string;
  createdAt?: string;
  targetUniversities?: TargetUniversityInfo[];
  targetOrganizations?: TargetOrganizationInfo[];
  targetGender?: AdminAdvertisementResponseTargetGender;
}

export interface PageResponseAdminAdvertisementResponse {
  content?: AdminAdvertisementResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseAdminAdvertisementResponse {
  isSuccess?: boolean;
  data?: PageResponseAdminAdvertisementResponse;
}

export type WithdrawRequestReasonsItem = typeof WithdrawRequestReasonsItem[keyof typeof WithdrawRequestReasonsItem];


export const WithdrawRequestReasonsItem = {
  UNUSED: 'UNUSED',
  INSUFFICIENT_BENEFITS: 'INSUFFICIENT_BENEFITS',
  INCONVENIENT: 'INCONVENIENT',
  TOO_MANY_ADS: 'TOO_MANY_ADS',
  NOT_NEEDED: 'NOT_NEEDED',
  OTHER: 'OTHER',
} as const;

export interface WithdrawRequest {
  reasons: WithdrawRequestReasonsItem[];
  detailReason?: string;
}

export type GetReviewsParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetCommentsParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetStoresParams = {
/**
 * 검색 키워드 (상점 이름)
 */
keyword?: string;
/**
 * 카테고리 필터 (복수 선택 가능)
 */
categories?: GetStoresCategoriesItem[];
/**
 * 분위기 필터 (복수 선택 가능)
 */
moods?: GetStoresMoodsItem[];
/**
 * 대학(상권) ID 필터
 */
universityId?: number;
/**
 * 제휴 업체 보유 여부 필터 (true: 있음, false: 없음, 생략: 전체)
 */
hasPartnership?: boolean;
/**
 * 상점 상태 필터 (UNCLAIMED, ACTIVE, BANNED, 생략: 전체)
 */
storeStatus?: GetStoresStoreStatus;
/**
 * 페이징 정보 (page, size, sort)
 */
pageable: Pageable;
};

export type GetStoresCategoriesItem = typeof GetStoresCategoriesItem[keyof typeof GetStoresCategoriesItem];


export const GetStoresCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type GetStoresMoodsItem = typeof GetStoresMoodsItem[keyof typeof GetStoresMoodsItem];


export const GetStoresMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export type GetStoresStoreStatus = typeof GetStoresStoreStatus[keyof typeof GetStoresStoreStatus];


export const GetStoresStoreStatus = {
  UNCLAIMED: 'UNCLAIMED',
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
} as const;

export type GetReviews1Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetStoreNewsListParams = {
/**
 * 페이징 정보 (page, size, sort)
 */
pageable: Pageable;
};

export type CreateItemCategoryBody = {[key: string]: string};

export type GetComments1Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetStoreNewsList1Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type CreateItemCategory1Body = {[key: string]: string};

export type GetComments2Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetStores1Params = {
/**
 * 검색어 (상점명)
 */
keyword?: string;
/**
 * 가게 유형
 */
categories?: GetStores1CategoriesItem[];
/**
 * 대학 ID
 */
universityId?: number;
/**
 * 상점 상태
 */
storeStatus?: GetStores1StoreStatus;
/**
 * 제휴 여부
 */
hasPartnership?: boolean;
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};

export type GetStores1CategoriesItem = typeof GetStores1CategoriesItem[keyof typeof GetStores1CategoriesItem];


export const GetStores1CategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type GetStores1StoreStatus = typeof GetStores1StoreStatus[keyof typeof GetStores1StoreStatus];


export const GetStores1StoreStatus = {
  UNCLAIMED: 'UNCLAIMED',
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
} as const;

export type CreateItemCategory2Body = {[key: string]: string};

export type UploadStoreDataBody = {
  /** 엑셀 파일 (.xlsx) */
  file: Blob;
};

export type UploadPartnershipDataParams = {
/**
 * 대상 조직 ID (관리자용)
 */
organizationId?: number;
};

export type UploadPartnershipDataBody = {
  /** 엑셀 파일 */
  file: Blob;
};

export type GetEventsParams = {
/**
 * 검색 키워드(제목)
 */
keyword?: string;
/**
 * 이벤트 타입 필터 (복수 선택 가능)
 */
eventTypes?: GetEventsEventTypesItem[];
/**
 * 상태 필터
 */
status?: GetEventsStatus;
/**
 * 대학 ID (미입력 시 전체 조회)
 */
universityId?: number;
/**
 * 페이지 정보
 */
pageable: Pageable;
};

export type GetEventsEventTypesItem = typeof GetEventsEventTypesItem[keyof typeof GetEventsEventTypesItem];


export const GetEventsEventTypesItem = {
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  STUDENT_EVENT: 'STUDENT_EVENT',
  FOOD_EVENT: 'FOOD_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  BRAND_POPUP: 'BRAND_POPUP',
} as const;

export type GetEventsStatus = typeof GetEventsStatus[keyof typeof GetEventsStatus];


export const GetEventsStatus = {
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
} as const;

export type GetAdvertisementsParams = {
/**
 * 광고 타입 필터 (POPUP / BANNER / FLOATING)
 */
type?: GetAdvertisementsType;
/**
 * 광고 상태 필터 (SCHEDULED / ACTIVE / INACTIVE / ENDED)
 */
status?: GetAdvertisementsStatus;
pageable: Pageable;
};

export type GetAdvertisementsType = typeof GetAdvertisementsType[keyof typeof GetAdvertisementsType];


export const GetAdvertisementsType = {
  POPUP: 'POPUP',
  BANNER: 'BANNER',
  FLOATING: 'FLOATING',
} as const;

export type GetAdvertisementsStatus = typeof GetAdvertisementsStatus[keyof typeof GetAdvertisementsStatus];


export const GetAdvertisementsStatus = {
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ENDED: 'ENDED',
} as const;

export type UpdateItemCategoryBody = {[key: string]: string};

export type UpdateItemCategory1Body = {[key: string]: string};

export type UpdateItemCategory2Body = {[key: string]: string};

export type HealthCheck200 = {[key: string]: { [key: string]: unknown }};

export type GetStores2Params = {
/**
 * 검색 키워드 (상점 이름)
 */
keyword?: string;
/**
 * 카테고리 필터 (복수 선택 가능)
 */
categories?: GetStores2CategoriesItem[];
/**
 * 분위기 필터 (복수 선택 가능)
 */
moods?: GetStores2MoodsItem[];
/**
 * 대학(상권) ID 필터
 */
universityId?: number;
/**
 * 제휴 업체 보유 여부 필터
 */
hasPartnership?: boolean;
/**
 * 상점 상태 필터
 */
storeStatus?: GetStores2StoreStatus;
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetStores2CategoriesItem = typeof GetStores2CategoriesItem[keyof typeof GetStores2CategoriesItem];


export const GetStores2CategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type GetStores2MoodsItem = typeof GetStores2MoodsItem[keyof typeof GetStores2MoodsItem];


export const GetStores2MoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export type GetStores2StoreStatus = typeof GetStores2StoreStatus[keyof typeof GetStores2StoreStatus];


export const GetStores2StoreStatus = {
  UNCLAIMED: 'UNCLAIMED',
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
} as const;

export type GetStoreNewsList2Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetNearbyStoresParams = {
/**
 * 위도
 */
latitude: number;
/**
 * 경도
 */
longitude: number;
/**
 * 반경(km)
 */
radius: number;
};

export type GetStoreMapParams = {
/**
 * 대학(상권) ID 필터
 */
universityId?: number;
};

export type GetStoresByLocationParams = {
/**
 * 위도
 */
latitude: number;
/**
 * 경도
 */
longitude: number;
};

export type GetMyReviewsParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetMyFavoritesParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetEvents1Params = {
/**
 * 검색 키워드(제목)
 */
keyword?: string;
/**
 * 이벤트 타입 필터 (복수 선택 가능)
 */
eventTypes?: GetEvents1EventTypesItem[];
/**
 * 상태 필터
 */
status?: GetEvents1Status;
/**
 * 페이지 정보
 */
pageable: Pageable;
};

export type GetEvents1EventTypesItem = typeof GetEvents1EventTypesItem[keyof typeof GetEvents1EventTypesItem];


export const GetEvents1EventTypesItem = {
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  STUDENT_EVENT: 'STUDENT_EVENT',
  FOOD_EVENT: 'FOOD_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  BRAND_POPUP: 'BRAND_POPUP',
} as const;

export type GetEvents1Status = typeof GetEvents1Status[keyof typeof GetEvents1Status];


export const GetEvents1Status = {
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
} as const;

export type GetNearbyStores1Params = {
/**
 * 위도
 */
latitude: number;
/**
 * 경도
 */
longitude: number;
/**
 * 반경(km)
 */
radius: number;
};

export type GetStoreMap1Params = {
/**
 * 대학(상권) ID 필터
 */
universityId?: number;
};

export type GetStoresByLocation1Params = {
/**
 * 위도
 */
latitude: number;
/**
 * 경도
 */
longitude: number;
};

export type SearchUnclaimedStoresParams = {
keyword: string;
};

export type GetMyReviews1Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetReviews2Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type SearchUnclaimedStores1Params = {
keyword: string;
};

export type GetMyReviews2Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetMyFavorites1Params = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetEvents2Params = {
/**
 * 검색 키워드(제목)
 */
keyword?: string;
/**
 * 이벤트 타입 필터 (복수 선택 가능)
 */
eventTypes?: GetEvents2EventTypesItem[];
/**
 * 상태 필터
 */
status?: GetEvents2Status;
/**
 * 페이지 정보
 */
pageable: Pageable;
};

export type GetEvents2EventTypesItem = typeof GetEvents2EventTypesItem[keyof typeof GetEvents2EventTypesItem];


export const GetEvents2EventTypesItem = {
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  STUDENT_EVENT: 'STUDENT_EVENT',
  FOOD_EVENT: 'FOOD_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  BRAND_POPUP: 'BRAND_POPUP',
} as const;

export type GetEvents2Status = typeof GetEvents2Status[keyof typeof GetEvents2Status];


export const GetEvents2Status = {
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
} as const;

export type CheckUsernameAvailabilityParams = {
username: string;
};

export type GetAllUsersParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetGeocodeParams = {
/**
 * 도로명 주소 (예: 전라북도 전주시 덕진구 명륜3길 22)
 */
address: string;
};

export type GetStoreClaimsParams = {
/**
 * 요청 상태 (PENDING, APPROVED, REJECTED, CANCELED)
 */
status?: GetStoreClaimsStatus;
pageable: Pageable;
};

export type GetStoreClaimsStatus = typeof GetStoreClaimsStatus[keyof typeof GetStoreClaimsStatus];


export const GetStoreClaimsStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
} as const;

export type ExportPartnershipTemplateParams = {
/**
 * 대상 대학 ID
 */
universityId: number;
};

