/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseItemResponse,
  CommonResponseListItemResponse,
  CommonResponseLong,
  CommonResponseVoid,
  CreateItemRequest,
  SwaggerErrorResponse,
  UpdateItemRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 특정 상점의 모든 상품을 조회합니다.
 * @summary [점주] 상점별 상품 목록 조회
 */
export type getItems1Response200 = {
  data: CommonResponseListItemResponse
  status: 200
}

export type getItems1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getItems1ResponseSuccess = (getItems1Response200) & {
  headers: Headers;
};
export type getItems1ResponseError = (getItems1Response404) & {
  headers: Headers;
};

export type getItems1Response = (getItems1ResponseSuccess | getItems1ResponseError)

export const getGetItems1Url = (storeId: number,) => {


  

  return `/api/owner/stores/${storeId}/items`
}

export const getItems1 = async (storeId: number, options?: RequestInit): Promise<getItems1Response> => {
  
  return customFetch<getItems1Response>(getGetItems1Url(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetItems1QueryKey = (storeId?: number,) => {
    return [
    `/api/owner/stores/${storeId}/items`
    ] as const;
    }

    
export const getGetItems1QueryOptions = <TData = Awaited<ReturnType<typeof getItems1>>, TError = SwaggerErrorResponse>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItems1QueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItems1>>> = ({ signal }) => getItems1(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItems1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItems1QueryResult = NonNullable<Awaited<ReturnType<typeof getItems1>>>
export type GetItems1QueryError = SwaggerErrorResponse


export function useGetItems1<TData = Awaited<ReturnType<typeof getItems1>>, TError = SwaggerErrorResponse>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems1>>,
          TError,
          Awaited<ReturnType<typeof getItems1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems1<TData = Awaited<ReturnType<typeof getItems1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems1>>,
          TError,
          Awaited<ReturnType<typeof getItems1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems1<TData = Awaited<ReturnType<typeof getItems1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 상점별 상품 목록 조회
 */

export function useGetItems1<TData = Awaited<ReturnType<typeof getItems1>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItems1QueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상점에 새로운 상품을 등록합니다. (본인 상점만 가능)
 * @summary [점주] 상품 등록
 */
export type createItem1Response201 = {
  data: CommonResponseLong
  status: 201
}

export type createItem1Response400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type createItem1Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type createItem1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type createItem1ResponseSuccess = (createItem1Response201) & {
  headers: Headers;
};
export type createItem1ResponseError = (createItem1Response400 | createItem1Response403 | createItem1Response404) & {
  headers: Headers;
};

export type createItem1Response = (createItem1ResponseSuccess | createItem1ResponseError)

export const getCreateItem1Url = (storeId: number,) => {


  

  return `/api/owner/stores/${storeId}/items`
}

export const createItem1 = async (storeId: number,
    createItemRequest: CreateItemRequest, options?: RequestInit): Promise<createItem1Response> => {
  
  return customFetch<createItem1Response>(getCreateItem1Url(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createItemRequest,)
  }
);}




export const getCreateItem1MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem1>>, TError,{storeId: number;data: CreateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createItem1>>, TError,{storeId: number;data: CreateItemRequest}, TContext> => {

const mutationKey = ['createItem1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createItem1>>, {storeId: number;data: CreateItemRequest}> = (props) => {
          const {storeId,data} = props ?? {};

          return  createItem1(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateItem1MutationResult = NonNullable<Awaited<ReturnType<typeof createItem1>>>
    export type CreateItem1MutationBody = CreateItemRequest
    export type CreateItem1MutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 상품 등록
 */
export const useCreateItem1 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem1>>, TError,{storeId: number;data: CreateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createItem1>>,
        TError,
        {storeId: number;data: CreateItemRequest},
        TContext
      > => {
      return useMutation(getCreateItem1MutationOptions(options), queryClient);
    }
    /**
 * 상품 ID로 상품의 상세 정보를 조회합니다.
 * @summary [점주] 상품 단건 조회
 */
export type getItemResponse200 = {
  data: CommonResponseItemResponse
  status: 200
}

export type getItemResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getItemResponseSuccess = (getItemResponse200) & {
  headers: Headers;
};
export type getItemResponseError = (getItemResponse404) & {
  headers: Headers;
};

export type getItemResponse = (getItemResponseSuccess | getItemResponseError)

export const getGetItemUrl = (itemId: number,) => {


  

  return `/api/owner/items/${itemId}`
}

export const getItem = async (itemId: number, options?: RequestInit): Promise<getItemResponse> => {
  
  return customFetch<getItemResponse>(getGetItemUrl(itemId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetItemQueryKey = (itemId?: number,) => {
    return [
    `/api/owner/items/${itemId}`
    ] as const;
    }

    
export const getGetItemQueryOptions = <TData = Awaited<ReturnType<typeof getItem>>, TError = SwaggerErrorResponse>(itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemQueryKey(itemId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItem>>> = ({ signal }) => getItem(itemId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(itemId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemQueryResult = NonNullable<Awaited<ReturnType<typeof getItem>>>
export type GetItemQueryError = SwaggerErrorResponse


export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = SwaggerErrorResponse>(
 itemId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = SwaggerErrorResponse>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = SwaggerErrorResponse>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 상품 단건 조회
 */

export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = SwaggerErrorResponse>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemQueryOptions(itemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상품을 삭제합니다. (본인 상점만 가능)
 * @summary [점주] 상품 삭제
 */
export type deleteItemResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteItemResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteItemResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteItemResponseSuccess = (deleteItemResponse204) & {
  headers: Headers;
};
export type deleteItemResponseError = (deleteItemResponse403 | deleteItemResponse404) & {
  headers: Headers;
};

export type deleteItemResponse = (deleteItemResponseSuccess | deleteItemResponseError)

export const getDeleteItemUrl = (itemId: number,) => {


  

  return `/api/owner/items/${itemId}`
}

export const deleteItem = async (itemId: number, options?: RequestInit): Promise<deleteItemResponse> => {
  
  return customFetch<deleteItemResponse>(getDeleteItemUrl(itemId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteItemMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: number}, TContext> => {

const mutationKey = ['deleteItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteItem>>, {itemId: number}> = (props) => {
          const {itemId} = props ?? {};

          return  deleteItem(itemId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteItem>>>
    
    export type DeleteItemMutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 상품 삭제
 */
export const useDeleteItem = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteItem>>,
        TError,
        {itemId: number},
        TContext
      > => {
      return useMutation(getDeleteItemMutationOptions(options), queryClient);
    }
    /**
 * 상품 정보를 수정합니다. (본인 상점만 가능)
 * @summary [점주] 상품 수정
 */
export type updateItemResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type updateItemResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updateItemResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type updateItemResponseSuccess = (updateItemResponse200) & {
  headers: Headers;
};
export type updateItemResponseError = (updateItemResponse403 | updateItemResponse404) & {
  headers: Headers;
};

export type updateItemResponse = (updateItemResponseSuccess | updateItemResponseError)

export const getUpdateItemUrl = (itemId: number,) => {


  

  return `/api/owner/items/${itemId}`
}

export const updateItem = async (itemId: number,
    updateItemRequest: UpdateItemRequest, options?: RequestInit): Promise<updateItemResponse> => {
  
  return customFetch<updateItemResponse>(getUpdateItemUrl(itemId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateItemRequest,)
  }
);}




export const getUpdateItemMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{itemId: number;data: UpdateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{itemId: number;data: UpdateItemRequest}, TContext> => {

const mutationKey = ['updateItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateItem>>, {itemId: number;data: UpdateItemRequest}> = (props) => {
          const {itemId,data} = props ?? {};

          return  updateItem(itemId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateItem>>>
    export type UpdateItemMutationBody = UpdateItemRequest
    export type UpdateItemMutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 상품 수정
 */
export const useUpdateItem = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{itemId: number;data: UpdateItemRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateItem>>,
        TError,
        {itemId: number;data: UpdateItemRequest},
        TContext
      > => {
      return useMutation(getUpdateItemMutationOptions(options), queryClient);
    }
    