/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseLong,
  CommonResponsePageResponseStoreNewsCommentResponse,
  CommonResponsePageResponseStoreNewsResponse,
  CommonResponseStoreNewsResponse,
  CommonResponseVoid,
  CreateStoreNewsCommentRequest,
  CreateStoreNewsRequest,
  GetComments2Params,
  GetStoreNewsList1Params,
  SwaggerErrorResponse,
  UpdateStoreNewsRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 가게의 소식 목록을 조회합니다.
 * @summary [점주] 소식 목록 조회
 */
export type getStoreNewsList1Response200 = {
  data: CommonResponsePageResponseStoreNewsResponse
  status: 200
}
    
export type getStoreNewsList1ResponseSuccess = (getStoreNewsList1Response200) & {
  headers: Headers;
};
;

export type getStoreNewsList1Response = (getStoreNewsList1ResponseSuccess)

export const getGetStoreNewsList1Url = (storeId: number,
    params: GetStoreNewsList1Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/owner/stores/${storeId}/news?${stringifiedParams}` : `/api/owner/stores/${storeId}/news`
}

export const getStoreNewsList1 = async (storeId: number,
    params: GetStoreNewsList1Params, options?: RequestInit): Promise<getStoreNewsList1Response> => {
  
  return customFetch<getStoreNewsList1Response>(getGetStoreNewsList1Url(storeId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoreNewsList1QueryKey = (storeId?: number,
    params?: GetStoreNewsList1Params,) => {
    return [
    `/api/owner/stores/${storeId}/news`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetStoreNewsList1QueryOptions = <TData = Awaited<ReturnType<typeof getStoreNewsList1>>, TError = unknown>(storeId: number,
    params: GetStoreNewsList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNewsList1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoreNewsList1QueryKey(storeId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoreNewsList1>>> = ({ signal }) => getStoreNewsList1(storeId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoreNewsList1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoreNewsList1QueryResult = NonNullable<Awaited<ReturnType<typeof getStoreNewsList1>>>
export type GetStoreNewsList1QueryError = unknown


export function useGetStoreNewsList1<TData = Awaited<ReturnType<typeof getStoreNewsList1>>, TError = unknown>(
 storeId: number,
    params: GetStoreNewsList1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNewsList1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreNewsList1>>,
          TError,
          Awaited<ReturnType<typeof getStoreNewsList1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreNewsList1<TData = Awaited<ReturnType<typeof getStoreNewsList1>>, TError = unknown>(
 storeId: number,
    params: GetStoreNewsList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNewsList1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreNewsList1>>,
          TError,
          Awaited<ReturnType<typeof getStoreNewsList1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreNewsList1<TData = Awaited<ReturnType<typeof getStoreNewsList1>>, TError = unknown>(
 storeId: number,
    params: GetStoreNewsList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNewsList1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 소식 목록 조회
 */

export function useGetStoreNewsList1<TData = Awaited<ReturnType<typeof getStoreNewsList1>>, TError = unknown>(
 storeId: number,
    params: GetStoreNewsList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNewsList1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoreNewsList1QueryOptions(storeId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 가게에 새로운 소식을 등록합니다.
 * @summary [점주] 소식 등록
 */
export type createStoreNews1Response201 = {
  data: CommonResponseLong
  status: 201
}

export type createStoreNews1Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type createStoreNews1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type createStoreNews1ResponseSuccess = (createStoreNews1Response201) & {
  headers: Headers;
};
export type createStoreNews1ResponseError = (createStoreNews1Response403 | createStoreNews1Response404) & {
  headers: Headers;
};

export type createStoreNews1Response = (createStoreNews1ResponseSuccess | createStoreNews1ResponseError)

export const getCreateStoreNews1Url = (storeId: number,) => {


  

  return `/api/owner/stores/${storeId}/news`
}

export const createStoreNews1 = async (storeId: number,
    createStoreNewsRequest: CreateStoreNewsRequest, options?: RequestInit): Promise<createStoreNews1Response> => {
  
  return customFetch<createStoreNews1Response>(getCreateStoreNews1Url(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStoreNewsRequest,)
  }
);}




export const getCreateStoreNews1MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStoreNews1>>, TError,{storeId: number;data: CreateStoreNewsRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createStoreNews1>>, TError,{storeId: number;data: CreateStoreNewsRequest}, TContext> => {

const mutationKey = ['createStoreNews1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStoreNews1>>, {storeId: number;data: CreateStoreNewsRequest}> = (props) => {
          const {storeId,data} = props ?? {};

          return  createStoreNews1(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStoreNews1MutationResult = NonNullable<Awaited<ReturnType<typeof createStoreNews1>>>
    export type CreateStoreNews1MutationBody = CreateStoreNewsRequest
    export type CreateStoreNews1MutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 소식 등록
 */
export const useCreateStoreNews1 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStoreNews1>>, TError,{storeId: number;data: CreateStoreNewsRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStoreNews1>>,
        TError,
        {storeId: number;data: CreateStoreNewsRequest},
        TContext
      > => {
      return useMutation(getCreateStoreNews1MutationOptions(options), queryClient);
    }
    /**
 * 소식에 좋아요를 누르거나 취소합니다.
 * @summary [점주] 소식 좋아요 토글
 */
export type toggleLike2Response200 = {
  data: CommonResponseVoid
  status: 200
}

export type toggleLike2Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type toggleLike2ResponseSuccess = (toggleLike2Response200) & {
  headers: Headers;
};
export type toggleLike2ResponseError = (toggleLike2Response404) & {
  headers: Headers;
};

export type toggleLike2Response = (toggleLike2ResponseSuccess | toggleLike2ResponseError)

export const getToggleLike2Url = (newsId: number,) => {


  

  return `/api/owner/store-news/${newsId}/likes`
}

export const toggleLike2 = async (newsId: number, options?: RequestInit): Promise<toggleLike2Response> => {
  
  return customFetch<toggleLike2Response>(getToggleLike2Url(newsId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getToggleLike2MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleLike2>>, TError,{newsId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof toggleLike2>>, TError,{newsId: number}, TContext> => {

const mutationKey = ['toggleLike2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleLike2>>, {newsId: number}> = (props) => {
          const {newsId} = props ?? {};

          return  toggleLike2(newsId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleLike2MutationResult = NonNullable<Awaited<ReturnType<typeof toggleLike2>>>
    
    export type ToggleLike2MutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 소식 좋아요 토글
 */
export const useToggleLike2 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleLike2>>, TError,{newsId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleLike2>>,
        TError,
        {newsId: number},
        TContext
      > => {
      return useMutation(getToggleLike2MutationOptions(options), queryClient);
    }
    /**
 * 소식의 댓글 목록을 조회합니다.
 * @summary [점주] 댓글 목록 조회
 */
export type getComments2Response200 = {
  data: CommonResponsePageResponseStoreNewsCommentResponse
  status: 200
}
    
export type getComments2ResponseSuccess = (getComments2Response200) & {
  headers: Headers;
};
;

export type getComments2Response = (getComments2ResponseSuccess)

export const getGetComments2Url = (newsId: number,
    params: GetComments2Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/owner/store-news/${newsId}/comments?${stringifiedParams}` : `/api/owner/store-news/${newsId}/comments`
}

export const getComments2 = async (newsId: number,
    params: GetComments2Params, options?: RequestInit): Promise<getComments2Response> => {
  
  return customFetch<getComments2Response>(getGetComments2Url(newsId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetComments2QueryKey = (newsId?: number,
    params?: GetComments2Params,) => {
    return [
    `/api/owner/store-news/${newsId}/comments`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetComments2QueryOptions = <TData = Awaited<ReturnType<typeof getComments2>>, TError = unknown>(newsId: number,
    params: GetComments2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComments2QueryKey(newsId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComments2>>> = ({ signal }) => getComments2(newsId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(newsId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComments2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComments2QueryResult = NonNullable<Awaited<ReturnType<typeof getComments2>>>
export type GetComments2QueryError = unknown


export function useGetComments2<TData = Awaited<ReturnType<typeof getComments2>>, TError = unknown>(
 newsId: number,
    params: GetComments2Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComments2>>,
          TError,
          Awaited<ReturnType<typeof getComments2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComments2<TData = Awaited<ReturnType<typeof getComments2>>, TError = unknown>(
 newsId: number,
    params: GetComments2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComments2>>,
          TError,
          Awaited<ReturnType<typeof getComments2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComments2<TData = Awaited<ReturnType<typeof getComments2>>, TError = unknown>(
 newsId: number,
    params: GetComments2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 댓글 목록 조회
 */

export function useGetComments2<TData = Awaited<ReturnType<typeof getComments2>>, TError = unknown>(
 newsId: number,
    params: GetComments2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComments2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComments2QueryOptions(newsId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 소식에 댓글을 작성합니다.
 * @summary [점주] 댓글 작성
 */
export type createComment2Response201 = {
  data: CommonResponseLong
  status: 201
}

export type createComment2Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type createComment2ResponseSuccess = (createComment2Response201) & {
  headers: Headers;
};
export type createComment2ResponseError = (createComment2Response404) & {
  headers: Headers;
};

export type createComment2Response = (createComment2ResponseSuccess | createComment2ResponseError)

export const getCreateComment2Url = (newsId: number,) => {


  

  return `/api/owner/store-news/${newsId}/comments`
}

export const createComment2 = async (newsId: number,
    createStoreNewsCommentRequest: CreateStoreNewsCommentRequest, options?: RequestInit): Promise<createComment2Response> => {
  
  return customFetch<createComment2Response>(getCreateComment2Url(newsId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStoreNewsCommentRequest,)
  }
);}




export const getCreateComment2MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComment2>>, TError,{newsId: number;data: CreateStoreNewsCommentRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createComment2>>, TError,{newsId: number;data: CreateStoreNewsCommentRequest}, TContext> => {

const mutationKey = ['createComment2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createComment2>>, {newsId: number;data: CreateStoreNewsCommentRequest}> = (props) => {
          const {newsId,data} = props ?? {};

          return  createComment2(newsId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateComment2MutationResult = NonNullable<Awaited<ReturnType<typeof createComment2>>>
    export type CreateComment2MutationBody = CreateStoreNewsCommentRequest
    export type CreateComment2MutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 댓글 작성
 */
export const useCreateComment2 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComment2>>, TError,{newsId: number;data: CreateStoreNewsCommentRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createComment2>>,
        TError,
        {newsId: number;data: CreateStoreNewsCommentRequest},
        TContext
      > => {
      return useMutation(getCreateComment2MutationOptions(options), queryClient);
    }
    /**
 * 소식 상세 정보를 조회합니다.
 * @summary [점주] 소식 상세 조회
 */
export type getStoreNews1Response200 = {
  data: CommonResponseStoreNewsResponse
  status: 200
}
    
export type getStoreNews1ResponseSuccess = (getStoreNews1Response200) & {
  headers: Headers;
};
;

export type getStoreNews1Response = (getStoreNews1ResponseSuccess)

export const getGetStoreNews1Url = (newsId: number,) => {


  

  return `/api/owner/store-news/${newsId}`
}

export const getStoreNews1 = async (newsId: number, options?: RequestInit): Promise<getStoreNews1Response> => {
  
  return customFetch<getStoreNews1Response>(getGetStoreNews1Url(newsId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoreNews1QueryKey = (newsId?: number,) => {
    return [
    `/api/owner/store-news/${newsId}`
    ] as const;
    }

    
export const getGetStoreNews1QueryOptions = <TData = Awaited<ReturnType<typeof getStoreNews1>>, TError = unknown>(newsId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNews1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoreNews1QueryKey(newsId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoreNews1>>> = ({ signal }) => getStoreNews1(newsId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(newsId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoreNews1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoreNews1QueryResult = NonNullable<Awaited<ReturnType<typeof getStoreNews1>>>
export type GetStoreNews1QueryError = unknown


export function useGetStoreNews1<TData = Awaited<ReturnType<typeof getStoreNews1>>, TError = unknown>(
 newsId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNews1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreNews1>>,
          TError,
          Awaited<ReturnType<typeof getStoreNews1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreNews1<TData = Awaited<ReturnType<typeof getStoreNews1>>, TError = unknown>(
 newsId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNews1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreNews1>>,
          TError,
          Awaited<ReturnType<typeof getStoreNews1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreNews1<TData = Awaited<ReturnType<typeof getStoreNews1>>, TError = unknown>(
 newsId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNews1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 소식 상세 조회
 */

export function useGetStoreNews1<TData = Awaited<ReturnType<typeof getStoreNews1>>, TError = unknown>(
 newsId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreNews1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoreNews1QueryOptions(newsId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 소식을 삭제합니다.
 * @summary [점주] 소식 삭제
 */
export type deleteStoreNews1Response204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteStoreNews1Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteStoreNews1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteStoreNews1ResponseSuccess = (deleteStoreNews1Response204) & {
  headers: Headers;
};
export type deleteStoreNews1ResponseError = (deleteStoreNews1Response403 | deleteStoreNews1Response404) & {
  headers: Headers;
};

export type deleteStoreNews1Response = (deleteStoreNews1ResponseSuccess | deleteStoreNews1ResponseError)

export const getDeleteStoreNews1Url = (newsId: number,) => {


  

  return `/api/owner/store-news/${newsId}`
}

export const deleteStoreNews1 = async (newsId: number, options?: RequestInit): Promise<deleteStoreNews1Response> => {
  
  return customFetch<deleteStoreNews1Response>(getDeleteStoreNews1Url(newsId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteStoreNews1MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStoreNews1>>, TError,{newsId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStoreNews1>>, TError,{newsId: number}, TContext> => {

const mutationKey = ['deleteStoreNews1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStoreNews1>>, {newsId: number}> = (props) => {
          const {newsId} = props ?? {};

          return  deleteStoreNews1(newsId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStoreNews1MutationResult = NonNullable<Awaited<ReturnType<typeof deleteStoreNews1>>>
    
    export type DeleteStoreNews1MutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 소식 삭제
 */
export const useDeleteStoreNews1 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStoreNews1>>, TError,{newsId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStoreNews1>>,
        TError,
        {newsId: number},
        TContext
      > => {
      return useMutation(getDeleteStoreNews1MutationOptions(options), queryClient);
    }
    /**
 * 소식을 수정합니다.
 * @summary [점주] 소식 수정
 */
export type updateStoreNews1Response200 = {
  data: CommonResponseVoid
  status: 200
}

export type updateStoreNews1Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updateStoreNews1Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type updateStoreNews1ResponseSuccess = (updateStoreNews1Response200) & {
  headers: Headers;
};
export type updateStoreNews1ResponseError = (updateStoreNews1Response403 | updateStoreNews1Response404) & {
  headers: Headers;
};

export type updateStoreNews1Response = (updateStoreNews1ResponseSuccess | updateStoreNews1ResponseError)

export const getUpdateStoreNews1Url = (newsId: number,) => {


  

  return `/api/owner/store-news/${newsId}`
}

export const updateStoreNews1 = async (newsId: number,
    updateStoreNewsRequest: UpdateStoreNewsRequest, options?: RequestInit): Promise<updateStoreNews1Response> => {
  
  return customFetch<updateStoreNews1Response>(getUpdateStoreNews1Url(newsId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStoreNewsRequest,)
  }
);}




export const getUpdateStoreNews1MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStoreNews1>>, TError,{newsId: number;data: UpdateStoreNewsRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStoreNews1>>, TError,{newsId: number;data: UpdateStoreNewsRequest}, TContext> => {

const mutationKey = ['updateStoreNews1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStoreNews1>>, {newsId: number;data: UpdateStoreNewsRequest}> = (props) => {
          const {newsId,data} = props ?? {};

          return  updateStoreNews1(newsId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStoreNews1MutationResult = NonNullable<Awaited<ReturnType<typeof updateStoreNews1>>>
    export type UpdateStoreNews1MutationBody = UpdateStoreNewsRequest
    export type UpdateStoreNews1MutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 소식 수정
 */
export const useUpdateStoreNews1 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStoreNews1>>, TError,{newsId: number;data: UpdateStoreNewsRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStoreNews1>>,
        TError,
        {newsId: number;data: UpdateStoreNewsRequest},
        TContext
      > => {
      return useMutation(getUpdateStoreNews1MutationOptions(options), queryClient);
    }
    /**
 * 자신의 댓글을 삭제합니다.
 * @summary [점주] 댓글 삭제
 */
export type deleteComment2Response204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteComment2Response403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteComment2Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteComment2ResponseSuccess = (deleteComment2Response204) & {
  headers: Headers;
};
export type deleteComment2ResponseError = (deleteComment2Response403 | deleteComment2Response404) & {
  headers: Headers;
};

export type deleteComment2Response = (deleteComment2ResponseSuccess | deleteComment2ResponseError)

export const getDeleteComment2Url = (newsId: number,
    commentId: number,) => {


  

  return `/api/owner/store-news/${newsId}/comments/${commentId}`
}

export const deleteComment2 = async (newsId: number,
    commentId: number, options?: RequestInit): Promise<deleteComment2Response> => {
  
  return customFetch<deleteComment2Response>(getDeleteComment2Url(newsId,commentId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteComment2MutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComment2>>, TError,{newsId: number;commentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteComment2>>, TError,{newsId: number;commentId: number}, TContext> => {

const mutationKey = ['deleteComment2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteComment2>>, {newsId: number;commentId: number}> = (props) => {
          const {newsId,commentId} = props ?? {};

          return  deleteComment2(newsId,commentId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteComment2MutationResult = NonNullable<Awaited<ReturnType<typeof deleteComment2>>>
    
    export type DeleteComment2MutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 댓글 삭제
 */
export const useDeleteComment2 = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComment2>>, TError,{newsId: number;commentId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteComment2>>,
        TError,
        {newsId: number;commentId: number},
        TContext
      > => {
      return useMutation(getDeleteComment2MutationOptions(options), queryClient);
    }
    