/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseOwnerInfoResponse,
  SwaggerErrorResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 점주의 이름, 이메일, 아이디, 성별, 생년월일을 조회합니다.
 * @summary [점주] 내 정보 조회
 */
export type getOwnerInfoResponse200 = {
  data: CommonResponseOwnerInfoResponse
  status: 200
}

export type getOwnerInfoResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type getOwnerInfoResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getOwnerInfoResponseSuccess = (getOwnerInfoResponse200) & {
  headers: Headers;
};
export type getOwnerInfoResponseError = (getOwnerInfoResponse403 | getOwnerInfoResponse404) & {
  headers: Headers;
};

export type getOwnerInfoResponse = (getOwnerInfoResponseSuccess | getOwnerInfoResponseError)

export const getGetOwnerInfoUrl = () => {


  

  return `/api/owner/profile`
}

export const getOwnerInfo = async ( options?: RequestInit): Promise<getOwnerInfoResponse> => {
  
  return customFetch<getOwnerInfoResponse>(getGetOwnerInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetOwnerInfoQueryKey = () => {
    return [
    `/api/owner/profile`
    ] as const;
    }

    
export const getGetOwnerInfoQueryOptions = <TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = SwaggerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOwnerInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOwnerInfo>>> = ({ signal }) => getOwnerInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOwnerInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getOwnerInfo>>>
export type GetOwnerInfoQueryError = SwaggerErrorResponse


export function useGetOwnerInfo<TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = SwaggerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnerInfo>>,
          TError,
          Awaited<ReturnType<typeof getOwnerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOwnerInfo<TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnerInfo>>,
          TError,
          Awaited<ReturnType<typeof getOwnerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOwnerInfo<TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 내 정보 조회
 */

export function useGetOwnerInfo<TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOwnerInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




