/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseListUniversityResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 전체 대학 목록을 조회합니다.
 * @summary [공통] 대학 목록 조회
 */
export type getUniversitiesResponse200 = {
  data: CommonResponseListUniversityResponse
  status: 200
}
    
export type getUniversitiesResponseSuccess = (getUniversitiesResponse200) & {
  headers: Headers;
};
;

export type getUniversitiesResponse = (getUniversitiesResponseSuccess)

export const getGetUniversitiesUrl = () => {


  

  return `/api/universities`
}

export const getUniversities = async ( options?: RequestInit): Promise<getUniversitiesResponse> => {
  
  return customFetch<getUniversitiesResponse>(getGetUniversitiesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUniversitiesQueryKey = () => {
    return [
    `/api/universities`
    ] as const;
    }

    
export const getGetUniversitiesQueryOptions = <TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUniversitiesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUniversities>>> = ({ signal }) => getUniversities({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUniversitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getUniversities>>>
export type GetUniversitiesQueryError = unknown


export function useGetUniversities<TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUniversities>>,
          TError,
          Awaited<ReturnType<typeof getUniversities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUniversities<TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUniversities>>,
          TError,
          Awaited<ReturnType<typeof getUniversities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUniversities<TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 대학 목록 조회
 */

export function useGetUniversities<TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUniversitiesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




