/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BizVerificationRequest,
  CommonResponseBizVerificationResponse,
  CommonResponseListMyStoreClaimResponse,
  CommonResponseListStoreResponse,
  CommonResponseLong,
  SearchUnclaimedStoresParams,
  StoreClaimRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 사장님이 상점에 대해 소유를 요청하여 심사 대상이 됩니다.
 * @deprecated
 * @summary [점주] 상점 소유 요청 등록
 */
export type createStoreClaimsResponse200 = {
  data: CommonResponseLong
  status: 200
}
    
export type createStoreClaimsResponseSuccess = (createStoreClaimsResponse200) & {
  headers: Headers;
};
;

export type createStoreClaimsResponse = (createStoreClaimsResponseSuccess)

export const getCreateStoreClaimsUrl = () => {


  

  return `/api/store-claims`
}

export const createStoreClaims = async (storeClaimRequest: StoreClaimRequest, options?: RequestInit): Promise<createStoreClaimsResponse> => {
  
  return customFetch<createStoreClaimsResponse>(getCreateStoreClaimsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeClaimRequest,)
  }
);}




export const getCreateStoreClaimsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStoreClaims>>, TError,{data: StoreClaimRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createStoreClaims>>, TError,{data: StoreClaimRequest}, TContext> => {

const mutationKey = ['createStoreClaims'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStoreClaims>>, {data: StoreClaimRequest}> = (props) => {
          const {data} = props ?? {};

          return  createStoreClaims(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStoreClaimsMutationResult = NonNullable<Awaited<ReturnType<typeof createStoreClaims>>>
    export type CreateStoreClaimsMutationBody = StoreClaimRequest
    export type CreateStoreClaimsMutationError = unknown

    /**
 * @deprecated
 * @summary [점주] 상점 소유 요청 등록
 */
export const useCreateStoreClaims = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStoreClaims>>, TError,{data: StoreClaimRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStoreClaims>>,
        TError,
        {data: StoreClaimRequest},
        TContext
      > => {
      return useMutation(getCreateStoreClaimsMutationOptions(options), queryClient);
    }
    /**
 * 사업자등록번호의 유효성을 검증합니다.
 * @deprecated
 * @summary [점주] 사업자등록번호 유효성 검증
 */
export type verifyBizRegNo1Response200 = {
  data: CommonResponseBizVerificationResponse
  status: 200
}
    
export type verifyBizRegNo1ResponseSuccess = (verifyBizRegNo1Response200) & {
  headers: Headers;
};
;

export type verifyBizRegNo1Response = (verifyBizRegNo1ResponseSuccess)

export const getVerifyBizRegNo1Url = () => {


  

  return `/api/biz-reg-no/verify`
}

export const verifyBizRegNo1 = async (bizVerificationRequest: BizVerificationRequest, options?: RequestInit): Promise<verifyBizRegNo1Response> => {
  
  return customFetch<verifyBizRegNo1Response>(getVerifyBizRegNo1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bizVerificationRequest,)
  }
);}




export const getVerifyBizRegNo1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyBizRegNo1>>, TError,{data: BizVerificationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyBizRegNo1>>, TError,{data: BizVerificationRequest}, TContext> => {

const mutationKey = ['verifyBizRegNo1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyBizRegNo1>>, {data: BizVerificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  verifyBizRegNo1(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyBizRegNo1MutationResult = NonNullable<Awaited<ReturnType<typeof verifyBizRegNo1>>>
    export type VerifyBizRegNo1MutationBody = BizVerificationRequest
    export type VerifyBizRegNo1MutationError = unknown

    /**
 * @deprecated
 * @summary [점주] 사업자등록번호 유효성 검증
 */
export const useVerifyBizRegNo1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyBizRegNo1>>, TError,{data: BizVerificationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyBizRegNo1>>,
        TError,
        {data: BizVerificationRequest},
        TContext
      > => {
      return useMutation(getVerifyBizRegNo1MutationOptions(options), queryClient);
    }
    /**
 * 시스템에 등록된 미등록 상점을 이름 또는 주소로 검색합니다.
 * @deprecated
 * @summary [점주] 미등록 상점 검색
 */
export type searchUnclaimedStoresResponse200 = {
  data: CommonResponseListStoreResponse
  status: 200
}
    
export type searchUnclaimedStoresResponseSuccess = (searchUnclaimedStoresResponse200) & {
  headers: Headers;
};
;

export type searchUnclaimedStoresResponse = (searchUnclaimedStoresResponseSuccess)

export const getSearchUnclaimedStoresUrl = (params: SearchUnclaimedStoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/store-claims/search?${stringifiedParams}` : `/api/store-claims/search`
}

export const searchUnclaimedStores = async (params: SearchUnclaimedStoresParams, options?: RequestInit): Promise<searchUnclaimedStoresResponse> => {
  
  return customFetch<searchUnclaimedStoresResponse>(getSearchUnclaimedStoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSearchUnclaimedStoresQueryKey = (params?: SearchUnclaimedStoresParams,) => {
    return [
    `/api/store-claims/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchUnclaimedStoresQueryOptions = <TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(params: SearchUnclaimedStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchUnclaimedStoresQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchUnclaimedStores>>> = ({ signal }) => searchUnclaimedStores(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchUnclaimedStoresQueryResult = NonNullable<Awaited<ReturnType<typeof searchUnclaimedStores>>>
export type SearchUnclaimedStoresQueryError = unknown


export function useSearchUnclaimedStores<TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(
 params: SearchUnclaimedStoresParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchUnclaimedStores>>,
          TError,
          Awaited<ReturnType<typeof searchUnclaimedStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchUnclaimedStores<TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(
 params: SearchUnclaimedStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchUnclaimedStores>>,
          TError,
          Awaited<ReturnType<typeof searchUnclaimedStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchUnclaimedStores<TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(
 params: SearchUnclaimedStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary [점주] 미등록 상점 검색
 */

export function useSearchUnclaimedStores<TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(
 params: SearchUnclaimedStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchUnclaimedStoresQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 점주가 자신이 신청한 상점 소유 요청 목록을 조회합니다.
 * @deprecated
 * @summary [점주] 내 상점 소유 요청 목록 조회
 */
export type getMyStoreClaims1Response200 = {
  data: CommonResponseListMyStoreClaimResponse
  status: 200
}
    
export type getMyStoreClaims1ResponseSuccess = (getMyStoreClaims1Response200) & {
  headers: Headers;
};
;

export type getMyStoreClaims1Response = (getMyStoreClaims1ResponseSuccess)

export const getGetMyStoreClaims1Url = () => {


  

  return `/api/store-claims/my`
}

export const getMyStoreClaims1 = async ( options?: RequestInit): Promise<getMyStoreClaims1Response> => {
  
  return customFetch<getMyStoreClaims1Response>(getGetMyStoreClaims1Url(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyStoreClaims1QueryKey = () => {
    return [
    `/api/store-claims/my`
    ] as const;
    }

    
export const getGetMyStoreClaims1QueryOptions = <TData = Awaited<ReturnType<typeof getMyStoreClaims1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStoreClaims1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyStoreClaims1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyStoreClaims1>>> = ({ signal }) => getMyStoreClaims1({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyStoreClaims1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyStoreClaims1QueryResult = NonNullable<Awaited<ReturnType<typeof getMyStoreClaims1>>>
export type GetMyStoreClaims1QueryError = unknown


export function useGetMyStoreClaims1<TData = Awaited<ReturnType<typeof getMyStoreClaims1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStoreClaims1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyStoreClaims1>>,
          TError,
          Awaited<ReturnType<typeof getMyStoreClaims1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyStoreClaims1<TData = Awaited<ReturnType<typeof getMyStoreClaims1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStoreClaims1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyStoreClaims1>>,
          TError,
          Awaited<ReturnType<typeof getMyStoreClaims1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyStoreClaims1<TData = Awaited<ReturnType<typeof getMyStoreClaims1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStoreClaims1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary [점주] 내 상점 소유 요청 목록 조회
 */

export function useGetMyStoreClaims1<TData = Awaited<ReturnType<typeof getMyStoreClaims1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStoreClaims1>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyStoreClaims1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




