/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseItemResponse,
  CommonResponseListItemResponse,
  SwaggerErrorResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 특정 상점의 모든 상품을 조회합니다.
 * @summary [학생] 상점별 상품 목록 조회
 */
export type getItems3Response200 = {
  data: CommonResponseListItemResponse
  status: 200
}

export type getItems3Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getItems3ResponseSuccess = (getItems3Response200) & {
  headers: Headers;
};
export type getItems3ResponseError = (getItems3Response404) & {
  headers: Headers;
};

export type getItems3Response = (getItems3ResponseSuccess | getItems3ResponseError)

export const getGetItems3Url = (storeId: number,) => {


  

  return `/api/student/stores/${storeId}/items`
}

export const getItems3 = async (storeId: number, options?: RequestInit): Promise<getItems3Response> => {
  
  return customFetch<getItems3Response>(getGetItems3Url(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetItems3QueryKey = (storeId?: number,) => {
    return [
    `/api/student/stores/${storeId}/items`
    ] as const;
    }

    
export const getGetItems3QueryOptions = <TData = Awaited<ReturnType<typeof getItems3>>, TError = SwaggerErrorResponse>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItems3QueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItems3>>> = ({ signal }) => getItems3(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItems3>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItems3QueryResult = NonNullable<Awaited<ReturnType<typeof getItems3>>>
export type GetItems3QueryError = SwaggerErrorResponse


export function useGetItems3<TData = Awaited<ReturnType<typeof getItems3>>, TError = SwaggerErrorResponse>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems3>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems3>>,
          TError,
          Awaited<ReturnType<typeof getItems3>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems3<TData = Awaited<ReturnType<typeof getItems3>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems3>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems3>>,
          TError,
          Awaited<ReturnType<typeof getItems3>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems3<TData = Awaited<ReturnType<typeof getItems3>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 상점별 상품 목록 조회
 */

export function useGetItems3<TData = Awaited<ReturnType<typeof getItems3>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItems3QueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상품 ID로 상품의 상세 정보를 조회합니다.
 * @summary [학생] 상품 단건 조회
 */
export type getItem3Response200 = {
  data: CommonResponseItemResponse
  status: 200
}

export type getItem3Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getItem3ResponseSuccess = (getItem3Response200) & {
  headers: Headers;
};
export type getItem3ResponseError = (getItem3Response404) & {
  headers: Headers;
};

export type getItem3Response = (getItem3ResponseSuccess | getItem3ResponseError)

export const getGetItem3Url = (itemId: number,) => {


  

  return `/api/student/items/${itemId}`
}

export const getItem3 = async (itemId: number, options?: RequestInit): Promise<getItem3Response> => {
  
  return customFetch<getItem3Response>(getGetItem3Url(itemId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetItem3QueryKey = (itemId?: number,) => {
    return [
    `/api/student/items/${itemId}`
    ] as const;
    }

    
export const getGetItem3QueryOptions = <TData = Awaited<ReturnType<typeof getItem3>>, TError = SwaggerErrorResponse>(itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItem3QueryKey(itemId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItem3>>> = ({ signal }) => getItem3(itemId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(itemId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItem3>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItem3QueryResult = NonNullable<Awaited<ReturnType<typeof getItem3>>>
export type GetItem3QueryError = SwaggerErrorResponse


export function useGetItem3<TData = Awaited<ReturnType<typeof getItem3>>, TError = SwaggerErrorResponse>(
 itemId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem3>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem3>>,
          TError,
          Awaited<ReturnType<typeof getItem3>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem3<TData = Awaited<ReturnType<typeof getItem3>>, TError = SwaggerErrorResponse>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem3>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem3>>,
          TError,
          Awaited<ReturnType<typeof getItem3>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem3<TData = Awaited<ReturnType<typeof getItem3>>, TError = SwaggerErrorResponse>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 상품 단건 조회
 */

export function useGetItem3<TData = Awaited<ReturnType<typeof getItem3>>, TError = SwaggerErrorResponse>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItem3QueryOptions(itemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




