/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseListItemCategoryResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 매장의 상품 카테고리 목록을 조회합니다.
 * @summary [학생] 상품 카테고리 목록 조회
 */
export type getItemCategories3Response200 = {
  data: CommonResponseListItemCategoryResponse
  status: 200
}
    
export type getItemCategories3ResponseSuccess = (getItemCategories3Response200) & {
  headers: Headers;
};
;

export type getItemCategories3Response = (getItemCategories3ResponseSuccess)

export const getGetItemCategories3Url = (storeId: number,) => {


  

  return `/api/student/stores/${storeId}/item-categories`
}

export const getItemCategories3 = async (storeId: number, options?: RequestInit): Promise<getItemCategories3Response> => {
  
  return customFetch<getItemCategories3Response>(getGetItemCategories3Url(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetItemCategories3QueryKey = (storeId?: number,) => {
    return [
    `/api/student/stores/${storeId}/item-categories`
    ] as const;
    }

    
export const getGetItemCategories3QueryOptions = <TData = Awaited<ReturnType<typeof getItemCategories3>>, TError = unknown>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemCategories3QueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItemCategories3>>> = ({ signal }) => getItemCategories3(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItemCategories3>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemCategories3QueryResult = NonNullable<Awaited<ReturnType<typeof getItemCategories3>>>
export type GetItemCategories3QueryError = unknown


export function useGetItemCategories3<TData = Awaited<ReturnType<typeof getItemCategories3>>, TError = unknown>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories3>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemCategories3>>,
          TError,
          Awaited<ReturnType<typeof getItemCategories3>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemCategories3<TData = Awaited<ReturnType<typeof getItemCategories3>>, TError = unknown>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories3>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemCategories3>>,
          TError,
          Awaited<ReturnType<typeof getItemCategories3>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemCategories3<TData = Awaited<ReturnType<typeof getItemCategories3>>, TError = unknown>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 상품 카테고리 목록 조회
 */

export function useGetItemCategories3<TData = Awaited<ReturnType<typeof getItemCategories3>>, TError = unknown>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories3>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemCategories3QueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




