/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseListHotStoreResponse,
  CommonResponseListStudentStoreMapResponse,
  CommonResponseListStudentStoreResponse,
  CommonResponsePageResponseStudentStoreResponse,
  CommonResponseStudentStoreResponse,
  CommonResponseVoid,
  GetNearbyStoresParams,
  GetStoreMapParams,
  GetStores2Params,
  GetStoresByLocationParams,
  StoreReportRequest,
  SwaggerErrorResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 특정 상점을 신고합니다.
 * @summary [학생] 상점 신고
 */
export type reportStoreResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type reportStoreResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type reportStoreResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type reportStoreResponseSuccess = (reportStoreResponse200) & {
  headers: Headers;
};
export type reportStoreResponseError = (reportStoreResponse404 | reportStoreResponse409) & {
  headers: Headers;
};

export type reportStoreResponse = (reportStoreResponseSuccess | reportStoreResponseError)

export const getReportStoreUrl = (storeId: number,) => {


  

  return `/api/student/stores/${storeId}/reports`
}

export const reportStore = async (storeId: number,
    storeReportRequest: StoreReportRequest, options?: RequestInit): Promise<reportStoreResponse> => {
  
  return customFetch<reportStoreResponse>(getReportStoreUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeReportRequest,)
  }
);}




export const getReportStoreMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportStore>>, TError,{storeId: number;data: StoreReportRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reportStore>>, TError,{storeId: number;data: StoreReportRequest}, TContext> => {

const mutationKey = ['reportStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportStore>>, {storeId: number;data: StoreReportRequest}> = (props) => {
          const {storeId,data} = props ?? {};

          return  reportStore(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ReportStoreMutationResult = NonNullable<Awaited<ReturnType<typeof reportStore>>>
    export type ReportStoreMutationBody = StoreReportRequest
    export type ReportStoreMutationError = SwaggerErrorResponse

    /**
 * @summary [학생] 상점 신고
 */
export const useReportStore = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportStore>>, TError,{storeId: number;data: StoreReportRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reportStore>>,
        TError,
        {storeId: number;data: StoreReportRequest},
        TContext
      > => {
      return useMutation(getReportStoreMutationOptions(options), queryClient);
    }
    /**
 * 전체 상점 목록을 페이징하여 조회합니다.
 * @summary [학생] 상점 목록 조회
 */
export type getStores2Response200 = {
  data: CommonResponsePageResponseStudentStoreResponse
  status: 200
}
    
export type getStores2ResponseSuccess = (getStores2Response200) & {
  headers: Headers;
};
;

export type getStores2Response = (getStores2ResponseSuccess)

export const getGetStores2Url = (params: GetStores2Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/student/stores?${stringifiedParams}` : `/api/student/stores`
}

export const getStores2 = async (params: GetStores2Params, options?: RequestInit): Promise<getStores2Response> => {
  
  return customFetch<getStores2Response>(getGetStores2Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStores2QueryKey = (params?: GetStores2Params,) => {
    return [
    `/api/student/stores`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetStores2QueryOptions = <TData = Awaited<ReturnType<typeof getStores2>>, TError = unknown>(params: GetStores2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStores2QueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStores2>>> = ({ signal }) => getStores2(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStores2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStores2QueryResult = NonNullable<Awaited<ReturnType<typeof getStores2>>>
export type GetStores2QueryError = unknown


export function useGetStores2<TData = Awaited<ReturnType<typeof getStores2>>, TError = unknown>(
 params: GetStores2Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStores2>>,
          TError,
          Awaited<ReturnType<typeof getStores2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStores2<TData = Awaited<ReturnType<typeof getStores2>>, TError = unknown>(
 params: GetStores2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStores2>>,
          TError,
          Awaited<ReturnType<typeof getStores2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStores2<TData = Awaited<ReturnType<typeof getStores2>>, TError = unknown>(
 params: GetStores2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 상점 목록 조회
 */

export function useGetStores2<TData = Awaited<ReturnType<typeof getStores2>>, TError = unknown>(
 params: GetStores2Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStores2QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상점 ID로 상세 정보와 나의 파트너십 혜택을 조회합니다.
 * @summary [학생] 상점 단건 조회
 */
export type getStore2Response200 = {
  data: CommonResponseStudentStoreResponse
  status: 200
}

export type getStore2Response404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getStore2ResponseSuccess = (getStore2Response200) & {
  headers: Headers;
};
export type getStore2ResponseError = (getStore2Response404) & {
  headers: Headers;
};

export type getStore2Response = (getStore2ResponseSuccess | getStore2ResponseError)

export const getGetStore2Url = (storeId: number,) => {


  

  return `/api/student/stores/${storeId}`
}

export const getStore2 = async (storeId: number, options?: RequestInit): Promise<getStore2Response> => {
  
  return customFetch<getStore2Response>(getGetStore2Url(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStore2QueryKey = (storeId?: number,) => {
    return [
    `/api/student/stores/${storeId}`
    ] as const;
    }

    
export const getGetStore2QueryOptions = <TData = Awaited<ReturnType<typeof getStore2>>, TError = SwaggerErrorResponse>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStore2QueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStore2>>> = ({ signal }) => getStore2(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStore2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStore2QueryResult = NonNullable<Awaited<ReturnType<typeof getStore2>>>
export type GetStore2QueryError = SwaggerErrorResponse


export function useGetStore2<TData = Awaited<ReturnType<typeof getStore2>>, TError = SwaggerErrorResponse>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStore2>>,
          TError,
          Awaited<ReturnType<typeof getStore2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStore2<TData = Awaited<ReturnType<typeof getStore2>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStore2>>,
          TError,
          Awaited<ReturnType<typeof getStore2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStore2<TData = Awaited<ReturnType<typeof getStore2>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 상점 단건 조회
 */

export function useGetStore2<TData = Awaited<ReturnType<typeof getStore2>>, TError = SwaggerErrorResponse>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore2>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStore2QueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 위도, 경도, 반경(km)을 기준으로 주변 상점을 조회합니다.
 * @summary [학생] 주변 상점 조회
 */
export type getNearbyStoresResponse200 = {
  data: CommonResponseListStudentStoreResponse
  status: 200
}
    
export type getNearbyStoresResponseSuccess = (getNearbyStoresResponse200) & {
  headers: Headers;
};
;

export type getNearbyStoresResponse = (getNearbyStoresResponseSuccess)

export const getGetNearbyStoresUrl = (params: GetNearbyStoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/student/stores/nearby?${stringifiedParams}` : `/api/student/stores/nearby`
}

export const getNearbyStores = async (params: GetNearbyStoresParams, options?: RequestInit): Promise<getNearbyStoresResponse> => {
  
  return customFetch<getNearbyStoresResponse>(getGetNearbyStoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetNearbyStoresQueryKey = (params?: GetNearbyStoresParams,) => {
    return [
    `/api/student/stores/nearby`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetNearbyStoresQueryOptions = <TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(params: GetNearbyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNearbyStoresQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNearbyStores>>> = ({ signal }) => getNearbyStores(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNearbyStoresQueryResult = NonNullable<Awaited<ReturnType<typeof getNearbyStores>>>
export type GetNearbyStoresQueryError = unknown


export function useGetNearbyStores<TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(
 params: GetNearbyStoresParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNearbyStores>>,
          TError,
          Awaited<ReturnType<typeof getNearbyStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNearbyStores<TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(
 params: GetNearbyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNearbyStores>>,
          TError,
          Awaited<ReturnType<typeof getNearbyStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNearbyStores<TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(
 params: GetNearbyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 주변 상점 조회
 */

export function useGetNearbyStores<TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(
 params: GetNearbyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNearbyStoresQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 지도를 위한 상점 전체 목록을 조회합니다.
 * @summary [학생] 지도용 상점 전체 조회
 */
export type getStoreMapResponse200 = {
  data: CommonResponseListStudentStoreMapResponse
  status: 200
}
    
export type getStoreMapResponseSuccess = (getStoreMapResponse200) & {
  headers: Headers;
};
;

export type getStoreMapResponse = (getStoreMapResponseSuccess)

export const getGetStoreMapUrl = (params?: GetStoreMapParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/student/stores/map?${stringifiedParams}` : `/api/student/stores/map`
}

export const getStoreMap = async (params?: GetStoreMapParams, options?: RequestInit): Promise<getStoreMapResponse> => {
  
  return customFetch<getStoreMapResponse>(getGetStoreMapUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoreMapQueryKey = (params?: GetStoreMapParams,) => {
    return [
    `/api/student/stores/map`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetStoreMapQueryOptions = <TData = Awaited<ReturnType<typeof getStoreMap>>, TError = unknown>(params?: GetStoreMapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreMap>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoreMapQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoreMap>>> = ({ signal }) => getStoreMap(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoreMap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoreMapQueryResult = NonNullable<Awaited<ReturnType<typeof getStoreMap>>>
export type GetStoreMapQueryError = unknown


export function useGetStoreMap<TData = Awaited<ReturnType<typeof getStoreMap>>, TError = unknown>(
 params: undefined |  GetStoreMapParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreMap>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreMap>>,
          TError,
          Awaited<ReturnType<typeof getStoreMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreMap<TData = Awaited<ReturnType<typeof getStoreMap>>, TError = unknown>(
 params?: GetStoreMapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreMap>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreMap>>,
          TError,
          Awaited<ReturnType<typeof getStoreMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreMap<TData = Awaited<ReturnType<typeof getStoreMap>>, TError = unknown>(
 params?: GetStoreMapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreMap>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 지도용 상점 전체 조회
 */

export function useGetStoreMap<TData = Awaited<ReturnType<typeof getStoreMap>>, TError = unknown>(
 params?: GetStoreMapParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreMap>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoreMapQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 위도, 경도가 일치하는 상점 목록을 조회합니다. (같은 건물/위치)
 * @summary [학생] 특정 위치 상점 목록 조회
 */
export type getStoresByLocationResponse200 = {
  data: CommonResponseListStudentStoreResponse
  status: 200
}
    
export type getStoresByLocationResponseSuccess = (getStoresByLocationResponse200) & {
  headers: Headers;
};
;

export type getStoresByLocationResponse = (getStoresByLocationResponseSuccess)

export const getGetStoresByLocationUrl = (params: GetStoresByLocationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/student/stores/location?${stringifiedParams}` : `/api/student/stores/location`
}

export const getStoresByLocation = async (params: GetStoresByLocationParams, options?: RequestInit): Promise<getStoresByLocationResponse> => {
  
  return customFetch<getStoresByLocationResponse>(getGetStoresByLocationUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoresByLocationQueryKey = (params?: GetStoresByLocationParams,) => {
    return [
    `/api/student/stores/location`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetStoresByLocationQueryOptions = <TData = Awaited<ReturnType<typeof getStoresByLocation>>, TError = unknown>(params: GetStoresByLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoresByLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoresByLocationQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoresByLocation>>> = ({ signal }) => getStoresByLocation(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoresByLocation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoresByLocationQueryResult = NonNullable<Awaited<ReturnType<typeof getStoresByLocation>>>
export type GetStoresByLocationQueryError = unknown


export function useGetStoresByLocation<TData = Awaited<ReturnType<typeof getStoresByLocation>>, TError = unknown>(
 params: GetStoresByLocationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoresByLocation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoresByLocation>>,
          TError,
          Awaited<ReturnType<typeof getStoresByLocation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoresByLocation<TData = Awaited<ReturnType<typeof getStoresByLocation>>, TError = unknown>(
 params: GetStoresByLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoresByLocation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoresByLocation>>,
          TError,
          Awaited<ReturnType<typeof getStoresByLocation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoresByLocation<TData = Awaited<ReturnType<typeof getStoresByLocation>>, TError = unknown>(
 params: GetStoresByLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoresByLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 특정 위치 상점 목록 조회
 */

export function useGetStoresByLocation<TData = Awaited<ReturnType<typeof getStoresByLocation>>, TError = unknown>(
 params: GetStoresByLocationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoresByLocation>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoresByLocationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 소속 대학에서 이번 주 찜이 가장 많이 늘어난 상점 Top 10을 조회합니다.
 * @summary [학생] 이번 주 핫한 가게 조회
 */
export type getHotStoresResponse200 = {
  data: CommonResponseListHotStoreResponse
  status: 200
}

export type getHotStoresResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}
    
export type getHotStoresResponseSuccess = (getHotStoresResponse200) & {
  headers: Headers;
};
export type getHotStoresResponseError = (getHotStoresResponse403) & {
  headers: Headers;
};

export type getHotStoresResponse = (getHotStoresResponseSuccess | getHotStoresResponseError)

export const getGetHotStoresUrl = () => {


  

  return `/api/student/stores/hot`
}

export const getHotStores = async ( options?: RequestInit): Promise<getHotStoresResponse> => {
  
  return customFetch<getHotStoresResponse>(getGetHotStoresUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetHotStoresQueryKey = () => {
    return [
    `/api/student/stores/hot`
    ] as const;
    }

    
export const getGetHotStoresQueryOptions = <TData = Awaited<ReturnType<typeof getHotStores>>, TError = SwaggerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHotStoresQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHotStores>>> = ({ signal }) => getHotStores({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHotStoresQueryResult = NonNullable<Awaited<ReturnType<typeof getHotStores>>>
export type GetHotStoresQueryError = SwaggerErrorResponse


export function useGetHotStores<TData = Awaited<ReturnType<typeof getHotStores>>, TError = SwaggerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHotStores>>,
          TError,
          Awaited<ReturnType<typeof getHotStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHotStores<TData = Awaited<ReturnType<typeof getHotStores>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHotStores>>,
          TError,
          Awaited<ReturnType<typeof getHotStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHotStores<TData = Awaited<ReturnType<typeof getHotStores>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 이번 주 핫한 가게 조회
 */

export function useGetHotStores<TData = Awaited<ReturnType<typeof getHotStores>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHotStoresQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




