/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CommonResponseVoid,
  SwaggerErrorResponse
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 학생이 특정 소속에 가입합니다.
 * @summary [학생] 소속 가입
 */
export type joinOrganizationResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type joinOrganizationResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type joinOrganizationResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type joinOrganizationResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type joinOrganizationResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type joinOrganizationResponseSuccess = (joinOrganizationResponse200) & {
  headers: Headers;
};
export type joinOrganizationResponseError = (joinOrganizationResponse400 | joinOrganizationResponse403 | joinOrganizationResponse404 | joinOrganizationResponse409) & {
  headers: Headers;
};

export type joinOrganizationResponse = (joinOrganizationResponseSuccess | joinOrganizationResponseError)

export const getJoinOrganizationUrl = (organizationId: number,) => {


  

  return `/api/student/organizations/${organizationId}/membership`
}

export const joinOrganization = async (organizationId: number, options?: RequestInit): Promise<joinOrganizationResponse> => {
  
  return customFetch<joinOrganizationResponse>(getJoinOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getJoinOrganizationMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof joinOrganization>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['joinOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof joinOrganization>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  joinOrganization(organizationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type JoinOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof joinOrganization>>>
    
    export type JoinOrganizationMutationError = SwaggerErrorResponse

    /**
 * @summary [학생] 소속 가입
 */
export const useJoinOrganization = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof joinOrganization>>,
        TError,
        {organizationId: number},
        TContext
      > => {
      return useMutation(getJoinOrganizationMutationOptions(options), queryClient);
    }
    /**
 * 학생이 특정 소속에서 탈퇴합니다.
 * @summary [학생] 소속 탈퇴
 */
export type leaveOrganizationResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type leaveOrganizationResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type leaveOrganizationResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type leaveOrganizationResponseSuccess = (leaveOrganizationResponse204) & {
  headers: Headers;
};
export type leaveOrganizationResponseError = (leaveOrganizationResponse403 | leaveOrganizationResponse404) & {
  headers: Headers;
};

export type leaveOrganizationResponse = (leaveOrganizationResponseSuccess | leaveOrganizationResponseError)

export const getLeaveOrganizationUrl = (organizationId: number,) => {


  

  return `/api/student/organizations/${organizationId}/membership`
}

export const leaveOrganization = async (organizationId: number, options?: RequestInit): Promise<leaveOrganizationResponse> => {
  
  return customFetch<leaveOrganizationResponse>(getLeaveOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getLeaveOrganizationMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof leaveOrganization>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['leaveOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof leaveOrganization>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  leaveOrganization(organizationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LeaveOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof leaveOrganization>>>
    
    export type LeaveOrganizationMutationError = SwaggerErrorResponse

    /**
 * @summary [학생] 소속 탈퇴
 */
export const useLeaveOrganization = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof leaveOrganization>>,
        TError,
        {organizationId: number},
        TContext
      > => {
      return useMutation(getLeaveOrganizationMutationOptions(options), queryClient);
    }
    /**
 * 학생이 소속을 변경합니다. 기존 동종 소속은 자동 탈퇴됩니다.
 * @summary [학생] 소속 변경
 */
export type changeOrganizationResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type changeOrganizationResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type changeOrganizationResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type changeOrganizationResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type changeOrganizationResponseSuccess = (changeOrganizationResponse200) & {
  headers: Headers;
};
export type changeOrganizationResponseError = (changeOrganizationResponse400 | changeOrganizationResponse403 | changeOrganizationResponse404) & {
  headers: Headers;
};

export type changeOrganizationResponse = (changeOrganizationResponseSuccess | changeOrganizationResponseError)

export const getChangeOrganizationUrl = (organizationId: number,) => {


  

  return `/api/student/organizations/${organizationId}/membership`
}

export const changeOrganization = async (organizationId: number, options?: RequestInit): Promise<changeOrganizationResponse> => {
  
  return customFetch<changeOrganizationResponse>(getChangeOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}




export const getChangeOrganizationMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changeOrganization>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['changeOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeOrganization>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  changeOrganization(organizationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof changeOrganization>>>
    
    export type ChangeOrganizationMutationError = SwaggerErrorResponse

    /**
 * @summary [학생] 소속 변경
 */
export const useChangeOrganization = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeOrganization>>,
        TError,
        {organizationId: number},
        TContext
      > => {
      return useMutation(getChangeOrganizationMutationOptions(options), queryClient);
    }
    