/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseListUniversityResponse,
  CommonResponseLong,
  CommonResponseVoid,
  CreateUniversityRequest,
  UpdateUniversityRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 전체 대학 목록을 조회합니다.
 * @summary [공통] 대학 목록 조회
 */
export type getUniversitiesResponse200 = {
  data: CommonResponseListUniversityResponse
  status: 200
}
    
export type getUniversitiesResponseSuccess = (getUniversitiesResponse200) & {
  headers: Headers;
};
;

export type getUniversitiesResponse = (getUniversitiesResponseSuccess)

export const getGetUniversitiesUrl = () => {


  

  return `/api/universities`
}

export const getUniversities = async ( options?: RequestInit): Promise<getUniversitiesResponse> => {
  
  return customFetch<getUniversitiesResponse>(getGetUniversitiesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUniversitiesQueryKey = () => {
    return [
    `/api/universities`
    ] as const;
    }

    
export const getGetUniversitiesQueryOptions = <TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUniversitiesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUniversities>>> = ({ signal }) => getUniversities({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUniversitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getUniversities>>>
export type GetUniversitiesQueryError = unknown


export function useGetUniversities<TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUniversities>>,
          TError,
          Awaited<ReturnType<typeof getUniversities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUniversities<TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUniversities>>,
          TError,
          Awaited<ReturnType<typeof getUniversities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUniversities<TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 대학 목록 조회
 */

export function useGetUniversities<TData = Awaited<ReturnType<typeof getUniversities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUniversities>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUniversitiesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 새로운 대학을 등록합니다.
 * @summary [관리자] 대학 등록
 */
export type createUniversityResponse200 = {
  data: CommonResponseLong
  status: 200
}
    
export type createUniversityResponseSuccess = (createUniversityResponse200) & {
  headers: Headers;
};
;

export type createUniversityResponse = (createUniversityResponseSuccess)

export const getCreateUniversityUrl = () => {


  

  return `/api/universities`
}

export const createUniversity = async (createUniversityRequest: CreateUniversityRequest, options?: RequestInit): Promise<createUniversityResponse> => {
  
  return customFetch<createUniversityResponse>(getCreateUniversityUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUniversityRequest,)
  }
);}




export const getCreateUniversityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUniversity>>, TError,{data: CreateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createUniversity>>, TError,{data: CreateUniversityRequest}, TContext> => {

const mutationKey = ['createUniversity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUniversity>>, {data: CreateUniversityRequest}> = (props) => {
          const {data} = props ?? {};

          return  createUniversity(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUniversityMutationResult = NonNullable<Awaited<ReturnType<typeof createUniversity>>>
    export type CreateUniversityMutationBody = CreateUniversityRequest
    export type CreateUniversityMutationError = unknown

    /**
 * @summary [관리자] 대학 등록
 */
export const useCreateUniversity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUniversity>>, TError,{data: CreateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUniversity>>,
        TError,
        {data: CreateUniversityRequest},
        TContext
      > => {
      return useMutation(getCreateUniversityMutationOptions(options), queryClient);
    }
    /**
 * 대학을 삭제합니다.
 * @summary [관리자] 대학 삭제
 */
export type deleteUniversityResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type deleteUniversityResponseSuccess = (deleteUniversityResponse200) & {
  headers: Headers;
};
;

export type deleteUniversityResponse = (deleteUniversityResponseSuccess)

export const getDeleteUniversityUrl = (universityId: number,) => {


  

  return `/api/universities/${universityId}`
}

export const deleteUniversity = async (universityId: number, options?: RequestInit): Promise<deleteUniversityResponse> => {
  
  return customFetch<deleteUniversityResponse>(getDeleteUniversityUrl(universityId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteUniversityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUniversity>>, TError,{universityId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUniversity>>, TError,{universityId: number}, TContext> => {

const mutationKey = ['deleteUniversity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUniversity>>, {universityId: number}> = (props) => {
          const {universityId} = props ?? {};

          return  deleteUniversity(universityId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUniversityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUniversity>>>
    
    export type DeleteUniversityMutationError = unknown

    /**
 * @summary [관리자] 대학 삭제
 */
export const useDeleteUniversity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUniversity>>, TError,{universityId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUniversity>>,
        TError,
        {universityId: number},
        TContext
      > => {
      return useMutation(getDeleteUniversityMutationOptions(options), queryClient);
    }
    /**
 * 대학 정보를 수정합니다.
 * @summary [관리자] 대학 수정
 */
export type updateUniversity1Response200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type updateUniversity1ResponseSuccess = (updateUniversity1Response200) & {
  headers: Headers;
};
;

export type updateUniversity1Response = (updateUniversity1ResponseSuccess)

export const getUpdateUniversity1Url = (universityId: number,) => {


  

  return `/api/universities/${universityId}`
}

export const updateUniversity1 = async (universityId: number,
    updateUniversityRequest: UpdateUniversityRequest, options?: RequestInit): Promise<updateUniversity1Response> => {
  
  return customFetch<updateUniversity1Response>(getUpdateUniversity1Url(universityId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUniversityRequest,)
  }
);}




export const getUpdateUniversity1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUniversity1>>, TError,{universityId: number;data: UpdateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUniversity1>>, TError,{universityId: number;data: UpdateUniversityRequest}, TContext> => {

const mutationKey = ['updateUniversity1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUniversity1>>, {universityId: number;data: UpdateUniversityRequest}> = (props) => {
          const {universityId,data} = props ?? {};

          return  updateUniversity1(universityId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUniversity1MutationResult = NonNullable<Awaited<ReturnType<typeof updateUniversity1>>>
    export type UpdateUniversity1MutationBody = UpdateUniversityRequest
    export type UpdateUniversity1MutationError = unknown

    /**
 * @summary [관리자] 대학 수정
 */
export const useUpdateUniversity1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUniversity1>>, TError,{universityId: number;data: UpdateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUniversity1>>,
        TError,
        {universityId: number;data: UpdateUniversityRequest},
        TContext
      > => {
      return useMutation(getUpdateUniversity1MutationOptions(options), queryClient);
    }
    